### PR TITLE
[sweep:v7r3] added op_type option in elasticsearch options

### PR DESCRIPTION
**Pull request by DIRACGridBot**
Sweep #5987 `added op_type option in elasticsearch options` to `rel-v7r3`.

Adding original author @panta-123 as watcher.

BEGINRELEASENOTES

*Elasticsearch
NEW: option op_type in index API for Elasticsearch

ENDRELEASENOTES

### CODE REVIEW

**Comment by chrisburr** [comment]
In case anyone is confused: This has appeared now as I fixed a bug in the sweeper.

(It was failing to find an authors email address when they have no commits. You would think this is impossible but if they commit without using an email registered in their GitHub account it shows as an unowned commit in GitHub.)

**Review by chrisburr — APPROVED** [review]

**Comment by fstagni** [comment]
the sweeper of this failed (again)

**Comment by panta-123** [comment]
Let me if i can do anything from my side.

**Comment by chrisburr** [comment]
The sweeper bug is fixed with: https://github.com/DIRACGrid/pr-sweeper/commit/8f0ddefa5e01ab2cc45e1a728d5e8040e87ce929

**Pull request merged**
