### PR TITLE
[8.0] docs: Tornado logs split 

### PR DESCRIPTION
**Pull request by bertrandrigaud**
BEGINRELEASENOTES
Documentation on how to deploy a third party tool (fluent-bit) to grab, format and send Dirac current logs to ElasticSearch and/or splitted logs files

ENDRELEASENOTES

### CODE REVIEW

**Comment by bertrandrigaud** [comment]
This documentation shows how to use fluent-bit in order to format and send Dirac current logs to ElasticSearch and or files. For ElasticSearch, there are also kibana and grafana dashboards I can provide but I don't know where to put it (see "???" line 228)
Any advice/comment?

**Comment by bertrandrigaud** [comment]
Maybe I could put it near this area : https://github.com/DIRACGrid/DIRAC/tree/rel-v8r0/dashboards/diracLogs ?
Something like https://github.com/DIRACGrid/DIRAC/tree/rel-v8r0/dashboards/tornadoLogs ?

**Comment by bertrandrigaud** [comment]
I also have a problem with docs building, the output error message is not clear to me: 
```
File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/7232/docs/source/conf.py", line 52, in <module>
    raise RuntimeError("Something went wrong with the documentation creation")
```
@andresailer can you help me on this please?

**Comment by fstagni** [comment]
> Maybe I could put it near this area : https://github.com/DIRACGrid/DIRAC/tree/rel-v8r0/dashboards/diracLogs ? Something like https://github.com/DIRACGrid/DIRAC/tree/rel-v8r0/dashboards/tornadoLogs ?

Exactly!

**Comment by fstagni** [comment]
...still a draft?

**Comment by fstagni** [comment]
@bertrandrigaud is this still really a draft or we can merge?

**Comment by bertrandrigaud** [comment]
Yes, if it is ok for you, you can merge!

**Pull request merged**
