### PR TITLE
[v6r21] fix: return value of getJobParameters changed

### PR DESCRIPTION
**Pull request by fstagni**
BEGINRELEASENOTES

*Interfaces
FIX: return value of getJobParameters changed

ENDRELEASENOTES

### CODE REVIEW

**Comment by atsareg** [comment]
I guess without this one v6r21p2 is buggy ?

**Comment by fstagni** [comment]
Well even v6r21 is buggy in this sense. But since it's the API, a speedy release would be better.

**Comment by atsareg** [comment]
OK, will include it into v6r21p2

**Comment by chaen** [comment]
@atsareg if you wait just a few minutes, I have a one line fix that I would want in p2 as well please

**Comment by atsareg** [comment]
OK, started the timer.

**Comment by chaen** [comment]
Ahhhh pressuuuuure :D

**Pull request merged**
