### PR TITLE
[v7r2] Refresher: import tornado modules only if needed

### PR DESCRIPTION
**Pull request by chaen**
BEGINRELEASENOTES
*Configuration
CHANGE: split standard and tornado refresher in two files to avoid tornado dependency on the client

ENDRELEASENOTES

### CODE REVIEW

**Review by chrisburr — APPROVED** [review]

**Comment by chrisburr** [comment]
@chaen I guess you've just forgotten about removing WIP? Or is there something else still to come?

**Comment by chaen** [comment]
indeed thanks

**Comment by fstagni** [comment]
Can you add the release notes then?

**Review by fstagni — APPROVED** [review]

**Comment by chaen** [comment]
done !

**Pull request merged**
