### PR TITLE
[v6r19] Ensure multiple RequiredTag values get converted to a list

### PR DESCRIPTION
**Pull request by sfayer**
Hi,

We realised that when a CE set multiple RequiredTags, the jobs would never get scheduled there (even if they had the correct tags). We tracked this down to the RequiredTag field being handled as a string, so multiple tags don't get correctly converted to SQL in the TaskQueueDB resulting in no jobs matching. This fix ensures RequiredTags are handled the same as Tags in the SiteDirector which fixes the issue.

Regards,
Simon

BEGINRELEASENOTES
* WorkloadManagementSystem
FIX: Fix support for multiple values in the RequiredTag CE parameter
ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
This looks OK to me but @atsareg should review it.

**Comment by atsareg** [comment]
The fix is correct. Indeed it was coded without anticipation for multiple RequiredTags. But I think it is not complete. It should be also fixed in the PilotCommands where the queue parameters are obtained

**Comment by fstagni** [comment]
and if fixes are going in pilot 2, they should also go to pilot 3.

**Comment by atsareg** [comment]
This is OK for the patch. For the next release I will try to review how the queue parameters are retrieved from the CS (Resources helper). This logic is duplicated there already, should be all collected in one place

**Pull request merged**
