### PR TITLE
[v7] fix DataManagement/ConfigTemplate from bad merge

### PR DESCRIPTION
**Pull request by andresailer**
There was a bad merge in the ConfigTemplete.cfg for DataManagement, @chaen, please check

BEGINRELEASENOTES

*Docs:
CHANGE: diracdoctools concatcfg: catch exception when parsing of ConfigTemplate fails, return with 1

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
I'm not sure the travis failures are related to the changes you did though

**Comment by fstagni** [comment]
There might be more bad merges. Let me have a look.

**Comment by fstagni** [comment]
@andresailer I created a PR for this branch of yours: https://github.com/andresailer/DIRAC/pull/6

**Comment by andresailer** [comment]
Merged your PR to my branch

**Comment by andresailer** [comment]
Hope now the last warning is fixed

**Comment by fstagni** [comment]
All tests are passing. I'll merge this right now.

**Pull request merged**
