### PR TITLE
[v7r1] Fix MySQLDB race condition Tests

### PR DESCRIPTION
**Pull request by chaen**
@aldbr can you please check ? I think it is from when you factorized the MySQL db tests in 1aa7317832

### CODE REVIEW

**Comment by chaen** [comment]
All the tests are failing due to ProxyDB which Andrii is fixing in another PR, so these should be ignored. 
Also, there are cancelled tests. This is apparently due to having failures and using the matrix. This could be solved by setting `fail-fast` to `false`  (https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) Any thought @chrisburr

**Comment by aldbr** [comment]
> @aldbr can you please check ? I think it is from when you factorized the MySQL db tests in [1aa7317](https://github.com/DIRACGrid/DIRAC/commit/1aa731783263c405d4f4f82f123faf77db81ca00)

Yes, I approve the changes, I forgot the `sleep` and didn't notice the callable inside the `pytest` parameters...

**Comment by chaen** [comment]
No Problem. 
@atsareg @fstagni can you please merge ? And then @TaykYoku can rebase his PR once more, that should finally pass the tests.

**Comment by fstagni** [comment]
Done. @TaykYoku please rebase your PR.

**Pull request merged**
