### PR TITLE
[v7r0] Admin doc Restructuring

### PR DESCRIPTION
**Pull request by andresailer**
To add these instructions to add a dedicated filecatalog (https://groups.google.com/forum/#!msg/diracgrid-forum/dSsZbW4pyt4/Njh5NQvEAgAJ) in the Admin guide, I first wanted to create a place where this can be sensible placed. Thus I started restructuring the AdministratorGuide (AG), to give the existing content a bit more structure.

See result here: https://diracsailer.readthedocs.io/en/fixdoc/AdministratorGuide/index.html

I added a hierarchy on the first page of the AG, and distributed the existing pages according to some categories. Also tweaking some of the headers to have sensible headers displayed in the table of contents. I already found some information that was duplicated (about the "DIRAC" section in the config). 

I also want to add a section about the "general options" shared by all services and agents, because I don't think that exists yet?

BEGINRELEASENOTES

* Docs
CHANGE: the AdministratorGuide has been restructured

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Do you want to make this a real PR? Or you want to add something still?

**Comment by andresailer** [comment]
Both.

**Comment by andresailer** [comment]
Probably this can be merged and I add the rest via a new PR

**Comment by fstagni** [comment]
Is it up for review? you kept the [WIP] in the title.

**Comment by andresailer** [comment]
Have rather limited access to github atm.

**Pull request merged**
