### PR TITLE
[v6r15] dirac-dms-find-lfns: remove space after printout of lfn

### PR DESCRIPTION
**Pull request by andresailer**

### CODE REVIEW

**Comment by chaen** [comment]
Review OK

**Comment by atsareg** [comment]
Review OK. There are conflicts with earlier commits. I will merge it by hand resolving conflicts

**Comment by andresailer** [comment]
Thanks, but actually the conflicts are from later commits.

**Comment by atsareg** [comment]
Conflicting change incorporated by hand

**Pull request closed without merging**
