### PR TITLE
[v6r21] logging filter

### PR DESCRIPTION
**Pull request by andresailer**
BEGINRELEASENOTES

*Resources
NEW: Added the possibility to add filters to log backends to refine the output shown/stored
NEW: Resources.LogFilters.ModuleFilter: Filter that allows one to set the LogLevel for individual modules
NEW: Resources.LogFilter.PatternFilter: Filter to select or reject log output based on words

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Thanks. May I know what's the use case that triggered these changes?

PS: check Travis.

**Comment by andresailer** [comment]
The original trigger was developing and debugging the glue2/bdii reader and the too verbose output from the subprocess module, long time ago.

**Comment by andresailer** [comment]
Pylint and format fixed

**Comment by fstagni** [comment]
I don't see any real issue here. @chaen would you also have a look?

**Pull request merged**
