### PR TITLE
[v7] fix doc warnings from merge

### PR DESCRIPTION
**Pull request by andresailer**
This fixes all the warnings from the documentation that showed up after the last merge.

The removed file was removed in PR #3763 previously

### CODE REVIEW

**Comment by andresailer** [comment]
@atsareg @fstagni please review (and merge)

**Comment by fstagni** [comment]
I don't think that the "step 1/index" file should just be deleted. I think that instead it should be linked from here: https://github.com/DIRACGrid/DIRAC/blob/integration/docs/source/AdministratorGuide/index.rst

**Comment by andresailer** [comment]
I brought back the file (but moved it).
Also you probably should review the content of this section https://dirac.readthedocs.io/en/latest/AdministratorGuide/InstallingDIRACService/index.html#primary-server-installation with respect to the minimal server installation

**Comment by fstagni** [comment]
Yes, you are right. I will merge the 2 files.

**Pull request merged**
