### PR TITLE
[v6r19] Fix DMSHelpers

### PR DESCRIPTION
**Pull request by phicharp**
BEGINRELEASENOTES
*DMS
FIX: return None as LocalSite if an SE is at no site
ENDRELEASENOTES

### CODE REVIEW

**Comment by phicharp** [comment]
PR redone as Travis was not happy the first time since the PR was on the wrong branch

**Comment by chaen** [comment]
That is not good, it breaks the code at quite a few places, for example

```
            res = getSitesForSE(se, gridName='LCG')
            if res['OK'] and len(res['Value']) > 0:
```

**Comment by phicharp** [comment]
I don't think so... This is not the same method... `getLocalSiteForSE()` returns a single site name or `None`

**Comment by phicharp** [comment]
`In [3]: dh.getSitesForSE('NCBJ-BUFFER')`
`Out[3]: {'OK': True, 'Value': ['LCG.NCBJ.pl']}`

**Comment by chaen** [comment]
Oups ! I thought from the diff that getSitesForSE was the modified method.

**Pull request merged**
