### PR TITLE
!!! [v6r13] Retrieval of trusted hosts from Registry

### PR DESCRIPTION
**Pull request by Sbalbp**
Added a new 'getTrustedHosts' method to Registry so that only host with the 'TrustedHost' property are retrieved by the SystemAdministratorIntegrator, instead of every single host in the installation.

### CODE REVIEW

**Comment by fstagni** [comment]
review OK

**Comment by atsareg** [comment]
Why only trusted hosts to be taken into account by the SystemIntegrator ? The only hosts that must be Trusted are web portals and gateways. Now there are few more hosts Trusted as well which should be progressively fixed

**Comment by Sbalbp** [comment]
The idea is to retrieve only those hosts that are server hosts ( they should be tagged as trusted hosts ) and have a SystemAdministrator service, since the list of hosts would usually retrieve all the hosts ( including client ones, who it makes no sense to make SystemAdministrator requests to ).

**Comment by atsareg** [comment]
There are no server and client hosts in DIRAC in general. If a host is configured in the DIRAC Registry, it must run SystemAdministrator service. So, this is the sign of the "server" host. Hosts without the SystemAdministrator running should be reviewed why they are in the Registry and either should be removed or run the SystemAdministrator service. The fact that a host is trusted has no relevance.

**Comment by chaen** [comment]
This is not true Andrei. There are special cases, that I don't want to explicit here. But there might be software that needs to interact with DIRAC, or rely on the DIRAC infrastructure, without actually being DIRAC installations

**Comment by atsareg** [comment]
There can be always special cases, but this is nothing to do with Trusted hosts. If there are hosts that interact with DIRAC services using host certificates for whatever reasons ( like VM hosts ), then we should introduce a flag in the CS that these are not service hosts. So that the monitoring system is not fooled by them.

**Comment by chaen** [comment]
Yes yes, I am just saying that I disagree with this particular statement "If a host is configured in the DIRAC Registry, it must run SystemAdministrator service."

**Comment by atsareg** [comment]
Agreed. But in the tool polling all the hosts one should poll only hosts that run SystemAdministrator. This is naturally done since others will not respond to the call. They will time out which can be a loss of time. So the hosts can be rather pinged before actual SysAdmin call.

**Comment by fstagni** [comment]
Yes pinging host is a good idea for this case. This also leads to consider that:
- in LHCb we should review the list of hosts with "TrustedHost" property
- I am in favour of having a clear way to identify "service" hosts

**Comment by Sbalbp** [comment]
Instead of considering only TrustedHost-tagged hosts, the SystemAdministratorIntegrator now pings the SystemAdministrator service for every host in the list of hosts returned by the Registry, removing those from which it doesn't receive an answer.

**Pull request merged**
