### PR TITLE
[WIP v6r21] Fix problem when not being able to instantiate JobDB

### PR DESCRIPTION
**Pull request by phicharp**
BEGINRELEASENOTES

* WMS
FIX: when an optimiser agent was instantiating JobDB (via the base class) and the machine was overloaded, the connection to the DB failed but this was not noticed and the agent was not working until restarted after max cycles. Now testing JobDB  is valid in OptimizerModule base class and exit if not valid. Eventually this should be using exceptions...
CHANGE: streamlining code in OptimizerModule. Also pep8 formatting (ignore white spaces for reviewing)

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
HI Philippe,thanks. Can you target rel-v6r21? I don't think we want to do anymore patched in the v6r20 series.

**Comment by phicharp** [comment]
I'll try ;-)

**Comment by phicharp** [comment]
Messy as v6r21 has precisely conflicting changes :(
I'll try and do it though, but not before next week...
Putting WIP

**Comment by fstagni** [comment]
Just bumping...

**Comment by phicharp** [comment]
Close to replace with PR for v6r21

**Comment by phicharp** [comment]
Replaced by #3970

**Pull request closed without merging**
