### PR TITLE
[v7r1] Make M2Crypto the default over pyGSI

### PR DESCRIPTION
**Pull request by chaen**
First part of https://github.com/DIRACGrid/DIRAC/issues/4272

BEGINRELEASENOTES
*Core
CHANGE:  use M2Crypto by default
ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
@fstagni  @atsareg there is a bad non resolved merged. I am fixing it here

**Comment by chaen** [comment]
@atsareg @TaykYoku The ProxyDB tests are failing 
```
 test_connectDB (__main__.testDB)
Try to connect to the ProxyDB ... ok
test_getRemoveProxy (__main__.testDB)
Testing get, store proxy ... NOTE: __storeProxyOld function is deprecated (Only for DIRAC v6).
NOTE:   Used at /home/dirac/ServerInstallDIR/DIRAC/FrameworkSystem/DB/ProxyDB.py:352
FAIL
test_getUsers (__main__.testDB)
Try to get users from DB ... ok
test_purgeExpiredProxies (__main__.testDB)
Try to purge expired proxies ... ok

======================================================================
FAIL: test_getRemoveProxy (__main__.testDB)
Testing get, store proxy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dirac/ServerInstallDIR/DIRAC/tests/Integration/Framework/Test_ProxyDB.py", line 451, in test_getRemoveProxy
    ': %s' % result.get('Message') or 'Error message is absent.'))
AssertionError: Must be ended with error: None

----------------------------------------------------------------------
```

Can you please check ? Thanks

**Comment by chrisburr** [comment]
@atsareg @TaykYoku this is still needs fixing before v7r1 can be released

**Comment by TaykYoku** [comment]
@chaen @chrisburr yes, this fixing in a progress

**Comment by TaykYoku** [comment]
@chaen @chrisburr  fixed in #4469

**Comment by TaykYoku** [comment]
@chaen @chrisburr  fixed in #4469

**Comment by chaen** [comment]
Now I see two issues:

One is the known one with the proxy that @TaykYoku is looking at

```
 ======================================================================
ERROR: test_getRemoveProxy (__main__.testDB)
Testing get, store proxy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dirac/ServerInstallDIR/DIRAC/tests/Integration/Framework/Test_ProxyDB.py", line 540, in test_getRemoveProxy
    result = db.getVOMSProxy(dn, group, time, role)
  File "/home/dirac/ServerInstallDIR/DIRAC/FrameworkSystem/DB/ProxyDB.py", line 903, in getVOMSProxy
    attrs = vomsMgr.getVOMSAttributes(chain).get('Value') or ['']
  File "/home/dirac/ServerInstallDIR/DIRAC/Core/Security/VOMS.py", line 39, in getVOMSAttributes
    result = self.getVOMSProxyInfo(proxy, "all")
  File "/home/dirac/ServerInstallDIR/DIRAC/Core/Security/VOMS.py", line 131, in getVOMSProxyInfo
    res = proxyDict['chain'].getVOMSData()
  File "/home/dirac/ServerInstallDIR/DIRAC/Core/Security/m2crypto/X509Chain.py", line 580, in getVOMSData
    res = cert.getVOMSData()
  File "/home/dirac/ServerInstallDIR/DIRAC/Core/Utilities/Decorators.py", line 185, in innerFunc
    return meth(*args, **kwargs)
  File "/home/dirac/ServerInstallDIR/DIRAC/Core/Security/m2crypto/X509Certificate.py", line 382, in getVOMSData
    vomsExt = asn1_utils.decodeVOMSExtension(self.__certObj)
  File "/home/dirac/ServerInstallDIR/DIRAC/Core/Security/m2crypto/asn1_utils.py", line 227, in decodeVOMSExtension
    attrValStr = _decodeASN1String(rdnNameAttr['value'])
  File "/home/dirac/ServerInstallDIR/DIRAC/Core/Security/m2crypto/asn1_utils.py", line 119, in _decodeASN1String
    raise PyAsn1Error("Could not find a correct decoding type")
PyAsn1Error: Could not find a correct decoding type
```

And the other one is with the TaskQueueDB

```
2020-03-10 09:22:20 UTC WorkloadManagement/JobMonitoring ERROR: Exception while calling initialization function
Traceback (most recent call last):
  File "/home/dirac/ServerInstallDIR/DIRAC/Core/DISET/private/Service.py", line 133, in initialize
    result = initFunc(dict(self._serviceInfoDict))
  File "/home/dirac/ServerInstallDIR/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py", line 43, in initializeJobMonitoringHandler
    gTaskQueueDB = TaskQueueDB()
  File "/home/dirac/ServerInstallDIR/DIRAC/WorkloadManagementSystem/DB/TaskQueueDB.py", line 67, in __init__
    raise Exception("Can't create tables: %s" % result['Message'])
Exception: Can't create tables: MySQL Error ( 1131 : Recursive Foreign Keys in tq_Jobs, tq_TQToSites, tq_TQToGridMiddlewares)
2020-03-10 09:22:20 UTC WorkloadManagement/JobMonitoring ERROR: Exception while calling initialization function: Can't create tables: MySQL Error ( 1131 : Recursive Foreign Keys in tq_Jobs, tq_TQToSites, tq_TQToGridMiddlewares)
```

**Comment by fstagni** [comment]
Is the TaskQueueDB issue that you showed only for some specific MySQL version?

**Comment by chaen** [comment]
It only shows up in `(8,slc6,yes)`

**Comment by fstagni** [comment]
I doubt that the `yes` (M2Crypto) flag there means something. If it does, I am not sure we want to debug it...

**Comment by TaykYoku** [comment]
Is this test running with patch #4469 or not?

**Comment by TaykYoku** [comment]
I already see that test running without #4469 patch. 
`PyAsn1Error: Could not find a correct decoding type` should be resolved in #4469.

**Comment by chaen** [comment]
I believe `yes` is for the ThreadPool, not M2Crypto

**Comment by chaen** [comment]
#4469 hides the problem. The fact of having `user_1` instead of `user` should not be a problem. But let's discuss it on that PR

**Comment by TaykYoku** [comment]
@chaen can you describe your opinion in #4469 to start discuss, thanks.

**Comment by chaen** [comment]
@fstagni again the `expected` checks are not the correct one

**Comment by chaen** [comment]
@fstagni can you please correct the `expected checks`, and also look at the TaskQueueDB error ?

**Comment by fstagni** [comment]
I have fixed the `expected` checks. I will have a look at the TaskQueueDB thing later.

**Comment by chaen** [comment]
@fstagni any news ?

**Comment by fstagni** [comment]
Sorry, I was busy with other stuff and this slipped a bit below. I will try tomorrow morning.

**Comment by fstagni** [comment]
The TaskQueueDB errors that you mention are not appearing in the last tests run.

**Comment by chaen** [comment]
you mean I should just rebase that one and re-run ?

**Comment by fstagni** [comment]
I mean that this:
```
2020-03-10 09:22:20 UTC WorkloadManagement/JobMonitoring ERROR: Exception while calling initialization function
Traceback (most recent call last):
  File "/home/dirac/ServerInstallDIR/DIRAC/Core/DISET/private/Service.py", line 133, in initialize
    result = initFunc(dict(self._serviceInfoDict))
  File "/home/dirac/ServerInstallDIR/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py", line 43, in initializeJobMonitoringHandler
    gTaskQueueDB = TaskQueueDB()
  File "/home/dirac/ServerInstallDIR/DIRAC/WorkloadManagementSystem/DB/TaskQueueDB.py", line 67, in __init__
    raise Exception("Can't create tables: %s" % result['Message'])
Exception: Can't create tables: MySQL Error ( 1131 : Recursive Foreign Keys in tq_Jobs, tq_TQToSites, tq_TQToGridMiddlewares)
2020-03-10 09:22:20 UTC WorkloadManagement/JobMonitoring ERROR: Exception while calling initialization function: Can't create tables: MySQL Error ( 1131 : Recursive Foreign Keys in tq_Jobs, tq_TQToSites, tq_TQToGridMiddlewares)
```
that you showed above does not appear anywhere in the last tests run.

**Pull request merged**
