### PR TITLE
[v7r2] Backport OpenSSL 3 support

### PR DESCRIPTION
**Pull request by chrisburr**
BEGINRELEASENOTES

*Core
NEW: Support OpenSSL 3.0.x

ENDRELEASENOTES

Backport of https://github.com/DIRACGrid/DIRAC/pull/6643

### CODE REVIEW

**Comment by chaen** [comment]
do you really think it's worth backporting to v7r2 ? 
especially that if I remember ocrrectly, there are quite a few M2Crypto fixes in v7r3 that are not in v7r2

**Comment by chrisburr** [comment]
If it's trivial I see no reason not to, if it takes more than 2 minutes then I agree it's not worth it.

**Comment by chaen** [comment]
The reason is that it's super old, and if small VO start running into troubles, debugging it will be nearly impossible

**Comment by fstagni** [comment]
Let's not...

**Comment by chrisburr** [comment]
Okay, then we should remove v7r2 from the DIRACOS2 CI.

**Comment by fstagni** [comment]
> Okay, then we should remove v7r2 from the DIRACOS2 CI.

I think we could.

**Pull request closed without merging**
