### PR TITLE
[v6r14] Several changes on ComponentMonitoring

### PR DESCRIPTION
**Pull request by Sbalbp**
Due to the fact that the requests to the ComponentMonitoring service are currently made by the server's SysAdmin service ( and not from the original caller of the top level script/CLI command ) the certificate of the server is used instead, meaning that the calls turn out unauthorized.

To avoid this, the InstallTools' monitorInstallation/Uninstallation funcions that make the requests to the ComponentMonitoring service have been moved so that they are callable by the scripts or the CLI.

Also, some minor changes to the InstalledComponentsDB module have been made to avoid sqlAlchemy warnings.

Lastly, I'm PR'ing the DB-populating script again, since I made the last PR for it to integration by mistake.

### CODE REVIEW

**Comment by atsareg** [comment]
The more I see the necessary fixes in various places to enable the component monitoring, the more I think that the proper way should be different: remove enabling of monitoring from all the installation logic whatsoever, instead call the populate command each time a new component is installed. This will relieve the InstallTools from the stuff which is not directly related to the installation proper and will concentrate the whole logic in just one place which is a lot of simplification. Please, comment.

**Comment by Sbalbp** [comment]
I see 2 downsides to that approach:
* The populating script is not able to find out when the un/installations were made nor who they were made by ( the script assumes they were made just now ), so we would miss that information.
* We force the user to run the script pretty much all the time to make sure that the information is always up to date, which may become an annoyance.

**Comment by atsareg** [comment]
I do not really care much about who has done the new installation. If one cares, then this can be seen in the ownership of the CS comment, for example. If, as I suggest, the practice is to run the script right after the new installation, then the first bullet is irrelevant. The second bullet is about the user - who is that ? the person who wants to see the status or who installs the new components ? I think you mean the first one. Then again it is irrelevant, this is the dutu of the administrator to start the components properly including the monitoring stuff if this is the policy of the given installation. However, if the contents of the database and the reality will get out of sync often, then the user looking at the status of the system will have to resync each time anyway. This is not related to the installation procedure.

**Comment by fstagni** [comment]
Several comments on my side:

- while agreeing on the fact that it's not strictly important who has installed what, in case we want to know, the ownership of the CS comment is useless: first of all, the CS comment ownership is for component type, not for component instance (I can install N instances of a service). 
- the 'populate' script is a one-time script, so the resulting timestamp of installed components is clearly artificial, and there's nothing we can do for that.
- this 'populate' script is a heavy one, especially for an installation like the LHCb one, while updating the InstalledComponentsDB every time a new component is installed is an easy task that assures, on top, that we will never get out of sync: for a large installation this is really an important point.

**Comment by atsareg** [comment]
My point is that the installation tools and monitoring basic tools are not mixed together. What I suggest is the following:
- make a utility to update the InstalledComponentsDB either entirely or for a specific component. This utility is NOT part of the InstallTools utility;
- dirac-populate-... script will use this utility to resync the entire database;
- dirac-install-... scripts will use this utility to update for their corresponding components as an extra step in case of successful installation, it can be controlled with a switch;
- SysAdminClientCLI will use this utility to update the components in the corresponding install/uninstall commands if the operation is successful;
- InstallTools are cleaned from the monitoring stuff making it cleaner ( already too heavy );
- installing a site from scratch will be done as it is now followed by a one-time dirac-populate-...
So, I do not suggest to run the populate script each time. You do what is needed to do in each case

**Comment by fstagni** [comment]
The Monitoring utility has been added. I looked quickly at the code and I don't have specific comments.

**Pull request merged**
