### PR TITLE
[v8r0] Support Authlib v1.2.1

### PR DESCRIPTION
**Pull request by chrisburr**
BEGINRELEASENOTES

*Framework
FIX: Support Authlib v1.2.1

ENDRELEASENOTES

### CODE REVIEW

**Comment by chrisburr** [comment]
There's more here than I know how to test. I guess @atsareg is the only user to know what needs to be changed.

**Comment by andresailer** [comment]
Currently the doc builds for rel-v8 are failing because readthedocs pulls in a newer authlib that isn't supported without this PR.
So either this PR gets merged soon, or we need to fix authlib in the environment.yml used by readthedocs.

https://github.com/DIRACGrid/DIRAC/blob/1228f153e8359657151fa09d71cc1c5b2af30c06/environment.yml#L103

**Comment by atsareg** [comment]
How did yo notice this change ? In the tests ? It is not mentioned in the 1.2.1 change log on their site.

**Comment by chrisburr** [comment]
> How did yo notice this change ? In the tests ? It is not mentioned in the 1.2.1 change log on their site.

The DIRACOS2. nigthly CI started failing.

**Comment by chrisburr** [comment]
@atsareg do you have a solution to this? It's preventing us from being able to release.

**Comment by fstagni** [comment]
I added one commit, mostly guided by @atsareg that fixes the issue.

**Comment by fstagni** [comment]
This is rather urgent, so merging it now.

**Pull request merged**
