### PR TITLE
[v6r17] Add executeWithoutServerCertificate function

### PR DESCRIPTION
**Pull request by chaen**
This is useful for Agents.

### CODE REVIEW

**Comment by fstagni** [comment]
Any specific ideas on where this may be used?

**Comment by atsareg** [comment]
The use case is in the doc string of the new method

**Comment by atsareg** [comment]
Review OK

**Comment by chaen** [comment]
My use case is more to use it in the calls than as a decorator. For example, in an agent:

``` res = executeWithoutServerCertificate(dfc.addFile)(lfn) ```

**Pull request merged**
