### PR TITLE
[v6r22] Allow to retrieve multiple variables from MonitoringDB

### PR DESCRIPTION
**Pull request by yujikato**
BEGINRELEASENOTES
Thank you for writing the text to appear in the release notes. It will show up
exactly as it appears between the two bold lines

Please follow the template:
*Monitoring
CHANGE: Allow to retrieve multiple variables from Monitoring DB.
                Add functions to calculate efficiency.

ENDRELEASENOTES

### CODE REVIEW

**Comment by zmathe** [comment]
@aldbr Could you please have a look pytest? It seams to me it is related to your change:
```
   htce._HTCondorCEComputingElement__writeSub( "dirac-install", 42 ) #pylint: disable=E1101

E       TypeError: __writeSub() takes exactly 4 arguments (3 given)
```

**Comment by aldbr** [comment]
@zmathe Yes I added a new parameter in `writeSub` but I made this change in v7r0 and I corrected this test too. It looks like it is using DIRAC v7r0 with tests based on v6r22. Is that possible?

**Comment by andresailer** [comment]
It is this change #4518 , which had the test only fixed in v7r0 here  #4526

**Comment by atsareg** [comment]
Can you please rebase on the current state of the rel-v6r22 branch to see if the tests are fixed.

**Comment by yujikato** [comment]
> 
> 
> Can you please rebase on the current state of the rel-v6r22 branch to see if the tests are fixed.

It is OK now.

**Pull request merged**
