### PR TITLE
[v7r2] Fix CS thread leaks

### PR DESCRIPTION
**Pull request by atsareg**
This PR is to fix #5589. 

BEGINRELEASENOTES

*Configuration
FIX:  ServiceInterface.py - use ThreadPoolExecutor instead of ThreadPool to avoid thread leaks in the ConfigurationServer

ENDRELEASENOTES

### CODE REVIEW

**Review by fstagni — DISMISSED** [review]

**Comment by chrisburr** [comment]
Looks good but can you squash these commits into one?

**Comment by atsareg** [comment]
I can squash commits locally. But is there a way to squash commits in a way that can be pushed to my remote same branch so that  no new PR will be necessary ?

**Comment by andresailer** [comment]
```
# git squash
git push --force your_remote this_branch
```

**Comment by atsareg** [comment]
Yes, forced pushing works. Thanks

**Review by chrisburr — APPROVED** [review]

**Pull request merged**
