### PR TITLE
[8.0] Remove LcgFileCatalogClient

### PR DESCRIPTION
**Pull request by chrisburr**
The `lfcthr` Python module isn't included in DIRACOS2 but I don't think anyone is still using it so I guess this code can be simply removed?

BEGINRELEASENOTES

*DataManagement
CHANGE: The LcgFileCatalogClient has been removed

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
Green light on my side, but let's just make sure with Belle II (@hmiyake @iueda )

**Comment by iueda** [comment]
I think it is ok for Belle II, but just double checking... for confirmation.
(Even if we find something, we should solve it by the time we move to 8.0...)

**Comment by iueda** [comment]
Talking with the Belle II colleagues, we all think it is ok for us.

**Review by fstagni — APPROVED** [review]

**Review by chaen — APPROVED** [review]

**Comment by atsareg** [comment]
What form should be the version in the __init__.py now ?

**Comment by chrisburr** [comment]
> What form should be the version in the init.py now ?

It's not needed at all as it comes from the tag, see #5417

**Pull request merged**
