### PR TITLE
[v7r1] Merging v7r0

### PR DESCRIPTION
**Pull request by atsareg**
This is just a PR to trigger the tests

### CODE REVIEW

**Comment by chaen** [comment]
The tests have failed though

**Comment by fstagni** [comment]
And I have the impression we have seen that failure already recently:

```
ClientInstallDIR/DIRAC/tests/Integration/Monitoring/Test_MonitoringSystem.py::MonitoringTestChain::test_getLastDayData FAILED
___________________ MonitoringTestChain.test_getLastDayData ____________________
self = <DIRAC.tests.Integration.Monitoring.Test_MonitoringSystem.MonitoringTestChain testMethod=test_getLastDayData>
    def test_getLastDayData(self):
      params = {'Status': 'Running', 'Site': 'LCG.NIKHEF.nl'}
      result = self.client.getLastDayData('WMSHistory', params)
>     self.assertTrue(result['OK'])
E     AssertionError: False is not true
ClientInstallDIR/DIRAC/tests/Integration/Monitoring/Test_MonitoringSystem.py:363: AssertionError
```

**Comment by atsareg** [comment]
The failures were due to the server installation which failed due to (non-existing ?) diracos master tag. Interesting that I did not merge this PR. I just did a usual push to the central Github repo. However, this had the same effect as the PR merge. But the link to the result of the tests was lost. How do you see it now ?

**Comment by chrisburr** [comment]
> But the link to the result of the tests was lost. How do you see it now ?

Click "View details" or the little green tick/red cross next to the commit hash.

**Comment by fstagni** [comment]
Search in the Actions like in the screenshot below:

image

**Comment by atsareg** [comment]
Yes, this was in the details:

    2020-04-19 21:38:31 UTC dirac-install [ERROR] Cannot download diracos-master.tar.gz: Timeout

**Comment by atsareg** [comment]
@fstagni : How do you see the failing test in the MonitoringSystem above ? I see only reports like:

   ERROR: Client integration tests failed with 1
   ##[error]Process completed with exit code 1.

**Comment by fstagni** [comment]
Then I open the text in the "Client tests", which are the previous step:
image
(sometimes the server tests fail, but in this case it was the client)
and once in there I look for "FAILED" in the search box:
image

**Pull request merged**
