### PR TITLE
[v7r0] M2crypto: support more exotic DN

### PR DESCRIPTION
**Pull request by chaen**
This should fix the problem of #4469 
It basically supports some more string types and more fields for the DN

BEGINRELEASENOTES

*Core
NEW: M2Crypto support more Distinguished Names 

ENDRELEASENOTES

### CODE REVIEW

**Comment by TaykYoku** [comment]
Thanks for this implementation.

**Comment by fstagni** [comment]
Do you want to merge and propagate this now, so that the other PRs can be rebased on top?

**Comment by chaen** [comment]
I'd say so

**Comment by fstagni** [comment]
Done.

**Pull request merged**
