### PR TITLE
Fix stop_agent location

### PR DESCRIPTION
**Pull request by hmiyake**
stop_agent should be located below controlDir as discussed in
https://groups.google.com/forum/#!topic/diracgrid-forum/V2tDSO8XH94

### CODE REVIEW

**Comment by atsareg** [comment]
Will include it into v6r13 branch

**Comment by andresailer** [comment]
Please put this in v6r12 as well

**Comment by atsareg** [comment]
Included into the rel-v6r13 branch. Thanks

**Comment by fstagni** [comment]
controlDir is an undefined variablem I don't see how it can work. Also seen via pylint.

**Comment by hmiyake** [comment]
Right, sorry I forgot we declared it as global, and defined it at same place as runitDir.
I have updated my repository. Please take a look.

**Pull request closed without merging**
