### PR TITLE
[v6r12] fix trans150105

### PR DESCRIPTION
**Pull request by phicharp**
This PR should be applied to v6r12 instead of its [v6r11] sister. The changes are the same and the conflicts in TransformationAgent are solved

### CODE REVIEW

**Comment by atsareg** [comment]
Philippe, this is not like that it works, you do not make separate PRs for different release branches with the same fixes. Commits to rel-v6r11 are _ALWAYS_  propagated to rel-v6r12, so no point to make a new PR to rel-v6r12 with the same fixes. No surprises that this PR is in conflict with rel-v6r12 branch after the rel-v6r11 was merged in after your previous "sister" PR was incorporated. 

As for the conflicts in TransformationAgent, I resolved them by taking your latest version of this file from this PR.  I hope this is what you wanted, but please check. 
Most likely this PR as a whole is no more needed but please check on your side.

**Comment by phicharp** [comment]
Hi Andrei,
I know this is not how it usually works… Let me explain what happened:

In order to test the changes as hot fixes, I had to make the changes in the v6r11 branch… Therefore I submitted a PR for v6r11 based on v6r11. However this was not easy to merge on v6r12 due to changes made by Federico and myself creating conflicts. 

This morning at BiLD where you didn’t attend, I proposed to help Federico for making the release by submitting another PR  for v6r12 with the conflicts solved (as I have no clue you or he would have solved these conflicts). I specified in that PR that is was replacing the v6r11 PR. I should have mentioned in a comment on the v6r11 PR that it should NOT be merged to v6r12 but rather use the other PR.

I apologize, but it was not clear to us how you would be able to merge the v6r11 PR in v6r12 and we wanted not to lose another week. git is not smarter for merging than SVN when there are conflicts… 

What we wanted is to have in v6r12 the file that is in the v6r12 PR, correct…

Sorry for the mess, but you were out of the game for a week and we need to proceed…

Cheers, Philippe

Le 13 janv. 2015 à 17:10, Andrei Tsaregorodtsev <notifications@github.com> a écrit :

> Philippe, this is not like that it works, you do not make separate PRs for different release branches with the same fixes. Commits to rel-v6r11 are ALWAYS propagated to rel-v6r12, so no point to make a new PR to rel-v6r12 with the same fixes. No surprises that this PR is in conflict with rel-v6r12 branch after the rel-v6r11 was merged in after your previous "sister" PR was incorporated.
> 
> As for the conflicts in TransformationAgent, I resolved them by taking your latest version of this file from this PR. I hope this is what you wanted, but please check. 
> Most likely this PR as a whole is no more needed but please check on your side.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Dr Philippe Charpentier
J09210, Physics Department, CERN, CH-1211 Genève 23
LHCb Experiment Distributed Computing Coordinator
Office 2-R-007, Tel : +41 22 767 4244 ,  GSM : +41 76 487 0167
mailto:Philippe.Charpentier@cern.ch  http://cern.ch/Philippe.Charpentier

**Comment by atsareg** [comment]
OK. Then please redo this PR against the current state of the rel-v6r12 branch. I think, the easiest would be to make a new branch from rel-v6r12 and copy the affected files from this PR branch. Then make the new PR with the resulting branch.

**Comment by atsareg** [comment]
The PR is dropped as conflicts with rel-v6r11 resolved directly.

Last remark - there is no way to merge something into rel-v6r11 and afterwards not to merge it onwards to rel-v6r12, this is  a strict definition of the procedure.

**Pull request closed without merging**
