### PR TITLE
do not fail when skipping travis format check for non PRs

### PR DESCRIPTION
**Pull request by fstagni**
Just travis fix

### CODE REVIEW

**Comment by chaen** [comment]
That was a useful feature, wasn't it ? Why did you remove it ?

**Comment by fstagni** [comment]
Because it was failing these builds: https://travis-ci.org/DIRACGrid/DIRAC/jobs/617643380 (it's on the branch, not on a PR).

**Comment by chrisburr** [comment]
Should it have become:
```
elif [[ "${CHECK}" == "format" ]]; then
    if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then
        ....
    fi
else
```

**Comment by fstagni** [comment]
yes, I know, but we really need this check? We anyway don't want to expand on Travis usage.

**Pull request merged**
