### PR TITLE
[v6r17] Creating folders without recursion

### PR DESCRIPTION
**Pull request by petricm**
To make the VOMS2CSAgent work in v6r15 do not change recursively the permissions.

chown -R does not work in CLI and times out

This fix is should _not_  be merged into higher versions

### CODE REVIEW

**Comment by fstagni** [comment]
> This fix is should not be merged into higher versions
May you elaborate why?

**Comment by atsareg** [comment]
Technically, it is not possible to not propagate changes to later versions. May be it is easier to hot fix it until you upgrade to a newer version of DIRAC

**Comment by petricm** [comment]
@fstagni it should only be merged into the v6r15 branch since in the newer version (the one LHCb is using) the recursive chown works. 

@atsareg what is the issue with merging this only into one branch? It's not a problem to hot fix it, it's just a notice to v6r15 users.

**Comment by petricm** [comment]
However I don't know if you really need to recursively change permissions and user groups, since when you add a new user, you only add one folder. Is there really a need for recursive in this case?

**Comment by chaen** [comment]
I am surprised, it should eb working on v6r15 already: https://github.com/DIRACGrid/DIRAC/pull/2605

**Comment by petricm** [comment]
With recursive on we get this 
`2017-03-10 14:26:44 UTC Configuration/VOMS2CSAgent/FileCatalog  ERROR: Failed to execute call on master catalog changePathOwner on FileCatalog: Socket read timeout exceeded`
which disappears when you turn off recursive.

**Comment by andresailer** [comment]
I was thinking we could survive with a hotfix, but now I think "chown -R" is broken, and this should be fixed everywhere...
The chown actually goes into a parallel directory and chowns everything there, which is why it takes so long.
E.g.:
I have `/ilc/user/u/usernew` and `/ilc/user/u/userold`.
`chown -R /ilc/user/u/usernew` changes the onwnership of the files in `userold` to `usernew`

Or maybe it would eventually chown everything and it only gets stopped by a timeout...

**Comment by chaen** [comment]
This timeout is for the default handlers, or for the LHCb one ? 

What you have found Andre is worrying...

**Comment by andresailer** [comment]
Default handlers

**Comment by chaen** [comment]
Hum. There is an integration test (https://github.com/DIRACGrid/DIRAC/blob/integration/tests/Integration/DataManagementSystem/Test_Client_DFC.py) which I made for the LHCb handlers, but *in principle*, it should work with the other handlers as well, except the constraints on the security manager :-/ Which one do you use ?

**Comment by andresailer** [comment]
```
SecurityManager = FullSecurityManager
```

**Comment by chaen** [comment]
Bon, in any case, the SecurityManager should not have an impact on the problem, so it should be possible to use this test against your other managers

**Comment by andresailer** [comment]
It seems to be the insert into the FileCatalog that is not working correctly, I get two subfolders with the same LPATH4 ID.
```
mysql> SELECT * FROM FC_DirectoryLevelTree WHERE DirID in (435056, 159679);
+--------+---------------------+--------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+
| DirID  | DirName             | Parent | Level | LPATH1 | LPATH2 | LPATH3 | LPATH4 | LPATH5 | LPATH6 | LPATH7 | LPATH8 | LPATH9 | LPATH10 | LPATH11 | LPATH12 | LPATH13 | LPATH14 | LPATH15 |
+--------+---------------------+--------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+
| 159679 | /ilc/user/k/kXXX1   |  28273 |     4 |      2 |      2 |     11 |      3 |      0 |      0 |      0 |      0 |      0 |       0 |       0 |       0 |       0 |       0 |       0 |
| 435056 | /ilc/user/k/kXXXX2  |  28273 |     4 |      2 |      2 |     11 |      3 |      0 |      0 |      0 |      0 |      0 |       0 |       0 |       0 |       0 |       0 |       0 |
+--------+---------------------+--------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+
```
So the select for the chown is picking up the new and the old folder. (there are other folders, but they all have unique LPATH4)
@atsareg any insights?

**Comment by atsareg** [comment]
This is a real bad sign ;( . Can you
      please give a bit more details how this can be reproduced ?
      
        Cheers,
        Andrei
      
      On 13/03/17 17:30, Andre Sailer wrote:
    
    
      It seems to be the insert into the FileCatalog that is not
        working correctly, I get two subfolders with the same LPATH4 ID.
      mysql> SELECT * FROM FC_DirectoryLevelTree WHERE DirID in (435056, 159679);
+--------+---------------------+--------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+
| DirID  | DirName             | Parent | Level | LPATH1 | LPATH2 | LPATH3 | LPATH4 | LPATH5 | LPATH6 | LPATH7 | LPATH8 | LPATH9 | LPATH10 | LPATH11 | LPATH12 | LPATH13 | LPATH14 | LPATH15 |
+--------+---------------------+--------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+
| 159679 | /ilc/user/k/kXXX1   |  28273 |     4 |      2 |      2 |     11 |      3 |      0 |      0 |      0 |      0 |      0 |       0 |       0 |       0 |       0 |       0 |       0 |
| 435056 | /ilc/user/k/kXXXX2  |  28273 |     4 |      2 |      2 |     11 |      3 |      0 |      0 |      0 |      0 |      0 |       0 |       0 |       0 |       0 |       0 |       0 |
+--------+---------------------+--------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+

      So the select for the chown is picking up the new and the old
        folder. (there are other folders, but they all have unique
        LPATH4)
        @atsareg any insights?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DIRACGrid/DIRAC","title":"DIRACGrid/DIRAC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DIRACGrid/DIRAC"}},"updates":{"snippets":[{"icon":"PERSON","message":"@andresailer in #3281: It seems to be the insert into the FileCatalog that is not working correctly, I get two subfolders with the same LPATH4 ID.\r\n```\r\nmysql\u003e SELECT * FROM FC_DirectoryLevelTree WHERE DirID in (435056, 159679);\r\n+--------+---------------------+--------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+\r\n| DirID  | DirName             | Parent | Level | LPATH1 | LPATH2 | LPATH3 | LPATH4 | LPATH5 | LPATH6 | LPATH7 | LPATH8 | LPATH9 | LPATH10 | LPATH11 | LPATH12 | LPATH13 | LPATH14 | LPATH15 |\r\n+--------+---------------------+--------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+\r\n| 159679 | /ilc/user/k/kXXX1   |  28273 |     4 |      2 |      2 |     11 |      3 |      0 |      0 |      0 |      0 |      0 |       0 |       0 |       0 |       0 |       0 |       0 |\r\n| 435056 | /ilc/user/k/kXXXX2  |  28273 |     4 |      2 |      2 |     11 |      3 |      0 |      0 |      0 |      0 |      0 |       0 |       0 |       0 |       0 |       0 |       0 |\r\n+--------+---------------------+--------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+\r\n```\r\nSo the select for the chown is picking up the new and the old folder. (there are other folders, but they all have unique LPATH4)\r\n@atsareg any insights?"}],"action":{"name":"View Pull Request","url":"https://github.com/DIRACGrid/DIRAC/pull/3281#issuecomment-286162424"}}}

**Comment by andresailer** [comment]
Run the VOMS2CSAgent including MakeHomeDir=True ? Or which part do you want reproduced?

**Comment by andresailer** [comment]
So in the end, we ran into two problems
1) The duplicate LPATH ID for some folders coming from somewhere (makeDir failes to properly update LPATHX?)
2) The recursive chown is _always_ slow. See: #3282

For this specific issue here: 

Why is the recursive operation needed for newly created folders?

**Pull request merged**
