### PR TITLE
[v6r13] DMS fixes 

### PR DESCRIPTION
**Pull request by phicharp**
* Added printout in FTSAgent and FTSJob to allow a better debugging of failing transfers
* Temporary fix for allowing getTransportURL even when the SE is banned for read. This requires a check in SRM2 plugin before calling the service

### CODE REVIEW

**Comment by chaen** [comment]
Review OK, but we shouldn't forget to discuss this changes a bit more in depth :-)

**Comment by chaen** [comment]
Ah wait, you should remove getTransportURL from the readMethod then

**Comment by phicharp** [comment]
I'll do it but it is irrelevant as the check for okMethod is done before! ;-)

**Comment by phicharp** [comment]
These changes are included in the next PR, Close

**Pull request closed without merging**
