### PR TITLE
[v6r14] Exit on EOF for CLIs

### PR DESCRIPTION
**Pull request by sposs**
Don't merge yet, other commits are to come

### CODE REVIEW

**Comment by sposs** [comment]
Ok, #2432 should be satisfied

**Comment by sposs** [comment]
It's now good to merge. is the execfile needed in all CLIs? If yes then someone with more ressources than me should take care of it: ideally, a parent class for all the CLIs should be implemented with the common methods such as do_EOF, do_exit, do_quit, emptyline, execfile, etc.

**Comment by andresailer** [comment]
Thanks!
Once in a while I have to run many commands in certain CLIs. So I agree that these common functions should be implemented once and inherited or mixedin.

**Comment by chaen** [comment]
Thanks ! :-) 
But when is this do_EOF called ? I did not get that part :)

**Comment by sposs** [comment]
The EOF command is a special one, issued when an EOFError is raised.

**Comment by andresailer** [comment]
Also when hitting CTRL+D EOF is send to the shell/CLI

**Comment by fstagni** [comment]
Review OK. Thanks for this.

**Comment by atsareg** [comment]
Sorry for getting late on this. do_execfile already exists in SystemAdministratorClientCLI as well as the EOF treatment. This functionality is relevant indeed to all the CLI's. What I suggest that we make a CLIBase class with these methods included and make all the CLIs inherit from it.

**Comment by andresailer** [comment]
@atsareg there was no do_EOF in the SysAdminCLI until @sposs added it.

**Comment by atsareg** [comment]
Indeed, it was rather in the CSCLI.
      But this way or another, my suggestions still holds.
      
        Andrei
      
      On 03/02/16 14:01, andresailer wrote:
    
    
      @atsareg there was no do_EOF in the
        SysAdminCLI until @sposs
        added it.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by andresailer** [comment]
Yes, and your suggestion was also made by Stephane and agreed to by me and Federico :)

**Comment by fstagni** [comment]
Yes, I also opened an issue for that few hours ago, it's also referenced from this page.

**Comment by atsareg** [comment]
Superseded by #2792

**Pull request closed without merging**
