### PR TITLE
Av150306 v6r13

### PR DESCRIPTION
**Pull request by avedaee**
- fixing issue  #2285 about RSSCache 
- implemented feature request  #1932  about FTSBan/Unban action policies
- implemented getFTSServer() (to guarantee back-compatibility between FTS2 and FTS3 servers)

### CODE REVIEW

**Comment by chaen** [comment]
Hi Aresh,

I don't clearly see how getFTSServer helps in being more generic if you hardcode the 'FTS3' value in the code then :-)

Also it is not clear to me. Is this to ban/unban an FTS server so that we don't use it to transfer, or is it to signal to the FTS server that some SEs are in downtime and it should pause the transfers implying these SEs?

**Comment by chaen** [comment]
And btw, you did the PR against the integration branch, it should be done against v6r13

**Comment by avedaee** [comment]
Hi,
Concerning "getFTSServer": the main purpose was to guarantee back-compatibility and, at the same time, be able to deal with both FTS2 and FTS3 server types.  And I understood this as to mean I should leave getFTS2servers untouched. Then I thought if I had to code a method based on the type of FTS server, maybe it's better to provide a generic method plus some default params.
The issue of (un)banning the FTS server should be handled by DowntimeCommand plus I guess some action policy (I just touched the DowntimeCommand), while the blacklist of sites for the FTS server is handled by an FTS(Un)ban action policy (which I implemented but maybe you expected a method in Resources) 
Concerning the PR, sorry, I'm not sure how I made this mistake, and if you rejected my pull request eventually. In case you did I will wait for making the pull request until we clarified the aforementioned points.

**Comment by chaen** [comment]
Hi,

Indeed, you should leave getFTS2Servers untouched, but if you hard code
FTS3, why not simply calling the method made for FTS3 ?

The banning of the FTS servers should be triggered by a downtime command,
or by a policy related to the gocdb announcement.
The blacklist of SE is to be done via a policy yes. But I as a bit confused
by the name 'FTSBanAction', and also you mention in the comment that it
bans sites, while it should be an SE granularity.

Regarding the PR, I don't have enough karma to reject it, but you can close
it yourself, and redo it against the proper branch

2015-04-08 11:00 GMT+02:00 avedaee <notifications@github.com>:

> Hi,
> Concerning "getFTSServer": the main purpose was to guarantee
> back-compatibility and, at the same time, be able to deal with both FTS2
> and FTS3 server types. And I understood this as to mean I should leave
> getFTS2servers untouched. Then I thought if I had to code a method based on
> the type of FTS server, maybe it's better to provide a generic method plus
> some default params.
> The issue of (un)banning the FTS server should be handled by
> DowntimeCommand plus I guess some action policy (I just touched the
> DowntimeCommand), while the blacklist of sites for the FTS server is
> handled by an FTS(Un)ban action policy (which I implemented but maybe you
> expected a method in Resources)
> Concerning the PR, sorry, I'm not sure how I made this mistake, and if you
> rejected my pull request eventually. In case you did I will wait for making
> the pull request until we clarified the aforementioned points.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIRACGrid/DIRAC/pull/2330#issuecomment-90851731>.
>



-- 
Christophe HAEN
CERN PH-LBC 2/R022
Phone : +41 (0)2 27 67 31 25
Mobile : +41 (0)7 64 87 88 57

**Comment by avedaee** [comment]
Right, I did that in the first place. But then I thought "what is going to happen if also the way we deal with the centralized FTS3 server right now is going to be superseded?". Therefore I thought a generic method would come in handy. But again, if you are not just asking for explanations but actually recommending me to use the method for FTS3 instead, pls let me know and I will do it.
Concerning the FTS server banning I just implemented in DTcommand the piece of code necessary to update the status of the FTSserver on the RSMDB. I thought this would be enough to let Dirac know that the FTS service is down and act accordingly without any explicit banning policy action.
But maybe I'm worng.
Concerning the "FTSBanAction", ok if the name is confusing I will change it : would "FTSStorageBanAction" sound better? If you have other names to suggest pls let me know.

**Comment by chaen** [comment]
Well, I find it a bit useless but okay.
Okay but something has to tell to DIRAC that a given FTS goes in downtime
no ? And this information should also come from GOCDB, the same way it does
with the StorageElements for example.

Thanks for changing the name, it is a bit clearer to me now :-)

2015-04-08 11:53 GMT+02:00 avedaee <notifications@github.com>:

> Closed #2330 <https://github.com/DIRACGrid/DIRAC/pull/2330>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIRACGrid/DIRAC/pull/2330#event-276078476>.
>



-- 
Christophe HAEN
CERN PH-LBC 2/R022
Phone : +41 (0)2 27 67 31 25
Mobile : +41 (0)7 64 87 88 57

**Comment by avedaee** [comment]
Right, in fact it's the DTCommand itself which takes care of fetching the info from GOCDB. Actually the DTCommand retrieves all the current downtimes from the GOCDB then it parses them service by service then updates the RMSDB accordingly.

**Pull request closed without merging**
