### PR TITLE
[v6r12] make successful removeReplica if missing in one catalog

### PR DESCRIPTION
**Pull request by phicharp**
This fix is necessary because LHCb has more than one catalog and some files are only registered in the DFC and not in the LFC (sandboxes).

### CODE REVIEW

**Comment by chaen** [comment]
Reviewed OK

**Comment by chaen** [comment]
re-reviewed ok

**Comment by phicharp** [comment]
Andrei, still something to check with the returned error message... Please don't merge yet

**Comment by atsareg** [comment]
Let me know when it will be ready to merge

**Comment by phicharp** [comment]
It's OK now, please go ahead Andrei

**Pull request merged**
