### PR TITLE
[v6r17] Revisit TaskManager, further fix checksum in ReplicateAndRegister, improve gLogger

### PR DESCRIPTION
**Pull request by phicharp**
* Review the code of TaskManager (in TS) and TaskManagerAgentBase:
   - Standardize the logging information
   - Remove unnecessary code (e.g. take into account the fact that only one transformation is dealt with at a time)
   - Use iterators wherever possible

* Although the checksum was fixed when "False" in the FC, it was overwritten later by _addMetatadataToFiles()

* Check explicitly for "False" in Adler utility and return error (no exception)

* gLogger: test level before processing string (i.e. mostly converting objects to strings)

### CODE REVIEW

**Comment by fstagni** [comment]
Hi Philippe, please have a look at https://travis-ci.org/DIRACGrid/DIRAC/builds/175141369#L1644

**Comment by phicharp** [comment]
Thanks, fixed!
Where can I find the Travis results? They don't appear on the PR page :(

**Comment by fstagni** [comment]
Yes, they do appear (at least for me): they are one of the links at the very end of each PR. Right now it is still failing BTW: https://travis-ci.org/DIRACGrid/DIRAC/builds/175514458#L1652 which probably means you can't use `iteritems()` everywhere.

**Comment by phicharp** [comment]
Right, sorry, I hadn't seen the link... Actually your guess was obviously correct!
Made a fix and wait for travis ;-)

**Comment by phicharp** [comment]
No functionality was changed, just the code was made (hopefully) more readable and maintainable.

**Pull request merged**
