### PR TITLE
[v7r0] Fix JobReport

### PR DESCRIPTION
**Pull request by chrisburr**
BEGINRELEASENOTES

*WorkloadManagement
FIX: Setting both MinorStatus and ApplicationStatus in JobReport at the same time

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
@phicharp can you look into this? Possible conflicts with what has been done recently?

**Comment by atsareg** [comment]
What problem it fixes ? Is it just an elegant way to set defaults in the dictionary without changing the logic of the existing code ?

**Comment by chrisburr** [comment]
> What problem it fixes ? Is it just an elegant way to set defaults in the dictionary without changing the logic of the existing code ?

The problem is if you call:
```python
JobReport(1234).setJobStatus(status='Running', minor='Generation', application='Application started')
```
Only the application status is set as the second for loop overwrites the value of `statusDict[dtime]` (as the time is exactly the same).

**Review by fstagni — APPROVED** [review]

**Comment by phicharp** [comment]
As this would conflict with PR #4852 for v7r1, I have fixed the same issue in that PR. Thus the current PR should only apply to v7r0

**Comment by phicharp** [comment]
Note in passing: this case should never happen as the time stamp for `setJobStatus()` and `setJobApplicationStatus()` is always different because the two methods cannot be called at exactly the same time... This looked always strange to me that there are two distinct methods, and the application status is not one more status, but this is the way it is currently done!

**Comment by chrisburr** [comment]
> this case should never happen as the time stamp for setJobStatus() and setJobApplicationStatus() is always different

`setJobStatus` has an argument for the `application` status so this can trivially happen:

```
def setJobStatus(self, status='', minor='', application='', sendFlag=True):
```

**Comment by phicharp** [comment]
Oups, my apologies! I had missed that one! Stupid me!

**Comment by chrisburr** [comment]
As this is fixed in #4852 and the bug is minor, I'm going to close this

**Pull request closed without merging**
