### PR TITLE
[v7r3] Support running dirac-configure without arguments

### PR DESCRIPTION
**Pull request by chrisburr**
This PR uses `prompt-toolkit` (a dependency of IPython) to improve the CLI interactions. As this inherently interactive I've included videos of how it looks. If this is accepted I'll add `prompt-toolkit` to DIRACOS (it's already there, but I'll make it an explicit dependency).

* 803e53b: Gets rid of the globals used by `dirac-configure`. I could easily rebase this commit out of this PR if desired.

* c12c515: Use `prompt-toolkit` to read the certificate password instead of plain `getpass`. This fixes the long standing bug that pressing `Control + C` while typing your password breaks the prompt. (moved to #5004)

https://user-images.githubusercontent.com/5220533/109291419-40bc3300-7829-11eb-9501-fbbd52175273.mov

* 5687a7a: If `dirac-configure` is ran without any arguments with a Python 3 installation it will suggest setups and CS URLs using the `extension_metadata`. Python 2 based installations are unaffected.

https://user-images.githubusercontent.com/5220533/109291407-3d28ac00-7829-11eb-94aa-da24274708ec.mov

BEGINRELEASENOTES

*Core
FIX: Handle SIGINT correctly when reading certificate passwords
NEW: dirac-configure can now be ran without arguments when using Python 3

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
We are really towards making the releasing of v7r2, and while this is a nice addition it's also a not necessary as of now. I would target v7r3 if you don't mind.

**Comment by chrisburr** [comment]
I'd be tempted to at least target c12c515 for v7r2 as it's a tiny change and fixes a problem that affects me almost every day.

**Comment by fstagni** [comment]
> I'd be tempted to at least target [c12c515](https://github.com/DIRACGrid/DIRAC/commit/c12c515f83c0f750eaff49bc202d1a142923d321) for v7r2 as it's a tiny change and fixes a problem that affects me almost every day.

That requires a release of DIRACOS and DIRACOS2

**Comment by chrisburr** [comment]
> That requires a release of DIRACOS and DIRACOS2

It doesn't, `prompt-toolkit` is already there as a transitive dependency from `ipython`.

**Comment by fstagni** [comment]
> > That requires a release of DIRACOS and DIRACOS2
> 
> It doesn't, `prompt-toolkit` is already there as a transitive dependency from `ipython` (if it wasn't the CI would be failing).
> 
> We shouldn't rely on transitive dependencies for future releases in case it's ever removed but that's only a problem for future releases.

A-ha, good to know. Then go ahead.

**Comment by petricm** [comment]
what about the `<<<` passwords in the CI and similar places?

**Comment by chrisburr** [comment]
> what about the `<<<` passwords in the CI and similar places?

Do you mean when reading from `stdin`? If so there is already a dedicated flag for doing that and disabling this:

https://github.com/DIRACGrid/DIRAC/blob/ebf667824eb9bd3bf289018defa01d838a8ca4b7/src/DIRAC/FrameworkSystem/Client/ProxyUpload.py#L94

**Comment by petricm** [comment]
I mean this `dirac-proxy-init <<< $CERT_PASSPHRASE`

**Comment by petricm** [comment]
There are several places like [this](https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/-/blob/master/.gitlab-ci.yml#L410) around

**Comment by atsareg** [comment]
I do not think you can redirect password from stdin. I do not think it was ever possible, never used it this way.

**Comment by chrisburr** [comment]
> I mean this `dirac-proxy-init <<< $CERT_PASSPHRASE`

Yes it does, albeit with a warning:

```
Generating proxy...
Warning: Input is not a terminal (fd=0).
^[[39;1REnter Certificate password: **********************************
Uploading proxy..
Proxy generated:
```

**Comment by fstagni** [comment]
Some conflicts, please rebase.

**Comment by chrisburr** [comment]
@fstagni Done

**Review by fstagni — APPROVED** [review]

**Pull request merged**
