### PR TITLE
[v6r15] Changed port of ReqProxy to 9161

### PR DESCRIPTION
**Pull request by fstagni**

### CODE REVIEW

**Comment by zmathe** [comment]
REVIEW OK

**Comment by fstagni** [comment]
I ask @iueda to comment if this change would be OK for Belle2. For the same reason, also other VOs should comment

**Comment by iueda** [comment]
If I understand correctly, the change of the port was requested because 9198 is already used by LHCb (and possibly everybody), is that right? It would be nice to know to which service the port 9198 is assigned, so that we can see if we are in the same situation or not.
The port 9161 is currently in use in one of the BelleDIRAC component, but we are on our way reviewing the port assignments and probably can re-assign it to some other port before upgrading to v6r15, probably to 92xx so that we can avoid other possible future conflicts.

**Comment by fstagni** [comment]
@rajanandakumar would you please comment? Thanks

**Comment by andresailer** [comment]
iLCDirac is not using 9161

(we are using 9198 for second instances of the FileCatalog service)

**Comment by rajanandakumar** [comment]
In LHCb, we use port 9198 for DataManagement/RawIntegrity  service. However, I must admit I do not know what the RawIntegrity service is about.

I had originally opened a Jira (CERN) ticket about this issue and Federico's pull request is a response to that ticket. But I also note that it is at some level a low-ish priority issue for now. In the long run though, maybe it is useful for everyone to agree on port mappings to make things uniform across installations?

Regarding Ueda's comment about using a port 92xx, I refer to the following link where we current request only ports 9130-9200 to be open. Maybe some discussion to be had about this also?

http://dirac.readthedocs.io/en/rel-v6r15/AdministratorGuide/InstallingDIRACService/index.html

Cheers,
Raja.

**Comment by zmathe** [comment]
I would say the VOs, which is using DIRAC without an extension then use: 9130-9200 range. The VOs which has an extension use 9201-9400.

**Comment by fstagni** [comment]
I will wait before merging this one yet.

**Comment by chaen** [comment]
Agree with Zoltan on defining something like that. For the RAWIntegrity, this is something which is ran only at the LHCb pit

**Comment by fstagni** [comment]
I have added the suggested range of ports for DIRAC extension in http://dirac.readthedocs.io/en/rel-v6r15/AdministratorGuide/InstallingDIRACService/index.html.

I have also modified the documentation in https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-v6r15, and I will now reply in the google forum thread.

**Pull request merged**
