### PR TITLE
[9.0] remove notification db

### PR DESCRIPTION
**Pull request by fstagni**
This has to be confirmed, but I believe this DB is by now unused.

- [x] update wiki

BEGINRELEASENOTES

*Framework
CHANGE: removed NotificationDN

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
```
SQL [NotificationDB]> show table status;
+--------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
| Name               | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation         | Checksum | Create_options | Comment |
+--------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
| ntf_AlarmFollowers | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2023-09-13 16:11:44 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| ntf_AlarmLog       | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2023-09-13 16:11:44 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| ntf_Alarms         | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        32768 |         0 |              1 | 2023-09-13 16:11:44 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| ntf_AssigneeGroups | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2023-09-13 16:11:44 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| ntf_Notifications  | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |            0 |         0 |              1 | 2023-09-13 16:11:44 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
```

**Comment by fstagni** [comment]
@marianne013 @zhangxiaomei @arrabito @hmiyake Would you make the same check that @andresailer did above? Thanks.

**Comment by arrabito** [comment]
I have similar outputs as @andresailer 
```
mysql> show table status;
+--------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+------------------+-----------+
| Name               | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation         | Checksum | Create_options | Comment | Max_index_length | Temporary |
+--------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+------------------+-----------+
| ntf_AlarmFollowers | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2022-07-12 17:30:40 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |                0 | N         |
| ntf_AlarmLog       | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2022-07-12 17:30:41 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |                0 | N         |
| ntf_Alarms         | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        32768 |         0 |              1 | 2022-07-12 17:30:41 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |                0 | N         |
| ntf_AssigneeGroups | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2022-07-12 17:30:41 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |                0 | N         |
| ntf_Notifications  | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |            0 |         0 |              1 | 2022-07-12 17:30:41 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |                0 | N         |
+--------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+---
```

so it doesn't seem to be used for us too.

**Comment by hmiyake** [comment]
Belle2 also has nothing.
```
mysql> show table status;
+--------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
| Name               | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation         | Checksum | Create_options | Comment |
+--------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
| ntf_AlarmFollowers | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2020-09-08 04:40:29 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| ntf_AlarmLog       | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2020-09-08 04:40:29 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| ntf_Alarms         | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        32768 |         0 |              1 | 2020-09-08 04:40:29 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| ntf_AssigneeGroups | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        16384 |         0 |           NULL | 2020-09-08 04:40:29 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| ntf_Notifications  | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |            0 |         0 |              1 | 2020-09-08 04:40:29 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
+--------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
5 rows in set (0.00 sec)
```

**Comment by sfayer** [comment]
GridPP's notification tables are also all empty.

Regards,
Simon

**Comment by zhangxiaomei** [comment]
IHEP's notification tables are also all empty.

Regards,
Xiaomei

**Pull request merged**
