### PR TITLE
[integration] diracInstall: fix check for using diracos for integration or master

### LINKED ISSUE #4449: [v6r22] dirac-install now defaults to dirac-os
https://github.com/DIRACGrid/DIRAC/blob/a7ff2f501cbf16d7ddb227f8645c59180be30d24/Core/scripts/dirac-install.py#L2643-L2645

Should this be an `and` between and parenthesis around the string type check and the version? Because every version (vXrYpZ) is a string? 

In any case it seems to me that dirac-install now always installs dirac-os even for v6r22

### PR DESCRIPTION
**Pull request by andresailer**
BEGINRELEASENOTES

*Core
FIX: dirac-install: fix check for using diracos for integration or master, fixes #4449 

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
somehow things are stuck with this check, which I don't see where it comes from
```
 check (find tests/CI -name '*.sh' -print0 | xargs -0 -n1 shellcheck --external-source) Expected — Waiting for status to be reported 
```

The one shellcheck check I can find in the basic.yml is not the same
```
 Basic tests / check (find tests/CI -name '*.sh' -print0 | xargs -0 -n1 shellcheck --exclude=SC1090,SC1091 --ext... (pull_request) Successful in 2m 
```

**Comment by fstagni** [comment]
> somehow things are stuck with this check, which I don't see where it comes from
> 
> ```
>  check (find tests/CI -name '*.sh' -print0 | xargs -0 -n1 shellcheck --external-source) Expected — Waiting for status to be reported 
> ```
> 
> The one shellcheck check I can find in the basic.yml is not the same
> 
> ```
>  Basic tests / check (find tests/CI -name '*.sh' -print0 | xargs -0 -n1 shellcheck --exclude=SC1090,SC1091 --ext... (pull_request) Successful in 2m 
> ```

Fixed.

**Comment by andresailer** [comment]
Thanks!

**Comment by andresailer** [comment]
Should we dare to merge this?

**Comment by fstagni** [comment]
et voila!

**Comment by andresailer** [comment]
Thanks again!

**Pull request merged**
