### PR TITLE
[v6r18] Add VMDIRAC doc

### PR DESCRIPTION
**Pull request by arrabito**

### CODE REVIEW

**Comment by fstagni** [comment]
The doc itself looks OK to me, but I am not really an expert of VMDIRAC, so I propose @atsareg as reviewer.

At the same time this page is not linked from any other, so you should add it to https://github.com/DIRACGrid/DIRAC/blob/integration/docs/source/AdministratorGuide/index.rst

**Comment by atsareg** [comment]
This needs also a hook in the main menu to point to this bit of documentation. I will add it while making the release.

**Comment by myco** [comment]
In this instruction I can not find quite important setting. How to set that JobAgent should process more than one job? I tried to change --MaxCycles param in vm-pilot bootstrap script but JobAgents still dying after one job.

**Comment by fstagni** [comment]
I think this is part of the documentation that can be improved during the DUW

**Pull request merged**
