### PR TITLE
[v6r15] Av150901 

### PR DESCRIPTION
**Pull request by avedaee**
- the DTCommand can remove the DT from the Cache once they are removed from the GOCDB (caveat: in order to do that it has to query the GOCDB once more every doNew())
- there is also script to manipulate the Policy Section of the Dirac cfg file, I've tested it and it works, but I'm not sure if infogetter takes into account dirac config setups, if so I may need to revise something.

### CODE REVIEW

**Comment by fstagni** [comment]
the 'releases.cfg file should not be here

**Comment by avedaee** [comment]
Just replaced the modified verision of releases.cfg with the original one from  v6r15

**Comment by fstagni** [comment]
This PR is a bit strange: it contains commits that should not be here, like some done by Andrei and by Sergio. I suggest to start from a clean branch.

**Comment by fstagni** [comment]
Replaced by https://github.com/DIRACGrid/DIRAC/pull/2608

**Pull request closed without merging**
