### PR TITLE
[v6r22] Updates to customize the JobType of user jobs.

### PR DESCRIPTION
**Pull request by hikarihirata**
This PR is updates of JobManifest and JobDescription, and they enable to customize the JobType of user jobs.
I welcome your comments, especially about where the UserJobType parameter should put in CS with you.

BEGINRELEASENOTES
*WMS
CHANGE: Updated to customize the JobType of user jobs in JobDescription and JobManifest
ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
Maybe it makes more sense to get the option from `JobDescription/UserJobTypes`? Instead of `Transformation/UserJobType`:
https://dirac.readthedocs.io/en/latest/AdministratorGuide/Configuration/ConfReference/Operations/JobDescription/index.html
https://dirac.readthedocs.io/en/latest/AdministratorGuide/Configuration/ConfReference/Oper
ations/JobDescription/index.html?highlight=allowedjobtypes#operations-jobdescription-subsection

Actually, according to the description for `JobDescription/AllowedJobTypes` that would already be the parameter to use in the case here?

**Comment by hikarihirata** [comment]
Thank you very much.

@andresailer 
Exactly, JobDescription/AllowedJobTypes is more suitable here, according to the description. 

I have a question about it, @fstagni .
Until DIRAC v6r6, the parameter was used in JobDescription.
Since then, however, it have been not used, and Transformations/DataProcessing have been introduced.
The intent seems to be separating jobs for  production ones and  user ones.
Can I understood correctly?
If so, are there no problem to use JobDescription/AllowedJobTypes here?

**Comment by fstagni** [comment]
`AllowedJobTypes` is not used anywhere at the moment (so, I think, it should be even removed from the documentation, unless you want to use it here instead of what you proposed initially). Both locations are fine to me.

**Comment by atsareg** [comment]
I think that, on the contrary, the Operations/.../JobDescription/AllowedJobTypes should be resurrected. And the list of allowed job types checked in the JobManifest should be extended by AllowedJobTypes. This way a given VO can define JobTypes used in their own workflow system other than the Transformation system.

**Comment by atsareg** [comment]
By the way, the JobDescription class is obsoleted and replaced by JobManifest. So, it can be dropped (to be reverified).

**Comment by atsareg** [comment]
And one more thing. The Operations helper used in the JobManifest should be instantiated with the VO of the owner of the job. This way each VO will be able to define their own job types. This is convenient, for example, the jobs with the COVID19 job types in the EGI were only relevant for one VO but others could also abuse it. This should be corrected.

**Comment by hikarihirata** [comment]
Thank you very much.

I see. I will update to use AllowedJobTypes.
Is it necessary to update the subsection name from JobDescription to JobManifest?

**Comment by atsareg** [comment]
No, JobDescription as the section name is OK

**Comment by hikarihirata** [comment]
> And one more thing. The Operations helper used in the JobManifest should be instantiated with the VO of the owner of the job. This way each VO will be able to define their own job types. This is convenient, for example, the jobs with the COVID19 job types in the EGI were only relevant for one VO but others could also abuse it. This should be corrected.

Do you mean that I should update JobManifest.check as following?
~~~
from DIRAC.ConfigurationSystem.Client.Helpers.Registry import getVOForGroup
....
def check(self):
    userGroup = self.__manifest['OwnerGroup']
    vo = getVOForGroup(userGroup)
    if not vo:
        vo = 'dirac'

    operation = Operations(vo=vo)
    ....
    userJobTypes = operations.getValue(“JobDescription/AllowedJobTypes”, ['User'])
    transformationTypes = operations.getValue("Transformations/DataProcessing", [])
~~~

**Comment by atsareg** [comment]
I think you can simply do:

    operation = Operations(group=self.__manifest['OwnerGroup'])

**Comment by hikarihirata** [comment]
I updated.

**Pull request merged**
