### PR TITLE
[v7r0] Use diracosrc from diracos to set PYTHONPATH and LD_LIBRARYPATH

### PR DESCRIPTION
**Pull request by zmathe**
BEGINRELEASENOTES
*Core
CHANGE: source diracosrc to set PYTHONPATH and LD_LIBRARYPATH
ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Looks fine but please run the jenkins test on this. 

Also, it's maybe only my test, but would you mind squashing some of the commits together?

**Comment by zmathe** [comment]
I never did it, but I will try to reduce the number of commits

**Comment by fstagni** [comment]
There's a conflict, can you please sort it out please?

**Comment by zmathe** [comment]
Something went wrong. I have to recreate this PR

**Pull request closed without merging**
