### PR TITLE
[v7r0] PiloWrapper: fix downloading pilot.json/tar

### PR DESCRIPTION
**Pull request by andresailer**
because the webapp will never not return 404 for the e.g. "cern.ch/pilot.json" URL, we have to move the tarring into the loop of locations.

BEGINRELEASENOTES

*WMS
FIX: PiloWrapper: fix downloading pilot.json/tar

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Please rebase on v7r0.
The reason we didn't see this before is simply because of what you set in the CS for the pilot files location.

**Comment by andresailer** [comment]
Rebased

**Comment by andresailer** [comment]
Opened issue #4483 so this PR can be merged an we don't forget about the checksum checking.

**Comment by andresailer** [comment]
Superseded by #4493

**Pull request closed without merging**
