### PR TITLE
[v6r20] fixing FTS3 server selection strategy

### PR DESCRIPTION
**Pull request by hamzazafar**
FTS3Agent always receives a server chosen using the 'Failover' server policy, even tough the configuration contains 'Random' or 'Sequence' server policy. This issue is caused by the function chooseFTS3Server in FTS3ServerPolicy class, which makes an explicit call to failoverServerPolicy function instead of calling the dynamic policy method! 

BEGINRELEASENOTES
*DMS
FIX: Use correct FTS Server Selection Policy
ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
`failoverServerPolicy` becomes useless like this, am I correct? @chaen should be reviewer of this.

**Comment by hamzazafar** [comment]
'Sequence' and 'Random' server policies become useless otherwise

**Comment by hamzazafar** [comment]
Stumped by another problem with the 'Random' policy, if the random.choice func returns the same server twice or more, then we are wasting out attempts for server selection. Is this scenario considered to be normal? @chaen need your comments!

**Comment by chaen** [comment]
Oups, I probably messed up a merge at some point. 
Thanks for the fix, the code looks ok to me.
But I don't understand your comment about the Random policy ?

**Comment by hamzazafar** [comment]
let's consider the following scenario:
serverlist=['server1', 'server2']
max attempts for selecting a server is 2
if we use the random policy then it might be the case that first 'server1' is selected and RSS returns some error for 'server1', then we make another attempt to select the fts server, what if random.choice function returns the same 'server1' again, in this case we will never try server2 and FTS3Agent wont get any server to submit the job. Have a look at chooseFTS3Server func in FTS3ServerPolicy class

**Comment by chaen** [comment]
Oh right ! I remember now.
All this is due to the fact that this was coded wayyyyyyy before RSS could tell us about FTS servers, so I made it dummy. Feel free to update it !

**Comment by fstagni** [comment]
Is this PR a Work in Progress?

**Comment by hamzazafar** [comment]
It's done from my side now, maybe @chaen can have a look at the latest commit!

**Comment by chaen** [comment]
OK I see what you are trying to do, and your fixes are correct. 
But I see an issue with your implementation but it is my fault, I should have done it differently to start with. We (LHCb) realized that we will need another type of policy, which will serve no one else because extremely specific. So I wanted to transform that into something more plugin based, but you beat me to it. How about we redesign it slightly so that the actual policy are callable and stateful (a class, a closure, a generator, whatever), and we hardcode these 3 policies. But they should all have the same interface (which is not the case in this implementation). the parameter `serverPolicy` then can just be a module name that would be loaded. 
The difference with what exists is very mild. We just need to replace the getattr call with the plugin loading of DIRAC, and rewrite the random policy so that it is stateful. 
What do you think ?

**Comment by hamzazafar** [comment]
To resolve this problem I had to remove the shuffled list argument from randomServerPolicy function, so that it conforms to the argument list of other server policy functions. 

If I choose to make a shuffledList variable in constructor then it causes another problem, all threads in FTS Agent use the same serverPolicy object to get FTS server, if one thread shuffles the list then this change is visible to other threads as well and it could result in non-distinct servers returned by the randomServerPolicy function. 

To tackle this problem I have made use of thread local cache to store shuffled list, hence every thread shuffles its own list  and the randomServerPolicy func also takes a single attempt argument, just like other policy methods (I know that this approach is a bit hacky but it solves the problem!!)

There are issues with writing classes for every server policy or using generators, we can discuss this in the meeting!

**Comment by fstagni** [comment]
All looks OK to me, but @chaen for the final review.

**Comment by chaen** [comment]
It fixes the original issue so I guess review OK, but it does not tackle the problem I mentioned so all this will have to be modified later on anyway.
@hamzazafar the BILD meeting is not really a place for low level implementation discussion. But you are welcome to pass by my office anytime you like to discuss that kind of matter !

**Pull request merged**
