### PR TITLE
[TBD][v7r3] test (CI): use github registry instead of docker

### PR DESCRIPTION
**Pull request by chaen**
Use github registry instead of docker
To be discussed, in the view of the new docker paid policy

BEGINRELEASENOTES
Thank you for writing the text to appear in the release notes. It will show up
exactly as it appears between the two bold lines

Please follow the template:
*Subsystem
NEW/CHANGE/FIX: explanation

For examples look into release.notes

ENDRELEASENOTES

### CODE REVIEW

**Comment by chrisburr** [comment]
I agree with changing the default but I think we should be eligible for the opensource program: https://www.docker.com/community/open-source/application/

**Comment by fstagni** [comment]
Can you check if there's something to be done also for _Pilot_ and _management_ repos?

**Comment by fstagni** [comment]
https://www.docker.com/developers/free-team-faq/

**Comment by fstagni** [comment]
This won't be needed, it seems.

**Pull request closed without merging**
