### PR TITLE
[v6r14] Extended InstalledComponents DB

### PR DESCRIPTION
**Pull request by Sbalbp**
InstalledComponents DB will now store information about the user who did the installation/uninstallation of components.

### CODE REVIEW

**Comment by fstagni** [comment]
Will the extra DB columns be added automatically, or is a human intervention necessary?

**Comment by fstagni** [comment]
At the same time, please update the integration test in TestDIRAC

**Comment by Sbalbp** [comment]
As of now, it is necessary to clean the db and rerun the populating script in order to update the new columns

**Comment by fstagni** [comment]
If this is the case, then the populating script should do the job of cleaning the DB, as this should not be a request for the administrator to do it by hand.

**Comment by atsareg** [comment]
First, there are conflicts with the previous PRs. 
Second, why do you need so complicated way to extract the user from the proxy ? It should be enough to have:

result = getProxyInfo()
if result['OK']:
  user = result['Value']['username']

**Comment by atsareg** [comment]
Is everybody happy with these changes ? To me looks OK more or less. The tabular printout should be rather than with the printTable utility as the main tool for this purpose.

**Comment by fstagni** [comment]
Review OK for me.

**Pull request merged**
