### PR TITLE
[v6r14] Unhashable objects as DAG graph nodes

### PR DESCRIPTION
**Pull request by fstagni**

### CODE REVIEW

**Comment by chaen** [comment]
From the pure code point of view, it seems ok to me (except maybe the name ```checkNode```, which in fact is not only checking). 
But:
* do we really have unhashable types ?
* I agree it is still simple, but it adds complexity, so just in case: still no existing libraries ?

**Comment by sposs** [comment]
https://github.com/thieman/py-dag for example looks very much like the code you wrote, but with a little more...

**Comment by fstagni** [comment]
The use case is exactly about using dictionaries (with lists in!) as nodes. So there's the need for the conversion to hashable types.

@sposs : I have seen that implementation before. Indeed it does few more things (and it's certainly more "precise" than mine, i.e. it checks for real "acyclicity" - is it a word? ), but for example it does not solve the case of unhashable types as nodes, as I have here.

**Comment by sposs** [comment]
There is also this impressive lib http://igraph.org/python/ that I've used in the past... And it allows for arbitrary python objects as node/edge attributes (as long as the pickle can digest them, needed from the dump-to-file).

**Comment by fstagni** [comment]
Nice lib, also very well documented! Thanks, I'll keep an eye on that.

**Comment by fstagni** [comment]
I guess review OK...

**Comment by chaen** [comment]
Yes, but I would really aim at replacing that by igraph for v6r16

**Pull request merged**
