### PR TITLE
[v7r1] Add AccountingMonitor permission

### PR DESCRIPTION
**Pull request by sfayer**
Hi,

This patch adds an AccountingMonitor permission, that's similar to JobMonitor but only allows full access to the accounting data. The use case for this is that we want our accounting to be visible to all users, but JobMonitor is too open (we don't want users to be able to get the sandboxes of other users).

Regards,
Simon

BEGINRELEASENOTES
*Accounting
NEW: Add AccountingMonitor permission
ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
hey Simon. We have somewhat a similar use case where site admins want to have a look at the accounting. For that, we just expose the accounting via `http`. Doesn't that work for you too ?

**Comment by sfayer** [comment]
I'm not sure that exposing the accounting as http would really work for us (although I don't think I fully understand exactly what that would involve): We used to give everyone the JobMonitor permission until we found the sandbox access issue, so our  users are quite used to just being able to generate plots via the web interface. (We also have a general policy of not hosting any new http services as part of a security improvement plan).

The exact use case that initially triggered this was that we have an end-user in the "vo_user" and "vo_production" groups and they want to generate plots including both of those groups at the same time for a general overview, which doesn't seem possible any other way.

**Comment by fstagni** [comment]
I think what you describe here is a pretty common use case. I am wondering if we should just expose Accounting data freely, to all registered users.

@chaen our case is actually for giving access to users that are not part of any VO (for our case, not part of LHCb). This is not exactly what's described here, IIUC.

**Comment by sfayer** [comment]
We've also noticed that there is a check for these permissions in the WebApp that would need patching too:
https://github.com/DIRACGrid/WebAppDIRAC/blob/integration/src/WebAppDIRAC/WebApp/static/core/js/utils/PlotView.js#L808

**Review by fstagni — APPROVED** [review]

**Review by atsareg — APPROVED** [review]

**Pull request merged**
