### PR TITLE
[v6r18] Correct documentation for PluginName

### PR DESCRIPTION
**Pull request by chaen**
Replace ProtocolName with PluginName

### CODE REVIEW

**Comment by atsareg** [comment]
Formatting of the new line as a table row looks to be wrong

**Comment by phicharp** [comment]
This "language" for producing documentation is just a pain in the neck! In particular for the tables...
Otherwise this online "editor" is helpful:
https://livesphinx.herokuapp.com

**Comment by chaen** [comment]
oups sorry I only see the comment now !

**Comment by atsareg** [comment]
Do not worry, I corrected it by hand after the merging

**Pull request merged**
