### PR TITLE
[rel-v7r1] Source bashrc in wrapper script

### PR DESCRIPTION
**Pull request by chrisburr**
BEGINRELEASENOTES

*Core
CHANGE: Source bashrc in wrapper script

ENDRELEASENOTES

As mentioned in #4480

### CODE REVIEW

**Comment by atsareg** [comment]
Integration test segfaulted in the Test_DIRACCAProxyProvider. This was not the case before and is not likely to be provoked by this PR. Merging ?

**Comment by chaen** [comment]
I would not. Sourcing the bashrc means different environment, and if there are conflicts, it could result in segfault. So I would not ignore the tests

**Comment by atsareg** [comment]
An integration test failed again but now this is another integration test. The one failing before is OK now. Merging ?

**Comment by atsareg** [comment]
After four attempts the test is finally green !

**Pull request merged**
