### PR TITLE
[WIP] [v6r20] FTS3 details are dict not obj

### PR DESCRIPTION
**Pull request by marianne013**
BEGINRELEASENOTES
*RequestManagementSystem
FIX: typo in code breaks dirac-rms-request for FTS3 requests.

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
They are objects. Not sure why you see this behaviour, it works fine for me
Attaching with a debugger:
```
ipdb> p fts3Op
<DIRAC.DataManagementSystem.Client.FTS3Operation.FTS3TransferOperation object at 
ipdb> fts3Op.ftsJobs
[<DIRAC.DataManagementSystem.Client.FTS3Job.FTS3Job object at 0x7f363ef8ce10>]
0x7f363cc0cb50>
```

See the output

```
DIRAC-PROD>dirac-rms-request 17185735
Request name='00073495_00037600' ID=17185735 Status='Done'
Created 2018-08-17 14:09:53, Updated 2018-08-17 14:34:49, NotBefore 2018-08-17 14:33:56

[...]

FTS3 jobs associated: 
743a16aa-a227-11e8-b9ed-02163e018d65@https://fts3.cern.ch:8446 (Finished)
```

To me it looks like the unmarshalling is not done. Is the client version you use up to date ?

**Comment by marianne013** [comment]
I'm using v6r20p9 all the way through (+ lcgBundle v14r1) Without this fix I see:

lx02:2018_Aug_17_1147_gridpp_EL7 > dirac-rms-request ddrarr_1534503088
Request name='ddrarr_1534503088' ID=227692 Status='Done'
Created 2018-08-17 10:51:34, Updated 2018-08-17 11:09:24, NotBefore 2018-08-17 11:08:34
Owner: '/C=UK/O=eScience/OU=Imperial/L=Physics/CN=daniela bauer', Group: gridpp_user
  [0] Operation Type='RegisterReplica' ID=198560 Order=0 Status='Done'
      TargetSE: UKI-LT2-QMUL2-disk - Created 2018-08-17 11:01:18, Updated 2018-08-17 11:09:24
    [01] ID=9142 LFN='/gridpp/user/daniela.bauer/repregtest.1534503088.txt' Status='Done' Checksum='1cd4d4d5' Attempts=2
  [1] Operation Type='ReplicateAndRegister' ID=198559 Order=1 Status='Done'
      TargetSE: UKI-LT2-QMUL2-disk - Created 2018-08-17 10:51:35, Updated 2018-08-17 11:01:18
    [01] ID=9141 LFN='/gridpp/user/daniela.bauer/repregtest.1534503088.txt' Status='Done' Checksum='1cd4d4d5'
exception in FTS3JSONDecoder No module named M2Crypto for type FTS3Job
exception in FTS3JSONDecoder No module named sqlalchemy for type FTS3TransferOperation
[I stuck a print statement in here]
{u'username': u'daniela.bauer', u'lastUpdate': u'2018-08-17 11:01:18', '__module__': u'DIRAC.DataManagementSystem.Client.FTS3Operation', u'rmsReqID': 227692, u'ftsFiles': [<DIRAC.DataManagementSystem.Client.FTS3File.FTS3File object at 0x7fba82370890>], u'creationTime': u'2018-08-17 10:52:25', u'error': None, '__type__': u'FTS3TransferOperation', u'ftsJobs': [{u'status': u'Finished', u'lastUpdate': u'2018-08-17 11:01:18', '__module__': u'DIRAC.DataManagementSystem.Client.FTS3Job', u'completeness': 100.0, u'ftsGUID': u'c00e8c94-a20b-11e8-b4a4-525400e091e6', u'error': None, '__type__': u'FTS3Job', u'jobID': 1, u'username': u'daniela.bauer', u'submitTime': u'2018-08-17 10:53:18', u'userGroup': u'gridpp_user', u'ftsServer': u'https://fts00.grid.hep.ph.ic.ac.uk:8446', u'operationID': 1, '__datetime__': [u'submitTime', u'lastUpdate']}], u'sourceSEs': None, u'priority': None, u'status': u'Finished', '__datetime__': [u'creationTime', u'lastUpdate'], u'rmsOpID': 198559, u'userGroup': u'gridpp_user', u'activity': None, u'operationID': 1}
Traceback (most recent call last):
  File "/home/hep/dbauer/check_dirac/2018_Aug_17_1147_gridpp_EL7/DIRAC/RequestManagementSystem/scripts/dirac-rms-request.py", line 265, in <module>
    printRequest(request, status=dbStatus, full=full, verbose=verbose, terse=terse)
  File "/home/hep/dbauer/check_dirac/2018_Aug_17_1147_gridpp_EL7/DIRAC/RequestManagementSystem/Client/ReqClient.py", line 531, in printRequest
    printFTSJobs(request)
  File "/home/hep/dbauer/check_dirac/2018_Aug_17_1147_gridpp_EL7/DIRAC/RequestManagementSystem/Client/ReqClient.py", line 482, in printFTSJobs
    job.status) for job in associatedFTS3Jobs))
  File "/home/hep/dbauer/check_dirac/2018_Aug_17_1147_gridpp_EL7/DIRAC/RequestManagementSystem/Client/ReqClient.py", line 482, in <genexpr>
    job.status) for job in associatedFTS3Jobs))
AttributeError: 'dict' object has no attribute 'ftsGUID'

**Comment by chaen** [comment]
That's super strange
```
exception in FTS3JSONDecoder No module named M2Crypto for type FTS3Job
exception in FTS3JSONDecoder No module named sqlalchemy for type FTS3TransferOperation
```

**Comment by marianne013** [comment]
The exceptions don't actually do anything though.
If I put the fix in, the same command ends with:
FTS3 jobs associated: 
c00e8c94-a20b-11e8-b4a4-525400e091e6@https://fts00.grid.hep.ph.ic.ac.uk:8446 (Finished)
while still showing the exceptions.

**Comment by chaen** [comment]
Yes it makes sense. The unmarshaling does not take place (that's what the exceptions say) so you get a dictionary instead of the objects. So we should rather fix the exception. Let me guess: CC7 ?

**Comment by fstagni** [comment]
BTW: the "correct" lcgBundle is v14r2, not v14r1.

**Comment by marianne013** [comment]
I think we dismissed v14r2 due to this comment:
https://github.com/DIRACGrid/DIRAC/issues/3614#issuecomment-407371023
@chaen Yes, it's CentOS7, but so far we've always run the DIRAC UIs of CentOS 7 and never seen a problem.

**Comment by chaen** [comment]
But v14r1 is the same with respect to this issue no ?
yes but I believe we advertised that the bundle does not work on Centos7 because of this conflict with fts3 at the level of M2Crypto. The `sqlalchemy` issue is new though, this should be in the externals

**Comment by fstagni** [comment]
So, now I am a bit lost: what to do with this PR?

**Comment by marianne013** [comment]
Ignore it until we've found a proper solution to this problem.

**Comment by chaen** [comment]
Yeah... I tried to avoid it as much as I could. But here I could not :-( The reason for having it on the client is because that's the only way (I found..) to have polymorphism in the DB. 
At some points, I thought of doing something like importing the decorator I need, and if it fails, I just redefine it as a dummy decorator. But I thought this is too much of a hack, and might hide real issues... 
But be reassured, there is no sqlalchemy being used on the client side. 

If there's a better way of doing that Simon knows, I'm happy to learn :)

**Comment by sfayer** [comment]
The problem we have is that the serialiser fails to create the FTS3JSONDecoder due to the sqlalchemy import in FTS3Operation... The client externals bundle doesn't have sqlalchemy, but the exception is caught  somewhere (no instant crash) so then when the operation is deserialised you get the raw dict, whereas with the server bundle you get a proper object. There is a similar problem with M2Crypto sneaking in there somewhere too (although I couldn't find exactly where)...

I don't have a neat solution for this at the moment, but perhaps not catching the import error when preparing the serialiser would be a start? At least then it would stop on a hard error rather than just giving (pseudo-)unpredictable behaviour?

Maybe the fix is to include the missing libraries in the client bundle (maybe DIRACOS is heading that way anyway)? How different are the client and server bundles now-a-days?

Regards,
Simon

**Comment by chaen** [comment]
Yes, you got it perfectly. 
For M2Crypto, the issue is tricky because fts3 ships M2Crypto internally, and I believe this is what is screwing things up. 

As for not catching the exception, it is a bit tricky because it is a normal behaviour to have exceptions: that's how the correct serializer/deserialzer is finally picked up. But I have to look more carefully at the doc, maybe I should be more strict on what I catch. But I agree that the error reporting her is clearly not optimal...

There's a single DIRACOS for client and server. And to be honest, I hope to keep it this way. The bundles are the same for client & server, but I would not know for client. Maybe @atsareg

**Comment by marianne013** [comment]
Hi Andrei. could you look this please ? This is currently stopping up from upgrading beyond v6r20p9 ?

**Comment by fstagni** [comment]
Closing after discussion in BiLD today.

**Pull request closed without merging**
