### PR TITLE
[v6r22] SingularityCE: Tidy up workdir at end of job

### LINKED ISSUE #4296: Singularity CE: Containers of completed jobs should be deleted
When setting FillingModeFlag=True to run multiple jobs per pilot in succession, the container root directories for completed jobs stay behind, potentially using too much disk space.

### PR DESCRIPTION
**Pull request by sfayer**
Hi,

This is a fix for SingularityCE to tidy up the workdir at the end of the job.

Fixes #4296.

Regards,
Simon

BEGINRELEASENOTES
*Resources
CHANGE: SingularityCE: Delete workDir at end of job by default.
FIX: SingularityCE: Always stop proxy renewal thread at end of job.
ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
There is a similar flag in the JobWrapper calle "CleanUp", maybe use the same name?
https://github.com/DIRACGrid/DIRAC/blob/integration/WorkloadManagementSystem/JobWrapper/JobWrapper.py#L116

(I also have no idea how or if at all the JobWrapper is involved when SingularityCE is used.)

**Comment by sfayer** [comment]
Hmm, I could use the same name, but then I'd be a bit worried about having two options that actually do subtly different things floating around in roughly the same places: It'd be very easy for someone to muddle them up and not get the behaviour they expect. Does anyone else have an opinion on this?

**Comment by atsareg** [comment]
I think this is OK to have a separate flag on the CE configuration for preventing clean up of the working directories. But I have another question. In the current implementation there is a dirac client installation for each job executed by the job agent. Is it possible to keep the working directory instead of deleting and recreating it for each job ? The job application directory is anyway cleaned up by the job wrapper, so these directories will not be accumulated.

Yet another question. In the current implementation a standard SLC6 CVM3 container is used. I think we should consider building a special container for pilots with the DIRAC client already installed in it and available from cvmfs. This would avoid a lot of overhead for each job of creating working directories.

**Comment by sfayer** [comment]
I think keeping the working directory around possibly opens a security hole: The DIRAC stuff installed in the working dir is owned by the same user in the container: If the containers are kept, a malicious user could potentially modify the scripts that would then be used for the next job. There may be a way to split the permissions, or make the base bit read-only but it would have to be tested quite carefully. In the long run, we're probably going to have to support user specified containers (at least two of the GridPP communities are already starting to request something like that), which means you'd need to keep track of which base image is already installed and possibly switch, which is more complexity. I have an alternate suggestion (make the containers far more lightweight so installing them each time isn't a problem), which is also the answer to your next question:

Yes, the CVM3 container is the default, although we actually use CVM4 on our cloud. I'd worry about the developmental overhead for maintaining (multiple) container images (not to mention the complexity of then getting VO specific addons etc installed). We could instead make the install step much faster by pre-unpacking things on CVMFS:
 - As part of the normal release process for DIRAC & DIRACOS, unpack the full release bundle into a directory on CVMFS (so that all versions are available there).
 - Modify dirac-install to symlink those CVMFS directories as the DIRAC and diracos directories (if they're available) into the install environment[*].
 - Potentially skip the benchmarking step: We could probably pass the host benchmark through to the container and skip running dirac-wms-cpu-normalization for each job.

As a bonus, the symlink install method would probably speed up start-up on standard grid WNs quite a bit too (we've found it takes about ~1-2 mins to unpack DIRACOS, whereas a symlink would be almost instant).

[*] So the DIRAC dir would look something like the following. The scripts and bashrc dirs would still be made locally (so the scripts dir could contain extension module scripts as well):
bashrc
DIRAC -> /cvmfs/dirac.egi.eu/releases/DIRAC/v7r0p2
SomeExtensionDIRAC
diracos -> /cvmfs/dirac.egi.eu/releases/diracos/v4r1
scripts

**Comment by atsareg** [comment]
The discussion in this PR should certainly continue. Merging this one now to fix the immediate issue

**Pull request merged**
