### PR TITLE
[8.0] refactor: removing the possibility to get the optimizers to run with a vo plugin

### PR DESCRIPTION
**Pull request by simon-mazenoux**
BEGINRELEASENOTES

*WMS
CHANGE: removing the possibility to get the optimizers to run with a vo plugin

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
@andresailer @marianne013 @atsareg @hmiyake @zhangxiaomei this PR is in draft mode only because it needs the approval from (all) the extensions that this is not going to harm you. 
Final approval can be done at the next BiLD (on June 30th).

**Review by andresailer — APPROVED** [review]
I am not even sure I was aware one could have vo-plugins in executors?

**Comment by marianne013** [comment]
Fine by GridPP.

**Comment by zhangxiaomei** [comment]
Fine with IHEP. We don't have plugins in exectutors.

**Comment by atsareg** [comment]
We had some example in the past, not now. What is the intention - just simplify the code or this feature was blocking something really ? So, does it harm ?

**Comment by simon-mazenoux** [comment]
I want to move this code before inserting the job into the database, and this VO plugin requires a jobID. Also, there is already two different ways you can modify the jobPath: via the config file or via the job API (https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/-/blob/master/src/LHCbDIRAC/Interfaces/API/LHCbJob.py).

**Comment by hmiyake** [comment]
We are using extension in optimizer (Scout), not using VOPlugin but directly adding to JobPath.
I expect the latter feature is kept after this PR is merged...

**Comment by simon-mazenoux** [comment]
Yes it will, I just want to remove the possibility to resolve the JobPath if not set in the job description with a VO plugin because I think there are better ways to resolve the JobPath.

**Pull request merged**
