### PR TITLE
[v6r20] native XROOT storage deprecated

### PR DESCRIPTION
**Pull request by chaen**
BEGINRELEASENOTES

*Resources
CHANGE: Add the deprecated decorator to native XROOT plugin

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Now the pycodestyle report is correct.

**Comment by chaen** [comment]
yeah, somehow travis does not change it's base branch if you change it on github after creating the PR

**Comment by chaen** [comment]
:D :D :D 
What the hell ! It first says there is too many white line, i remove one, and now it complains that there is not enough :D 
I hate that type of debugging :D

**Comment by chaen** [comment]
For my debugging:

Commit https://github.com/DIRACGrid/DIRAC/pull/3745/commits/ae5b78370adc354c12adf1d9e4f32653b7e7b1f1 leads to `./Resources/Storage/XROOTStorage.py:835:3: E303 too many blank lines (2)`

**Comment by chaen** [comment]
Added one commit to remove the blank line. Locally, the error is gone:

```
[chaen@pclhcb31 DIRAC]$ pycodestyle Resources/Storage/XROOTStorage.py | grep E303
[chaen@pclhcb31 DIRAC]$ 
```
let see

**Comment by fstagni** [comment]
```./Resources/Storage/XROOTStorage.py:834:3: E301 expected 1 blank line, found 0```

:)))

**Comment by chaen** [comment]
Youhou, victory ! :)

**Pull request merged**
