### PR TITLE
[v6r20] Generic to VO DIRAC installation in singularity

### PR DESCRIPTION
**Pull request by xianghuzhao**
When we try to test singularity CE, we could not pass the installation step from inner container. Because we are using BES installation and the versions are set multiply like "v0r17, v6r20pre14".

The original codes can only deal with pure DIRAC installation and single version. For our case it will try to execute "`./dirac-install.py -r v0r17,v6r20-pre14 -i 27 -e BES`", which will fail soon.

After this modification, it will execute "`./dirac-install.py -V BES -r v0r17 -i 27 -e BES`" and works properly.

BEGINRELEASENOTES

*WMS

FIX: SingularityComputingElement: Install DIRAC from inner singularity does not work correctly for generic VO installation

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
@sfayer Is this patch OK for you?

**Comment by fstagni** [comment]
For solving the pycodestyle report in travis, run:
```
autopep8 --global-config=setup.cfg --in-place  Resources/Computing/SingularityComputingElement.py
```

**Comment by sfayer** [comment]
Yes, the patch looks fine to me...

**Comment by fstagni** [comment]
OK, so please @xianghuzhao simply fix the pycodestyle as written above and then it could be merged.

**Comment by xianghuzhao** [comment]
The pycodestyle is fixed now. It seems that the whole file is converted with the autopep8 command.
Please check if any more problems exist.

**Comment by fstagni** [comment]
Yes, it's fine.

**Pull request merged**
