### PR TITLE
[v6r13] dirac-dms-get-file broken

### PR DESCRIPTION
**Pull request by atsareg**
FIX: getFile() allows to pass a list of LFNs

### CODE REVIEW

**Comment by chaen** [comment]
Review OK

**Comment by phicharp** [comment]
I have been checking that script and my test was successful (with a single file)...  I was trying to replicate the former behavior and probably at the time I thought it was not allowed to use the API getFile() with a list of LFNs. It is true however that now the script and the API were incompatible (as probably I also added this possibility in the script or removed a loop that was therein. 
Apologies for this inconsistency that you simple change fixes indeed!

**Comment by phicharp** [comment]
Andrei: probably a mistake but the PR is for Integration, not v6r13 ;-)

**Comment by atsareg** [comment]
Wrong target branch

**Pull request closed without merging**
