### PR TITLE
[Integration] feat: adding a prefix parameter to the logger

### PR DESCRIPTION
**Pull request by simon-mazenoux**
BEGINRELEASENOTES

*FrameworkSystem
NEW: add the possibility to add a prefix before the actual log message for a given subLogger

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
not sure what you are trying to do, but there is already a prefix feature 

```
In [4]: gLogger.info("toto")
2022-05-31 13:10:36 UTC Framework INFO: toto
Out[4]: True

In [5]: gLogger.getSubLogger("sub").info("tata")
2022-05-31 13:10:53 UTC Framework/sub INFO: tata
```

More over the logger is already complex enough, and we are more in the process of simplifying it, rather than adding features to it. 
Can you explain what you are trying to achieve ?

**Comment by simon-mazenoux** [comment]
> not sure what you are trying to do, but there is already a prefix feature
> 
> ```
> In [4]: gLogger.info("toto")
> 2022-05-31 13:10:36 UTC Framework INFO: toto
> Out[4]: True
> 
> In [5]: gLogger.getSubLogger("sub").info("tata")
> 2022-05-31 13:10:53 UTC Framework/sub INFO: tata
> ```
> 
> More over the logger is already complex enough, and we are more in the process of simplifying it, rather than adding features to it. Can you explain what you are trying to achieve ?

I'm trying to reproduce what the JobLog is doing, meaning :
```
self.jobLog.info("tata")
2022-05-31 13:10:53 UTC OptimizerName INFO: [JID 1234] tata
```

**Comment by chaen** [comment]
I'd rather adapt the log and have

```
2022-05-31 13:10:53 UTC OptimizerName/JID_1234/ INFO: tata
```

instead of increased complexity in the logger

**Comment by chaen** [comment]
It is a simple change that has zero test coverage, that needs to work with subloggers, local subloggers, etc etc, for zero gain. The name of the sublogger does exactly what you want. It just prints `/jobid/` instead of `[jobid]` (the first one being much easier to parse in bash btw)
No wonder DIRAC is such a hellish software if we keep adding code for redundant features.

**Review by fstagni — APPROVED** [review]

**Pull request closed without merging**
