### PR TITLE
[v6r13] Use SHA1 signature encryption everywhere

### PR DESCRIPTION
**Pull request by atsareg**
CHANGE: X509Chain - use SHA1 signature encryption when generating proxy by Proxy Manager

### CODE REVIEW

**Comment by chaen** [comment]
are you sure that this works everywhere ?

**Comment by atsareg** [comment]
It certainly better than the mixture of md5 and sha1 that we had before

**Comment by chaen** [comment]
Yes but I am sorry but doing this in a patch release, without discussing it, without explaining it, without letting any one know (13 minutes between the commit and the merge).... I totally agree that having this mixture is certainly not ideal, but at least we knew it was working

**Comment by atsareg** [comment]
It was not working for at least one crucial case, that's why was put in rather urgently. I have tested in several cases in the France-Grilles installation without seeing problems.

**Pull request merged**
