### PR TITLE
[8.0] Update dirac_cert_convert.py;  Add guidance error message for user if unsupported crypto

### PR DESCRIPTION
**Pull request by mdpunch**
Tell user to try "--legacy" option if the pcks12 file has old crypto (addition or replacement for my previous pull request).
    
Also, corrected trailing white-space, long lines, and other clean-ups after pylint.

### CODE REVIEW

**Comment by fstagni** [comment]
You are still targeting integration: in #7420 I have cherry-picked your commit on top of rel-v8r0 branch (and fixed the syntax)

**Comment by mdpunch** [comment]
> You are still targeting integration: in #7420 I have cherry-picked your commit on top of rel-v8r0 branch (and fixed the syntax)

Okay, thanks.  Sorry about that.

**Comment by mdpunch** [comment]
Sorry, I'm a bit lost... should I do something here?

**Comment by fstagni** [comment]
Nope, I just close this! Your changes are in the other PR.

**Pull request closed without merging**
