### PR TITLE
[v6r13] Metaquery enhancement and command

### LINKED ISSUE #1793: DIRAC.GetFile with wildcard
(from Alexander Richards)

Exposed in the API is the 'getFile' method of API.Dirac. This it seams does work for a list of files but not for a wildcard. I note also that you have a method 'getFilesFromDirectory' in DataManagementSystem/Client/ReplicaManager.py.. This it seems is capable of accepting a wildcard. Would it be possible to have this exposed in the API or the getFile method to include wildcards?

### PR DESCRIPTION
**Pull request by atsareg**
CHANGE: FileMetadata - allow single character wild cards, close #1793
NEW: dirac-dms-find-lfns command

### CODE REVIEW

**Comment by phicharp** [comment]
OK, but we should have a policy for scripts that are not generic... dirac-dms-find-lfns is only for VOs using the DFC and AFAIU using user metadata. 
Shouldn't we use a different name, e.g. dirac-dfc-find-lfns? Otherwise users will see these scripts and eventually try and use them... A workaround for LHCb would be to overwrite it with dirac-bookkeeping-get-files, but this is not really clean, is it?

**Comment by atsareg** [comment]
This is not only for user metadata but standard metadata as well. It is analogue to a unix find command + possibility to specify user metadata. This is true that for LFC this will not work but we are moving away from LFC anyway. For LHCb there should be certainly a specific command which should not overwrite this one and use Bookkeeping. 
With this command the dirac-dms-user-lfns, for example, can be replaced by something like:
dirac-dms-find-files "User=atsareg" "CreationDate>2015-05-15" "FileName=*.root" > output.txt
So, here no user metadata is used. Almost any file metadata can be used including SE to get files having replicas in a given SE.

**Comment by phicharp** [comment]
dirac-dms-user-lfns is indeed superseded by dirac-dms-list-directory (currently only in LHCbDIRAC admittedly, but I need to port a lot of scripts to DIRAC), but I fully agree with the new functionality that would provide more functionality. This is not the problem I was pointing to: I was referring to the fact that in principle dirac-dms-xxx commands should work for any file catalog, not only the DFC. I agree it is a bit theoretical but also a matter of principle...

**Comment by atsareg** [comment]
Well. let's discuss it next week. I think that the commands that can not be performed with some catalog must revert to the use of another catalog if several catalogs are used in parallel ( the case of LHCb ) or fail with a clear statement that it is not supported by the configured catalogs and thus invite to consider the use of DFC. 
By the way, you should try out the COMDIRAC extension. There you will find a nice 'dls' command which I think is equivalent of dirac-dms-list-directory. It has also dfind command which is equivalent of the dirac-dms-find-files.

**Pull request merged**
