### PR TITLE
[v7r2] fix: always removing the flag for skipping the CA checks

### PR DESCRIPTION
**Pull request by fstagni**
BEGINRELEASENOTES

*Core
FIX: unless explicitly set, do not skip the CA checks

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
> No, we should not ignore the config just like this.
> I think it would be best to explicitly pass the option when we really need it the first time, instead of setting it in the config.

That would mean remove these lines?

https://github.com/DIRACGrid/DIRAC/blob/88f47ec9f7bac5256fb174907bb54384e282659c/src/DIRAC/Core/scripts/dirac_configure.py#L408-L409

**Comment by chaen** [comment]
yes, and explicit when using the `BundleDeliveryClient` a bit lower

**Comment by fstagni** [comment]
Now the integration test fails with 

```
*** Mon Sep 20 14:34:57 UTC 2021  Getting a non privileged user

2021-09-20 14:34:57 UTC Framework [140580330772288] DEBUG: dirac.cfg should be at /home/dirac/ClientInstallDIR/etc/dirac.cfg
2021-09-20 14:34:57 UTC Framework [140580330772288] DEBUG: CFG merged
2021-09-20 14:34:57 UTC Framework [140580330772288] DEBUG: Updating configuration internals
2021-09-20 14:34:57 UTC Framework [140580330772288] DEBUG: Updating configuration internals
Parsing command line
Trying to load Resources.LogBackends.StdoutBackend
Trying to load DIRAC.Resources.LogBackends.StdoutBackend
2021-09-20 14:34:57 UTC dirac_proxy_init [140580330772288] DEBUG: Updating configuration internals
2021-09-20 14:34:57 UTC dirac_proxy_init [140580330772288] NOTICE: Generating proxy...
2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] NOTICE: 
Your certificate will expire in 6 days. Please renew it!

2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] INFO: Contacting CS...
2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] DEBUG: Refreshing configuration...
2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] DEBUG: Refreshing from list ['dips://server:9135/Configuration/Server']
2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] DEBUG: Randomized server list is dips://server:9135/Configuration/Server
2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] DEBUG:  Trying to refresh from dips://server:9135/Configuration/Server
2021-09-20 14:34:58 UTC dirac_proxy_init/DIRAC.Core.Tornado.Client.ClientSelector [140580330772288] DEBUG: Trying to autodetect client for dips://server:9135/Configuration/Server
2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] DEBUG: Already given a valid url dips://server:9135/Configuration/Server
2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] DEBUG: Trying to connect to: dips://server:9135/Configuration/Server
2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] ERROR: 
Traceback (most recent call last):
  File "/home/dirac/ClientInstallDIR/DIRAC/Core/DISET/private/BaseClient.py", line 472, in _connect
    retVal = transport.initAsClient()
  File "/home/dirac/ClientInstallDIR/DIRAC/Core/DISET/private/Transports/M2SSLTransport.py", line 147, in initAsClient
    self.oSocket.connect((host, port))
  File "/home/dirac/ClientInstallDIR/diracos/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 327, in connect
    ret = self.connect_ssl()
  File "/home/dirac/ClientInstallDIR/diracos/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 313, in connect_ssl
    return m2.ssl_connect(self.ssl, self._timeout)
SSLError: certificate verify failed
2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] WARN: Can't update from server Error while updating from dips://server:9135/Configuration/Server: Can't connect to dips://server:9135/Configuration/Server: SSLError('certificate verify failed',)
2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] WARN: Reason(s):
	Can't connect to dips://server:9135/Configuration/Server: SSLError('certificate verify failed',)
2021-09-20 14:34:58 UTC dirac_proxy_init [140580330772288] ERROR: Can't contact DIRAC CS: Reason(s):
	Can't connect to dips://server:9135/Configuration/Server: SSLError('certificate verify failed',)
```

This is at the beginning of the client tests, and it's triggered by this line: 

https://github.com/DIRACGrid/DIRAC/blob/f0b15d7a203beeff5ab95aedf058d2fa1122d7c7/tests/Integration/all_integration_client_tests.sh#L16

Suggestions?

**Comment by chaen** [comment]
Maybe the CA is not properly configured for the integration tests. I'll give it a look

**Comment by chaen** [comment]
OK fixed. The problem was that the symlink that was copied over (first in the `integration_tests.py`, but also by the BundleClient) was an absolute symlink, so pointing to a non existing location on the client side

**Comment by fstagni** [comment]
> OK fixed. The problem was that the symlink that was copied over (first in the `integration_tests.py`, but also by the BundleClient) was an absolute symlink, so pointing to a non existing location on the client side

Great, thanks! 

PR content is fine for you now?

**Review by chaen — APPROVED** [review]

**Pull request merged**
