### PR TITLE
[v7r0] Add extraOptions only when the executable is a DIRAC script

### PR DESCRIPTION
**Pull request by fstagni**
BEGINRELEASENOTES

*WMS
CHANGE: JobWrapper: Add extraOptions only when the executable is a DIRAC script

ENDRELEASENOTES

### CODE REVIEW

**Comment by sfayer** [comment]
This looks like a good approach to me and should fix our issue... I'm a little dubious about adding the --cfg at that specific point in-case someone wanted to include an extra option that isn't a config (although I don't think I've ever actually seen that used for anything else).

Regards,
Simon

**Comment by fstagni** [comment]
Thanks Simon. Regarding your remark: theoretically, it's possible to include an extra option that is not a DIRAC cfg file, but practically speaking that would not happen. I anyway added one more check.

**Comment by atsareg** [comment]
I do not see how this PR fixes the problem. The "ExtraOption" is added to the job's executable arguments in the JobAgent. In the JobWrapper you can not change this. This ExtraOptions option is quite confusing and needs some extra discussion/clarification

**Comment by fstagni** [comment]
I close this one now. I will look into providing a different fix using `DIRACSYSCONFIG`, and I will re-open if I see issues.

**Comment by fstagni** [comment]
Re-opened after https://github.com/DIRACGrid/Pilot/pull/122

**Review by atsareg — APPROVED** [review]

**Pull request merged**
