### PR TITLE
[v6r14] Installation scripts

### PR DESCRIPTION
**Pull request by Sbalbp**
Added an install and uninstallation scripts that allow the (un)installation of components regardless of their type, which must be specified in the command itself (only for installation).

### CODE REVIEW

**Comment by atsareg** [comment]
The command will be more convenient if the component type is determined automatically from the module name

**Comment by fstagni** [comment]
The dirac-install-component script is a replacement for dirac-install-[service|agent|executor] that should therefore be deleted.

Regarding name of the module and type: some agents (e.g. "SiteDirector") can't be recognized as agents by their names.

**Comment by atsareg** [comment]
I understand that this command is replacing 3 others. Agents can be recognized not by their names but by their modules which is true also for services.

**Comment by fstagni** [comment]
Review OK

**Pull request merged**
