### PR TITLE
[v6r14] soleve ps -q 

### PR DESCRIPTION
**Pull request by zmathe**

### CODE REVIEW

**Comment by zmathe** [comment]
this has to be replaced by monitoringtools which are in v6r16....

**Comment by fstagni** [comment]
Review OK...

**Comment by IgorPelevanyuk** [comment]
When this is supposed to be merged?

**Comment by IgorPelevanyuk** [comment]
And how can I install fixed version?

**Comment by atsareg** [comment]
Just wait wjen it will be releases
      (shortly).
      
        Cheers,
        Andrei
      
      On 02/06/16 17:18, IgorPelevanyuk wrote:
    
    
      And how can I install fixed version?
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Pull request merged**
