### PR TITLE
[v6r17] Minor fixes

### PR DESCRIPTION
**Pull request by phicharp**
BEGINRELEASENOTES
* RequestManagementSystem
FIX: avoid INFO message in client 
* WMS
CHANGE: Allow SE-USER to be defined as another SE group (e.g. Tier1-USER)
* DMS
CHANGE: make resolveSEGroup recursive in order to be able to define SE groups in terms of SE groups

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
The branch has conflicts. I try to target v6r17 (it's integration now), but should be anyway understood what's the problem.

**Comment by fstagni** [comment]
Yep conflicts desappeared

**Comment by phicharp** [comment]
Sorry Fede, my mistake, I forgot to change the base in the PR... and also added a few more changes ;-)

**Comment by atsareg** [comment]
Philippe, it is fine that you make all these fixes. But while you are working on that and keep adding commits which are not reactions to the reviewer comments, please make this PR a WIP. Once this is finished/frozen, the WIP should be removed. This will allow reviewers to understand that it is high time to review. You can always continue fixes with a new PR after that.

**Comment by phicharp** [comment]
@atsareg Yes, I agree! I had not anticipated that I would go through so many little things... it's a never ending story!
I stop for now adding commits to this PR, please review!

**Pull request merged**
