### PR TITLE
[v6r15] Get information from alternative bdiis for sites not existing in central one.

### PR DESCRIPTION
**Pull request by andresailer**
As discussed here: https://groups.google.com/forum/?hl=en#!topic/diracgrid-forum/KdZ9pg_Dj18

The information from the alternates will only be used for sites that don't exist in the primary one.

### CODE REVIEW

**Comment by fstagni** [comment]
I am bit puzzled. Doesn't this contradict what Andrei was saying in the google forum thread?

One more question: suppose you have a list of `alternativeBdiis` that have contradictory information: the order in which you analyse them may become important: how is that assured?

**Comment by andresailer** [comment]
No, I think this will do exactly this
" add the site info from alternative BDIIs in case the site is not present in the main BDII."
the update with the mainResult (coming at the end) will overwrite everything from the alternative BDIIs

Should I revert the order in the list to make the first one be more important than the last in a list of many alternative BDIIs?

**Comment by atsareg** [comment]
I think the logic is OK, corresponds to my comments at least. The order in which alternative BDIIs are taken into account is determined by the order in the CS. The only thing is that the most important one is the last one now. It would be better to have a reversed order.

**Comment by atsareg** [comment]
The last two comments just crossed :)

**Comment by atsareg** [comment]
Review OK

**Pull request merged**
