### PR TITLE
!!! [v6r15] Make S_ERROR dictionary behave as DError

### PR DESCRIPTION
**Pull request by atsareg**
Replace DError class by the enhanced S_ERROR structure. Not fully tested, rather to demonstrate the non-object solution.

### CODE REVIEW

**Comment by fstagni** [comment]
We'd need to move quickly on this one. Especially after we announced that DError is the main feature of v6r15.

**Comment by chaen** [comment]
I wrote a parser for it this morning, and I asked Zoltan to re run it's benchmark using it, to see if the object really has a perf hit. Andrei sent me a private mail to discuss it but I did not answer it yet (but we can do this here). In general I have nothing against the structure, especially if it is faster. Also, he proposes to get ride of the compatibility string, which I think is a good idea, even thought it scares me a bit. The only issue I can see with the structure, which he also points at in the mail, is in case we want to return it in the Failed dictionnary, which was my original motivation for changing the error system. I think it is clear, we must have the same feature in the Failed dictionnary. Andrei, do you have an idea on how we could do it with the structure ? 
Zoltan is coming back tomorrow, let's wait for his benchmark, maybe (hopefuly)  a complete change is not needed

**Comment by zmathe** [comment]
I made few test. My opinion is to keep the DErrno. You can see the result of my test.
1. using objects:
#---------DErrno
Encode-DErrno: 10.8652720451
Decode-DErrno: 44.9934368134
#---ujson
Encode-U: 177626 2.01598286629
Decode-U: 25 2.31132912636
#------cPickle
Encode-P: 177626 5.81767702103
Decode-P: 25 4.23345112801
#-------json
Encode-J: 177626 6.43958306313
Decode-J: 25 6.6806139946
#------DEncode
Encode-D: 177626 11.1984660625
Decode-D: 2 36.5213189125

2. using string:
#---------DErrno
Encode-DErrno: 7.96136212349
Decode-DErrno: 41.5073828697
#---ujson
Encode-U: 177626 0.84553194046
Decode-U: 391 1.46819210052
#------cPickle
Encode-P: 177626 1.61722493172
Decode-P: 391 0.891602993011
#-------json
Encode-J: 177626 2.14450502396
Decode-J: 391 4.63101601601
#------DEncode
Encode-D: 177626 2.61866021156
Decode-D: 2 19.8822159767

**Comment by zmathe** [comment]
You have to compare the result:
#---------DErrno
Encode-DErrno: 10.8652720451
Decode-DErrno: 44.9934368134
#------DEncode
Encode-D: 177626 11.1984660625
Decode-D: 2 36.5213189125

and
#---------DErrno
Encode-DErrno: 7.96136212349
Decode-DErrno: 41.5073828697
#------DEncode
Encode-D: 177626 2.61866021156
Decode-D: 2 19.8822159767

**Comment by chaen** [comment]
Just so that I understand correctly.
What is in DErrno section is when you tried to serialize the same list of 100k lfns you had before, but using the json encoder/decoder that supports DError, is it correct ?

**Comment by zmathe** [comment]
Note: the tests what I am using is intended to show the performance difference. This is an extreme case, we will not have this workload in production.

**Comment by zmathe** [comment]
@chaen This is a bit different. This is the result what show that:
#---------DErrno
Encode-DErrno: 2.93188619614
Decode-DErrno: 4.96354913712

#---ujson
Encode-U: 58962492 2.31428194046
Decode-U: 2 3.73201704025
#------cPickle
Encode-P: 106362877 16.7412250042
Decode-P: 2 8.66858196259
#-------json
Encode-J: 77518466 8.12531614304
Decode-J: 2 12.7060837746
#------DEncode
Encode-D: 72782633 20.6676700115
Decode-D: 2 40.6596519947

**Comment by zmathe** [comment]
I used 177626 lfns and their metadata.  
the test dataset is a list of dictionaries: lfns = [{},{}]
I used two different tests:
1. res = serialiser.dump(lfns) and serialiser.load(res) The result is in my previous post.

2. derr = []
 for i in lfns:
   derr += [DErrno.DError(1, i)]
 for i in derr:
   dres += [json.dumps(i, cls = DErrno.DIRACJSONEncoder)]
 end = time.time()-start
 print 'E-DErrno:', end
 start = time.time()
 for i in dres:
   x2 = json.loads(i, cls = DErrno.DIRACJSONDecoder)
 end = time.time() - start
 print 'D-DErrno:', end

and I also checked how fast if I only encode the element of the list:
dres = []
start = time.time()
for i in lfns:
  dres += [ujson.dumps( i )]
end = time.time() - start
print 'E-U:', len(dres), end
start = time.time()
for i in dres:
  a = ujson.loads( i )
end = time.time() - start
print 'D-U:', len(a), end

**Comment by zmathe** [comment]
I made the following test. I have a list of strings:
lfns = ["['/lhcb/data/2015/RAW/FULL/LHCb/COLLISION15/162871/162871_0000000198.raw', 58108, 3145742040, '2015-09-12 21:25:00', '2015-09-12 01:52:19', '2015-09-12 02:14:35', None, 'RAW', 162871, 4349, 65103, 'UNCHECKED', None, 123809.775098, 1038.01900388, 0, '0x10700a1', '1ce038f0-5985-11e5-a98f-00259012197e', None, 90000000, '321A2693DD030A6BE1044ADAEE90B142', 'Y', 326303361, 'Yes', '2015-09-13 02:37:24']","", ...]
The list contains 177626 string: len(lfns) = 177626
The test cases are the following:
a.) List of lfns 
1. dres = json.dumps(lfns, cls = DErrno.DIRACJSONEncoder)
2. a = json.loads(dres, cls=DErrno.DIRACJSONDecoder)
3. dres = DEncode.encode( lfns )
4. a = DEncode.decode( dres )

b.) List of DErrno:
In the following test I used DErrno:
```
for i in lfns:
 xJson += [DErrno.DError(1, i)]
```
5. dres = json.dumps(xJson, cls = DErrno.DIRACJSONEncoder)
6. a = json.loads(dres, cls = DErrno.DIRACJSONDecoder)
7. dres = DEncode.encode( xJson )
8. a = DEncode.decode( dres )

The result of the tests:
List of lfns:
json:
1. Encode: 0.603693962097
2. Decode: 1.40266799927
DEncode:
3. Encode: 0.585586071014
4. Decode 1.25886917114
List of DErrno:
json:
5. Encode: 4.14151000977
6. Decode: 41.4012188911
DEncode:
7. Encode: 2.05545401573
8. Decode: 25.6876590252

**Comment by zmathe** [comment]
I have another test cases and DEncode always faster than customised json when we use DErrno. However, this is an extreme case we never have to serialise an object which contains 177626 DErrno object...

**Comment by zmathe** [comment]
Of course if we do not use DErrno, the serialisation will be faster. As we know that we are not passing lot of error messages to the client I strongly suggest to keep DErrno.

**Comment by fstagni** [comment]
I think here the main question is "how slower is (d)encoding DError with respect to S_ERROR?"

**Comment by chaen** [comment]
Just a comment on DIRACJSONEncoder/DIRACJSONDecoder 
I wrote these classes in a very very generic manner, they can virtually serialize/deserialize  any of our custom classes, and handles datetimes. However here we have a decision to make which I think should be reserved for a meeting. 
Either we propose to have such a generic solution in the framework, and we could easily transfer custom objects over the network without explicit encoding/decoding on the client/service side, but this has a performance impact; or we have to explicitly transformer our custom objects into base types on the client/service, and optimize our encoding/decoding classes in the framework for DError (no datetime, no dynamic class loading, no bootstrap, etc).

**Comment by zmathe** [comment]
the result of the serialisation of S_ERROR:
#---------S_ERROR json
Encode-S_ERROR: 0.935889005661
Decode-S_ERROR: 4.22836589813

#------DEncode-S_ERROR
E-S_ERROR:1.83913707733
D-S_ERROR: 2.59519314766

If we use json and DErrno object and the current serialisation algorithm, the result is the following:
5. Encode: 4.14151000977
6. Decode: 41.4012188911
if we use json and S_ERROR, with the current serialisation algorithm, the result is the following:
Encode-S_ERROR: 0.935889005661
Decode-S_ERROR: 4.22836589813

You can see the difference now. Serialising python basic types it is very fast! I strongly suggest do not serialise python objects, because it is very slow. We can have one exception which is DErrno...

**Comment by atsareg** [comment]
The problem is that there is an intention to return S_ERROR/DError in the Failed dictionary for bulk queries. It means that large numbers of those objects may need serialization. If we use an updated S_ERROR, then: 1. It is fully compatible with the existing code, no need to change S_ERROR to DError calls 2. It is faster to serialize if many of those objects to be used. 3. This solution is not limiting compared to the DError class keeping all the introduced new features. So, we have the best of the two worlds

**Comment by chaen** [comment]
For sure, but how do you put the structure in the Failed dictionary ? If we can solve that, then your solution is definitely better.

**Comment by atsareg** [comment]
You put it just as a value of the corresponding LFN key, for example. What is the problem here ?

**Comment by zmathe** [comment]
@atsareg But we are going to put 177626 DErrno object to the Faild dictionary? If yes, we will have problem... I think the question is the following: Do we want to return more than 100k DErrno?
If the answer is yes, we have to use S_ERROR.
I am going to optimise the serialisation of DErrno... let me check how fast we can go.

**Comment by chaen** [comment]
but how do you then test ? 
I will have 
```
res = { 'OK':True,
           'Value': { 'Successful' : {},
                         'Failed': { { 'myLfn' : { 'OK': False, 'Errno' : 3, 'Message': 'Toto' , 'CallStack' : [] } } }
                      }
        }
```
How do I loop over the Failed dictionary to test the error case in a compatible way with what is currently existing, that is, a simple String ?

**Comment by atsareg** [comment]
We have to be consistent. We do not use S_ERROR now in the Failed structure. If we start using it instead of a string, then we should start using Error numbers to test the errors. Comparing strings should be the story of the past. This is one of the main DError proposals, isn't it ? Still the strings can be compared to the result['Message']. Yes, this is not compatible with some of the existing codes, but this is easy to fix and better fix it to use error numbers straight away.

**Comment by chaen** [comment]
Yes, it is one of the main proposals. 
So if I understand correctly, you want to replace everywhere in the code the string comparison with the numbers comparison ? I might be mistaken, but this seems a huge change to me. And when discussing it in Taipei, I had understood that changing all at once was one of your main fear with changing the error system (and one of mine as well ! ). 
Also, just from the top of my head, it is not only a problem of testing, but for example, when we assign the error message to the File object of a Request, we have to be careful here. But just writing these lines, I realize we might have a problem with DError as well here, I had overlooked that aspect... We now need to also store the error number in the DB, not only the message. I had taken this into account for the DataLogging, but overlooked the rest. Damn !

**Comment by atsareg** [comment]
There is no fire with changing everything. Only if we change String to S_ERROR then the comparison changes. This we can do progressively without a global rush. On the contrary, all the S_ERROR structures everywhere are the new ones without changing the code, so we start benefiting from it immediately.
As for the particular case of storing the error in the database, we can store the string with the error code embedded and make a simple utility to serialize/deserialize the message in this way. Again, there is no urgency to change everything at once.

**Comment by chaen** [comment]
I am afraid it is a bit nastier. For example I have already replaced S_ERROR with DError, for example in SRM plugins, that then ends in Failed dictionary.

Well I am pretty sure that we at least need a fix, because as of now, we would easily end up with having file.error = DError, and this will not work when inserting in the DB. We could use a property indeed. Or a simple fix now would be to do f.Error = "%s"%err 
Damn damn damn ! This needs to be tried

**Comment by atsareg** [comment]
f.Error = "%s"%err  looks quite acceptable. If it is f.Error = result['Message'], you can even do the check "%d" % Ernum in f.Error. Not sure, this is a good idea though. Rather Ernum == getErrorNumberFromTheErrorUtility( f.Error )

**Comment by chaen** [comment]
f.Error = "%s"%err will at least transform it into a string, and we can store it, but when it will be fetched from the DB it will be just a string. I don't think it is a good idea to do this sort of nasty parsing. What we can do, coming back on the original subject, is to store the error as a json dump. if it is a string, it stays a string. if it is a DError, it is transformed into a storeable string, and reloaded as a DError object :-) Note that this would also work for the S_ERROR dictionary you propose. We might just run into trouble because of the error field size in the DB, since we have the callstack...

Now still remains this problem of having a dictionary/object in the Failed dictionary. I don't clearly see how the change can be progressive, but maybe again I just misunderstand ?

**Comment by atsareg** [comment]
Yes, storing the json dump in the Error field of the database is a similar solution just using loads/dumps as the serialization utility. 
As for the Failed dictionary. Now the code assumes the strings are stored there and only strings are actually stored. If we start storing S_ERROR, the corresponding checking code must be changed to do Ernum comparison. But only the code for the updated Failed result structure. If you put DError object instead, you can be compatible with the error string comparison conserving the outdated method of checking forever. Was this is a real intention ?

**Comment by chaen** [comment]
I will have a look for the json. It fits anyway well the tests of Zoltan.

But the content of Failed can propagate quite high no ? I mean, whatever uses the DMS possibly needs be updated. 
Obviously the aim is to give up string comparison, and for sure avoid to stay compatible with the old system for ever ! How about we do it in two steps ? I must confess I doubt that we can change the content of Failed for dictionaries without  running into trouble. So the object keeps on the safe side. On the other hand, the structure is much faster to serialize. But we are not under pressure for serialization performance at the moment are we ? What would you think of the following:
* we start to use DError and json. We don't gain performance for serialization, we start using the new error system, and replace all the comparison calls in the code
* This transition can last for 1 or 2 versions. We can even display warning messages in the cmpError call if we turn out to compare old style error message. This should clean pretty much all the comparisons we have, and give times to the extensions to adapt. 
* we replace DError by the structure you propose, we can even call it S_ERROR and just do a global replace of the name DError by S_ERROR, it should work almost straight forward, except maybe the internals of cmpError. And then we get our performance boost.

Does this sound reasonable to you and the others ?

**Comment by zmathe** [comment]
I managed to optimise the DErrno decoding. It is now takes 8.29877591133 second.
I used the same test. Before the optimisation:
5. Encode: 4.14151000977
6. Decode: 41.4012188911
after the optimisation:
Encode 3.98003005981
Decode: 8.29877591133
I do not think we can go to much farther...

**Pull request closed without merging**
