### PR TITLE
[v6r12] SystemAdmin: show executors in log overview

### PR DESCRIPTION
**Pull request by andresailer**
Show executors in log overview,

### CODE REVIEW

**Comment by fstagni** [comment]
Review OK, but I think this is fixed already in v6r13

**Comment by andresailer** [comment]
Which patch of v6r13? 
This is the "show errors" overview at least in p08 I don't see any executors in that overview.

**Comment by chaen** [comment]
No I don't think it is fixed anywhere

**Comment by fstagni** [comment]
Ok then. It was anyway reviewed OK.

**Pull request merged**
