### PR TITLE
[8.0] fix (Configuration): fix ES access using certificates

### PR DESCRIPTION
**Pull request by arrabito**
BEGINRELEASENOTES
*Configuration
FIX: Fix the connection to ES database when using certificates
ENDRELEASENOTES

### CODE REVIEW

**Review by aldbr — COMMENTED** [review]
We might end up with the same issue as we had before: https://github.com/DIRACGrid/DIRAC/pull/6078

Since then, warning logs were converted to debug logs, but jobs will likely still display them: https://github.com/DIRACGrid/DIRAC/commit/ed4b7fc4377333777d88d7c1885c23020342a100#diff-aae750c606b1d50a39f4100dfc4518c53057c04dc88959d824208722c0b88409

To avoid that, maybe we can first check whether the `CRT` parameter is defined as you did but without displaying a log.
- If yes, then `client_cert`, `client_key`, `ca_certs` are mandatory (?): instead of displaying a log, we return `S_ERROR`.
 - Else, then `username` and `password` are mandatory: we already return `S_ERROR` if they are not defined.

Then we have the optional parameters (`Host`, `Port`, `SSL`), and here we can display some logs.
What do you think?

**Comment by arrabito** [comment]
I agree with you. 
I will commit a change according to your suggestion and you will tell me if I understood correctly.

**Review by fstagni — DISMISSED** [review]
Looks OK to me. For the commit message check failure:

```
Checking commit messages against "^((docs|feat|fix|refactor|style|test|sweep)( ?\(.*\))?: .+|Revert ".+")$"...
- failed: "Fix ES connection using certificates"
- failed: "remove warn when mandatory parameters are not defined"
Error: Error: Your commit has to follow the format "<type>(<scope>): <subject>"".
```

Basically, your 2 commit messages should have been:

fix: ES connection using certificates
and
refactor: remove warn when mandatory parameters are not defined

We can still merge this as-is, but if you can just

```
git rebase -i HEAD~2
```
and "reword" the 2 commits correctly.

**Comment by arrabito** [comment]
Thank you for the explanations. 
However, I was not able to rename the commits:

```
$ git rebase -i HEAD~2
[HEAD détachée 57a04f9c3] fix: ES connection using certificates
 Date: Tue Feb 28 13:49:32 2023 +0100
 1 file changed, 71 insertions(+), 66 deletions(-)
[HEAD détachée be56d2575] refactor: remove warn when mandatory parameters are not defined
 Date: Tue Feb 28 18:09:54 2023 +0100
 1 file changed, 33 insertions(+), 35 deletions(-)
Rebasage et mise à jour de refs/heads/fixgetESparams02 avec succès.
$ git push origin fixgetESparams02 
To github.com:arrabito/DIRAC.git
 ! [rejected]            fixgetESparams02 -> fixgetESparams02 (non-fast-forward)
error: impossible de pousser des références vers 'github.com:arrabito/DIRAC.git'
astuce: Les mises à jour ont été rejetées car la pointe de la branche courante est derrière
astuce: son homologue distant. Intégrez les changements distants (par exemple 'git pull ...')
astuce: avant de pousser à nouveau.
astuce: Voir la 'Note à propos des avances rapides' dans 'git push --help' pour plus d'information.
```
So it seems that I could rename the commits but then the push is rejected.

**Comment by chaen** [comment]
you have to use `push --force`

and no, we can't merge as is, as it would break the CI of the main branch

**Comment by arrabito** [comment]
OK thank you.
Just done, I hope I've done it correctly.

**Comment by fstagni** [comment]
> OK thank you. Just done, I hope I've done it correctly.

Yes, it is correct. Thank you, we'll merge as soon as all the tests are over.

**Review by fstagni — APPROVED** [review]

**Pull request merged**
