### PR TITLE
[v7r2] Fix handling Subprocess calls which produce invalid output

### PR DESCRIPTION
**Pull request by chrisburr**
Should fix this error seen in some LHCb jobs by explicitly replacing the bad sequences with the [unicode replacement character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character). The alternatives would be to:

* explicitly treat this as `bytes` but that will make all calls to subprocess harder
* add a new `text=True` keyword argument is needed like the standard library has but that's going to be quite invasive and that time is probably better spent deprecating DIRAC's `Subprocess` class in favour of the standard library.

```python
2021-06-15 10:54:27 UTC Test_UserJobs/Subprocess [22371007629120] ERROR: SUBPROCESS: readFromFile exception
Traceback (most recent call last):
  File "/cvmfs/lhcb.cern.ch/lhcbdirac/v10r2p3/DIRAC/Core/Utilities/Subprocess.py", line 382, in __readFromFile
    dataString += nB.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 1938: ordinal not in range(128)
2021-06-15 10:54:27 UTC Test_UserJobs/Subprocess [22371007629120] ERROR: Error reading type(nB) =<type 'str'>
2021-06-15 10:54:27 UTC Test_UserJobs/Subprocess [22371007629120] ERROR: Error reading nB =2021-06-15 10:54:27 UTC dirac_jobexec/Subprocess ERROR: SUBPROCESS: readFromFile exception
Traceback (most recent call last):
  File "/cvmfs/lhcb.cern.ch/lhcbdirac/v10r2p3/DIRAC/Core/Utilities/Subprocess.py", line 382, in __readFromFile
    dataString += nB.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 1403: ordinal not in range(128)
2021-06-15 10:54:27 UTC dirac_jobexec/Subprocess ERROR: Error reading type(nB) =<type 'str'>
2021-06-15 10:54:27 UTC dirac_jobexec/Subprocess ERROR: Error reading nB ========================================================================
======       Pre-compound/De-excitation Physics Parameters     ========
=======================================================================
Type of pre-compound inverse x-section              3
Pre-compound model active                           1
Pre-compound excitation low energy (MeV)            0.1
Pre-compound excitation high energy (MeV)           30
Type of de-excitation inverse x-section             3
Type of de-excitation factory                       Evaporation+GEM
Number of de-excitation channels                    68
Min excitation energy (keV)                         0.01
Min energy per nucleon for multifragmentation (MeV) 2e+05
Limit excitation energy for Fermi BreakUp (MeV)     20
Level density (1/MeV)                               0.075
Use simple level density model                      1
Use discrete excitation energy of the residual      0
Time limit for long lived isomeres (ns)             1000
Internal e- conversion flag                         1
Store e- internal conversion data                   0
Electron internal conversion ID                     2
Correlated gamma emission flag                      0
Max 2J for sampling of angular correlations         10
Upload data before 1st event for                Z < 9
=======================================================================
6�x

FAIL

```

BEGINRELEASENOTES

*Core
FIX: Fix handling Subprocess calls which produce invalid output

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
The `Test_Subprocess` fails (py2 and py3)

**Comment by atsareg** [comment]
I guess these errors are meaningful, please fix

**Comment by chrisburr** [comment]
> I guess these errors are meaningful, please fix

It's just a buggy test that affects GitHub actions but not my local machine (maybe Ubuntu specific), hopefully af0e2d0 works.

**Comment by chrisburr** [comment]
Looks like rucio have broken their master branch....

**Comment by atsareg** [comment]
Don't you think that there is something wrong in the CI design if the fact that Rucio breaks their master branch breaks the DIRAC CI tests ?

**Comment by chrisburr** [comment]
Definitely. It’s using the master branch as rucio doesn’t work without it. The ruicio stuff should never never have been propagated in the current state.

**Comment by fstagni** [comment]
Several times I heard about "rucio is correctly packaged" so here we are discovering that it's not.

**Comment by chrisburr** [comment]
> rucio is correctly packaged

Sorry but it is correctly packaged. The only issue is they decided to be overly conservative with restricting the Python version, a mistake in my opinion but it's more of a philosophical problem and there are very competent people who would disagree with me.

The mistake was merging the rucio PR into an old DIRAC branch and just hoping it would work in newer ones. Now we're piling up hacks (#5193) when this could all have been avoided by #5139.

**Comment by fstagni** [comment]
The original PR was for v6r22, which is the version their users are using now. It was bumped to v7r0 to at least enjoy some tests. Of course in later branches we have better tests, and yes I was expecting it to work there too. Others would say that the error was to use the rucio python binding (when the rest interface could be used). The sweeper would have indeed been very useful here but there's no yet an agreement on it.

**Review by fstagni — APPROVED** [review]

**Comment by fstagni** [comment]
I will now merge and propagate this one, for fixing the tests for the other PRs.

**Pull request merged**
