### PR TITLE
[v6r18] Add script to get release notes from pull requests

### PR DESCRIPTION
**Pull request by andresailer**
This script uses the github api (via curl) to get the release notes for pull requests that were merged since a given date.

You need to get your github Personal Access Token from here https://github.com/settings/tokens
And put it in the place the script expects:
```
Filename: GitTokens.py
Content:
GITHUBTOKEN = "e0b83063396fc632646603f113437de9"
```
 (this is some git sha, not my PAT)
The output from the script needs to be copied to the `release.notes` file by hand

At least two things need to be fixed:
- [x] : get the date from which to check PRs from command line argument
- [x] : change to closed and merged PRs, right now used open as otherwise there are no release notes to parse...
- [x] : get the desired branches from command line arguments
- [x] : update http://dirac.readthedocs.io/en/integration/DeveloperGuide/DevelopmentModel/ReleaseProcedure/index.html

Possibly:
- [x] : replace WMS etc. by WorkloadManagementSystem etc. ?
- [x] : add #PRID to the release notes entries

See output below. Please have a look @atsareg @fstagni 
anything else you would like the script to do?

There are no two PRs targeting the same system so the collation of changes for a single system is not tested

Right now this produces:

```
[integration]


[rel-v6r18]

*Core

FIX: dirac-distribution will by default compile for python 2.7

*tests

NEW: added submitAndMatch test for Jenkins style jobs

*WMS

NEW: The JobWrapperTemplate can reschedule a job if the payload exits with status 111

*ConfigurationSystem

NEW: Allow to define FailoverURLs and to reference MainServers in the URLs

*AccountingSystem

FIX: change the queries, which are used by the unit tests.

*Interfaces

FIX: correctly setting local PATHs for local job execution


[rel-v6r17]

* WorkloadManagementSystem

FIX: SiteDirector - unlink is also to be skipped for Local Condor batchsystem

*Core

FIX: dirac-install.py to fail when installation of lcgBundle has failed


[rel-v6r15]
```

BEGINRELEASENOTES

*Docs
NEW: Add script to collate release notes from Pull Request comments 

ENDRELEASENOTES

EDIT: updated to-do items

### CODE REVIEW

**Comment by fstagni** [comment]
I agree with both your proposals in "possibly". 
I add one more to-do: update http://dirac.readthedocs.io/en/integration/DeveloperGuide/DevelopmentModel/ReleaseProcedure/index.html

**Comment by andresailer** [comment]
So you mean always have the full system name, with or without system?

**Comment by fstagni** [comment]
Full system name looks clean to me.

**Comment by andresailer** [comment]
All done
```
$ python GetReleaseNotes.py  --date 2017-06-01 --o --branches rel-v6r18
[rel-v6r18]

*Core

FIX: (#3387) dirac-distribution will by default compile for python 2.7

*tests

NEW: (#3387) added submitAndMatch test for Jenkins style jobs

*ConfigurationSystem

NEW: (#3395) Allow to define FailoverURLs and to reference MainServers in the URLs

*WorkloadManagementSystem

NEW: (#3394) The application error codes, when returned, are passed to the JobWrapper, and maybe interpreted.
NEW: (#3394) The JobWrapperTemplate can reschedule a job if the payload exits with status DErrno.EWMSRESC

*AccountingSystem

FIX: (#3386) change the queries, which are used by the unit tests.

*Interfaces

FIX: (#3387) correctly setting local PATHs for local job execution
```

**Comment by andresailer** [comment]
http://diracsailer.readthedocs.io/en/integration/DeveloperGuide/DevelopmentModel/ReleaseProcedure/index.html?highlight=ReleaseProcedure#release-notes

**Comment by andresailer** [comment]
Rebased to v6r18

**Pull request merged**
