### PR TITLE
[v7r3] fix (resources): SLURM multi-node allocations

### PR DESCRIPTION
**Pull request by aldbr**
A few fixes related to multi-node allocations with SLURM.

BEGINRELEASENOTES

*Resources
FIX: multi-node allocations with SLURM

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Hard for me to understand the subtleties of SLURM. Do you have the possibility to properly test this?

**Comment by aldbr** [comment]
This is a very specific feature implying SLURM and multi-node allocations.
I added a few details in the unit tests but it is not like an end-to-end test of course.
I also tested these changes manually on a supercomputer.

Adding an integration test would imply that we have an SSH access to a SLURM cluster allowing us to make multi-node allocations, do we have that?
Would it be worth making our own (micro) SLURM cluster for that?

**Comment by andresailer** [comment]
CERN has a slurm cluster https://batchdocs.web.cern.ch/linuxhpc/index.html

**Comment by fstagni** [comment]
Can we add an SSHCE site in DIRAC certification submitting to this cluster?

**Review by atsareg — APPROVED** [review]

**Comment by fstagni** [comment]
> Can we add an SSHCE site in DIRAC certification submitting to this cluster?

Actually, from https://batchdocs.web.cern.ch/linuxhpc/access.html:

> The HPC batch cluster using SLURM is dedicated for users of MPI applications in the Accelerator and Technology sector at CERN or the Theory Lattice QCD team.
Access to the cluster is granted via e-groups. In general users should only be granted access by their local HPC experts and supervisors.

...unless @andresailer knows we can use it for tests.?

**Comment by andresailer** [comment]
Yeah, I think one can still use it: https://cern.service-now.com/service-portal?sys_kb_id=2d3e29e4db3a54d0f4c8949adb9619da&id=kb_article_view&sysparm_rank=1&sysparm_tsqueryId=a0ba12d1874e7c502d1442650cbb3586
if that doesn't exactly work like we expect, surely we can talk to the admins

**Pull request merged**
