### PR TITLE
[v6r15] help the python GC

### PR DESCRIPTION
**Pull request by zmathe**

### CODE REVIEW

**Comment by chaen** [comment]
Why do you need to redifine the variable after doing a del on them ?

**Comment by zmathe** [comment]
which variable?

**Comment by zmathe** [comment]
retVal = None ??

**Comment by chaen** [comment]
retVal and fileHelper

**Comment by zmathe** [comment]
In principle del must be enough. I putted variable = None, because we are using some C library.
We are using MySQL or Oracle libraries for communicate with the database. The core of the packages is implemented in C/C++. We are calling functions from python. In C/C++ to make sure that a memory is deleted it is better to use:
delete variable;
variable = NULL;
In that case the memory is freed and also the pointer is NULL.
I though if I put in python variable=None, I will delete the pointer in C. 
But having variable=None, will not change nothing. I do not think also It will help.
What I have noticed that del will help the GC. But this we will see in production...
At least I was able to see those del is helped when I tested.

**Comment by fstagni** [comment]
As discussed yesterday, I would remove the "variable = None" sentences.

**Pull request merged**
