### PR TITLE
[v7r2 pre39] small py3 doc fix

### PR DESCRIPTION
**Pull request by TaykYoku**
This PR is designed to solve the problem described in [comment](https://github.com/DIRACGrid/DIRAC/pull/5032#discussion_r593079690), will fix only scripts docs in python3 env. Compact version.

BEGINRELEASENOTES

*Core
FIX: set usage massage in Script global methods

ENDRELEASENOTES

### CODE REVIEW

**Comment by TaykYoku** [comment]
restart tests

**Comment by atsareg** [comment]
Does this PR replace #5035 ?

**Comment by chrisburr** [comment]
This PR is a workaround that is good enough v7r2.

#5035 is better suited to v7r3 as it's so large that I think it isn't suitable for v7r2 without being certified.

**Review by atsareg — APPROVED** [review]

**Comment by atsareg** [comment]
OK. So this PR fixes the docs creation and allows to finalize the v7r2 release. #5035 will be retagged v7r3 and will be merged to the integration as soon as the v7r2 branch will be created. Everybody agrees ?

**Comment by chrisburr** [comment]
> OK. So this PR fixes the docs creation and allows to finalize the v7r2 release. #5035 will be retagged v7r3 and will be merged to the integration as soon as the v7r2 branch will be created. Everybody agrees ?


#5035 still needs to be reviewed but yes 👍

**Pull request merged**
