### PR TITLE
[v6r15] ComponentsInstaller

### PR DESCRIPTION
**Pull request by Sbalbp**
This is an adaptation of InstallTools as a class. This way it is much easier to extend the functionality currently provided by InstallTools when developing for any extension ( like LHCbDIRAC ).
It includes support for the newly introduced type of component, MQ consumers.

For now, I have thought of making it a singleton, just because it is easier to adapt all the code that currently uses InstallTools to use this singleton instead.

Feedback is welcome :-)

### CODE REVIEW

**Comment by atsareg** [comment]
Am I alone not being able to comment on the code since File changes tab shows nothing ?

**Comment by sposs** [comment]
No, it's because it's a large file completely new.

**Comment by fstagni** [comment]
Yes, but still for other PRs with new single files, they can be commented. Not sure what's happening here.

**Comment by sposs** [comment]
I belive the 2700+ lines makes it hard for the github editor...

**Comment by atsareg** [comment]
I will merge this PR as it is a new tool. I will rename the main class from ComponentsInstaller to ComponentInstaller to make it better english.

**Comment by andresailer** [comment]
https://help.github.com/articles/what-are-the-limits-for-viewing-content-and-diffs-in-my-repository/

**Comment by atsareg** [comment]
The purpose of introducing this PR is to make a class that can be replaced/extended in DIRAC extensions. We  have this mechanism for basic types of components ( services, agents, resources, etc ).
Client is yet another basic component type. So, I suggest this class becomes a client and is moved to the Framework/Client directory. I do not like the idea to have utilities that can be extended

**Comment by fstagni** [comment]
The idea is that an extension may want to introduce a new type of component.

**Comment by atsareg** [comment]
Yes, and extend the ComponentsInstaller accordingly

**Comment by fstagni** [comment]
Review OK

**Pull request merged**
