### PR TITLE
[Integration]Fts3 docs

### PR DESCRIPTION
**Pull request by andresailer**
BEGINRELEASENOTES

*Docs:

FIX: Drop some old stuff, add link for FTS3 page

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
review OK

**Comment by andresailer** [comment]
Added an instllation section, but still missing how to sync the fts server into the RSS system, I think

**Comment by fstagni** [comment]
RSS should sync without specific commands given: https://github.com/DIRACGrid/DIRAC/blob/integration/ResourceStatusSystem/Utilities/Synchronizer.py

**Comment by fstagni** [comment]
still [WIP]? Wanna merge?

**Comment by andresailer** [comment]
Should be fine for now.

**Pull request merged**
