### PR TITLE
[8.1] test: added a backward compatibility integration test

### PR DESCRIPTION
**Pull request by fstagni**

### CODE REVIEW

**Comment by chrisburr** [comment]
I think this is only changing the test code that is used and not the branch that is installed.

**Comment by fstagni** [comment]
> I think this is only changing the test code that is used and not the branch that is installed.

Correct, maybe this last fix I just added will be enough. 
Another fix to add is to make this option working also for extensions.

**Comment by fstagni** [comment]
There is also a chicken-and-egg issue because by taking as test code what is in `rel-v8r0` the `utilities.sh` file does not contain what's in this PR...

**Comment by fstagni** [comment]
Looks like it worked. Review, please.

**Review by chrisburr — APPROVED** [review]

**Pull request merged**
