### PR TITLE
[WIP] SingularityCE Container support

### PR DESCRIPTION
**Pull request by sfayer**
Hi,

Further to ticket #3381 and as mentioned at a previous BiLD meetings, here is the start of a SingularityComputeElement module for some discussion. I had to modify the code which writes the job wrapper so that it can be relocated: I've done this in a way that hopefully shouldn't affect any existing CEs.

Regards,
Simon

BEGINRELEASENOTES
*Resources
NEW: Add SingularityCE module.
ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
I certainly didn't think enough about it, but why installing DIRAC inside the container?

**Comment by sfayer** [comment]
There is no reliable way to use the host version: It may be a different operating system (i.e. require a different externals/lcg bundle) and things may need to be relocated (singularity doesn't like bind mounting stuff inside of containers if the directory doesn't already exist, an installed DIRAC instance doesn't like being moved).

**Comment by fstagni** [comment]
I see you are proposing here a very generic solution, but at the end each VO will need to install at least a DIRAC extension. 

I again have little knowledge here, but can we mount a CVMFS repo inside a singularity container?

The PR itself could even be merged as it is now, as it affects no existing code. Would you prefer it merged?

**Comment by sfayer** [comment]
Generally yes, if the following conditions are met, CVMFS is available in the container:
 - CVMFS must be available on the host machine.
 - The container image must have a /cvmfs mount point built-in.

Yes, I think it would be good to merge it: It should be complete enough that it can be tested as a replacement for sudo on Vac/Vcycle.

Regards,
Simon

**Comment by fstagni** [comment]
Then fine for me, I just approved it. I don't think this can anyway be publicized until it's "operation" level.

**Pull request merged**
