### PR TITLE
[v6r14] Added CheckCECapabilities pilot command 

### PR DESCRIPTION
**Pull request by CinziaLu**
The dirac-get-ce-capabilities gets the ce tags.
Added the CheckCECapabilities pilot command to tag the CE in the VMs
case (no SiteDirector).

### CODE REVIEW

**Comment by fstagni** [comment]
@atsareg SiteDirectors may add this new command without the need to check beforehand the CE tags (and we can add this command everywhere)

**Comment by CinziaLu** [comment]
The dirac-get-ce-capabilities script is used by the CheckCECapabilities pilot command to retrieve the tags of the CE. 
E.g. It was added to give the possibility to use the CE Multiprocessor tag also in the case of VMs, however it can be used also by the SiteDirectors.

**Comment by atsareg** [comment]
The application of this command can conflict with the tags that are passed with the pilot by the SiteDirector. The tags can be defined on the CE and on the Queue level. I remind you that pilots are always running in a Queue ( or VM with a particular image ). This is a finer grain resource than a CE. Yes, the Queue is inheriting the CE tags, but it can have its own ones as well.

**Comment by atsareg** [comment]
If you will make another PR replacing this one, please, close this one

**Pull request closed without merging**
