### PR TITLE
[v7r0] Fix undefined variables in RabbitMQAdmin

### PR DESCRIPTION
**Pull request by chrisburr**
BEGINRELEASENOTES

*Core
FIX: Undefined variable error when RabbitMQAdmin fails to connect

ENDRELEASENOTES

### CODE REVIEW

**Comment by chrisburr** [comment]
The tests are failing as `joinedload_all` has been removed from SQLAlchemy 1.4. See also #5071.

**Comment by chaen** [comment]
This was actually fixed by you in 8d9747c6fd405aa4edde5702f16a5373d5dc459c
The problem here is that we are running the CI of an *old* version (v7r0) against master of DIRACOS. Is that really what we should be doing ?

**Comment by chrisburr** [comment]
> The problem here is that we are running the CI of an old version (v7r0) against master of DIRACOS. Is that really what we should be doing ?

This ties in to https://github.com/DIRACGrid/DIRACOS2/issues/30. IMHO we should be either:
* keeping all active branches of DIRAC functional with the latest DIRACOS
* splitting DIRACOS in to incompatible versions and document the mapping of minor DIRAC releases to minor DIRACOS releases (this would likely need a patch number adding to DIRACOS)

At some point we'll have breaking changes and SQLAlchemy 1.3 -> 1.4 might be a big enough migration that we want to calling breaking. Equally it's a hassle so maybe we'd rather just backport the fixes?

**Comment by chaen** [comment]
For this specific case, we could backport the fix, but I agree that a longer term solution should be considered. Let's continue the discussion on the issue you linked. In the meantime, do you want to backport the fixes or would you rather have me doing it ?

**Comment by chrisburr** [comment]
Done in https://github.com/DIRACGrid/DIRAC/pull/5089

**Review by fstagni — APPROVED** [review]

**Pull request merged**
