### PR TITLE
[v6r20] Mostly pylint fixes

### PR DESCRIPTION
**Pull request by fstagni**
BEGINRELEASENOTES

FIX: fixed pylint version to 1.6.5 (latest is broken)
NEW: added CODEOWNERS file

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
I have added a CODEOWNERS file to request code reviews from specified users. Doc in https://help.github.com/articles/about-codeowners/

It will be only for integration branch for now.

**Comment by fstagni** [comment]
I fixed the pylint version to 1.6.5 as last version is broken.

**Comment by phicharp** [comment]
I moved to 1.6.5 and now it gives me warnings when a variable is reused with a different type, like
```
lfns = set(lfns)
```
Shouldn't we disable this warning in the .pylintrc? or is it a code convention that we should not do that ever?

**Comment by fstagni** [comment]
Good question. I see that in newer versions of pylint `redefined-variable-type` is disabled by default, but I ignore the reason. What do other developers think?

**Comment by chaen** [comment]
I would disable it project wise.. 
It is true it *can* be dangerous, but well... we have so many places where we do that already... also, as Andre and Philippe said,  it takes less space in memory

**Comment by phicharp** [comment]
There are places where using different names would make the code much heavier, e.g. if a method argument can be of servers types, and a single type must be generated, avoiding code like
```
if isinstance(lfns, (dict, tuple)):
   lfns = list(lfns)
elif isinstance( lfns, basestring):
   lfns =[lfns]
```
would be more memory hungry as also if `lfns` is a list one would have to give it another reference... 
After all python is a non-typed language and this constraint breaks a bit this general rule, right?

Now, my question is: how do I disable this in the .pylintrc file? I found no rule / doc on the web...

**Comment by phicharp** [comment]
Found: in the MASTER section add

`disable=multiple_types`

**Comment by fstagni** [comment]
No, I think the correct way is in https://github.com/DIRACGrid/DIRAC/pull/3488/commits/a66a6b0b1bcfb0300f3957cf1da04e1a03214ae0 (in this PR)

**Comment by fstagni** [comment]
Yes I have put both.

**Comment by phicharp** [comment]
I tested what I advertised just above and it works well... Not clear too me whether the section matters, but I found in a doc (!) that it should be in [MASTER]

Now I have another problem, which is that pylint is pointing out some "Conventions" warnings but they don't show up in Eclipse, although they appear in the log of pylint (e.g. bad indentation on continuation line, bad while space...). In absence of pylint documentation as well as pydev doc, I'll go by trial and error! ;-)

**Comment by fstagni** [comment]
Review (still) OK?

**Comment by phicharp** [comment]
Review OK

**Pull request merged**
