### PR TITLE
[v6r16] Remove obsoleted DNs

### LINKED ISSUE #3130: v6r15 : VOMS2CSagent do not clean properly
If a user had 2 certificates in VOMS and in the DIRAC registry and you remove one entry in VOMS, the entry in DIRAC registry is not remove.

example with bkhanji:
    /C=DE/O=GermanGrid/OU=UniHeidelberg/CN=Basem Khanji
    /C=IT/O=INFN/OU=Personal Certificate/L=Milano Bicocca/CN=basem KHANJI

THE INFN one has been deleted in VOMS but the modification has not been propagated to DIRAC CS.

### PR DESCRIPTION
**Pull request by atsareg**
Remove user DNs which are no more in VOMS. Fixes #3130

### CODE REVIEW

**Comment by fstagni** [comment]
I guess it's OK but maybe @closier can comment on if this would be enough.

**Comment by closier** [comment]
It seems that if we remove DNs there is no notification in the log

**Comment by closier** [comment]
perhaps I should be more precise. In the mail received, there is no mention that a DN has been remove.

**Comment by closier** [comment]
In Fact if a user has 2 DNs in the CS but only one in VOMS, the "unknown" DN is not remove.
Still not working...

**Pull request merged**
