### PR TITLE
[v7r0] Remove direct access to SandboxMetadataDB in the SandboxStoreClient

### PR DESCRIPTION
**Pull request by atsareg**
SandboxStoreClient has got a problem with some recent update of the DIRACOS when MySQLdb module was added: it tries to import it and, if successful, it attempts to connect to the SandboxMetadataDB. If the db access is impossible, the connection takes several minutes to return with error and then the client proceeds with the service access. As a result suddenly the job submission with the command line became terribly slow. Looking at the code of the SandboxStoreClient, methods that are using direct db access are actually not used anywhere. Therefore, the direct db access and the methods that were using it are dropped in this PR. 

BEGINRELEASENOTES

*WorkloadManagement
CHANGE: SandboxStoreClient - remove direct access to SandboxMetadataDB

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
This looks like a similar problem as https://github.com/DIRACGrid/DIRAC/pull/4214

**Comment by phicharp** [comment]
PR #4214 was removing the direct DB access by default, thus why was there a problem still?

**Comment by atsareg** [comment]
The problem is that Dirac.submitJob() uses WMSClient which in turn instantiates SandboxStoreClient without smdb=False. Then submitJob() takes ages to execute. 

There is one place where the SandboxStoreClient is supposed to be used with direct access to the database - JobSanity executor, this one I have overlooked. If we have to keep direct db access inside the SandboxStoreClient, I would put smdb=False by default and JobSanity would explicitely set it to None.

**Comment by atsareg** [comment]
Replaced by #4594

**Comment by phicharp** [comment]
Sorry @atsareg, my mistake... I thought the default was False but indeed it is None which keeps the check...
I overlooked myself the fact that the WMSClient was instantiating `SandboxStoreClient`, otherwise I would have set it to False there, sorry!

**Pull request closed without merging**
