### PR TITLE
[v6r22] Fix bug in clinic handling

### PR DESCRIPTION
**Pull request by phicharp**
BEGINRELEASENOTES
*WMS
FIX: fix bug in finding the settings for Clinics in the hospital

ENDRELEASENOTES

### CODE REVIEW

**Comment by phicharp** [comment]
Yes, this is running as a hotfix in LHCb. I updated the LHCb documentation on hospital queues

**Comment by phicharp** [comment]
Sorry, I had forgotten to fix a small inconvenience in the system as the transformationID had to be in the `/Hospital/Transformations` option as well as in the `Hospital/Clinics/<clinic>/Transformations`
Should be enough to set in the the clinic now

**Comment by phicharp** [comment]
Have to find out why tests are now failing, not clear to me at all...

**Comment by chrisburr** [comment]
At a glance I guess you need to protect against `Hospital` not being defined in the CS?
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <DIRAC.TransformationSystem.Client.TaskManager.WorkflowTasks object at 0x7fa51cc63a10>

    def _getSickTransformations(self):

      """ Get the list of transformations to be processed at Hospital or Clinic

      """

      sickTrans = set(int(x) for x in self.opsH.getValue("Hospital/Transformations", []))

>     if "Clinics" in self.opsH.getSections("Hospital")['Value']:

E     KeyError: 'Value'

TransformationSystem/Client/TaskManager.py:828: KeyError
```

**Comment by phicharp** [comment]
> At a glance I guess you need to protect against `Hospital` not being defined in the CS?
> 
> ```
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <DIRAC.TransformationSystem.Client.TaskManager.WorkflowTasks object at 0x7fa51cc63a10>
> 
>     def _getSickTransformations(self):
> 
>       """ Get the list of transformations to be processed at Hospital or Clinic
> 
>       """
> 
>       sickTrans = set(int(x) for x in self.opsH.getValue("Hospital/Transformations", []))
> 
> >     if "Clinics" in self.opsH.getSections("Hospital")['Value']:
> 
> E     KeyError: 'Value'
> 
> TransformationSystem/Client/TaskManager.py:828: KeyError
> ```

This was also my guess but I was fooled by the fact that `getValue` returns a default value while `getSections` returns an error if the entry doesn't exist...

**Pull request merged**
