### PR TITLE
[V6r19] Tests, docs, pylints and bug fixes for RSS in v6r19

### PR DESCRIPTION
**Pull request by fstagni**
BEGINRELEASENOTES

*RSS
FIX: Bug fixes in scripts getting data out of DB
CHANGE: moved some integration tests from pytest to unittest

*WMS
FIX: Bug fix for correctly excluding WebApp extensions

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
review OK

**Comment by chaen** [comment]
The fix you put here is not enough for the problem on my PR I believe. I will add something in the Test_PathFinder to see if it helps

**Comment by fstagni** [comment]
Review anyone?

**Comment by fstagni** [comment]
@chaen the fix I put now should be enough

**Comment by chaen** [comment]
Review OK

**Pull request merged**
