### PR TITLE
[v7r3] fix: use correct environment for condor_rm

### PR DESCRIPTION
**Pull request by marianne013**
Previous version didn't use the proxy set by setproxy, so it always failed with an auth error.
BEGINRELEASENOTES

*Resources
FIX: HTCondorCE: make sure proxy is available when running condor_rm

ENDRELEASENOTES

### CODE REVIEW

**Comment by marianne013** [comment]
@andresailer This might also affect condor_status, it might be worth having a look.

**Comment by marianne013** [comment]
@fstagni @andresailer Would you mind having a look at that test failure, please ? I think the test doesn't quite work as it's meant to.

**Review by andresailer — COMMENTED** [review]
Otherwise looks fine to  me

**Comment by andresailer** [comment]
And it really does not produce errors with local schedd

**Review by fstagni — APPROVED** [review]

**Review by andresailer — APPROVED** [review]

**Pull request merged**
