### PR TITLE
Need to support file names using unicode

### PR DESCRIPTION
**Pull request by sposs**
This is a problem for me as my file names comes from a DB returning unicode. Also more generic.

### CODE REVIEW

**Comment by chaen** [comment]
Review OK. 
I think that for this particular case, it would be better to make one PR dedicated to replace the '== types.StringType' with isinstance(toto, basestring)

**Comment by fstagni** [comment]
v6r11...? :(

**Comment by sposs** [comment]
Yes, I know, Andrei said he would integrate it in a more recent version.
I'm waiting for him to close this.

**Comment by atsareg** [comment]
fixed in v6r14p3

**Pull request closed without merging**
