### PR TITLE
[v6r17] scripts for TransformationSystem certification "system tests"

### PR DESCRIPTION
**Pull request by fstagni**

### CODE REVIEW

**Comment by fstagni** [comment]
I have added function for getting the free and total disk space from SandboxStore (it was an error seen in certification).

**Comment by fstagni** [comment]
Review anyone?

**Comment by atsareg** [comment]
Review OK

**Comment by atsareg** [comment]
Conflicts in this branch please re-rebase it.

**Comment by fstagni** [comment]
Done

**Pull request merged**
