### PR TITLE
[v7r3] Backport: adapt mapper to sqlalchemy2.0

### PR DESCRIPTION
**Pull request by chrisburr**
Backport #6739 

BEGINRELEASENOTES

*DMS
CHANGE: adapt FTS3DB to sqlalchemy 2.0

*RMS
CHANGE: adapt ReqDB to sqlalchemy 2.0

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
the python2 tests are using an older version of sqlalchemy
```
    + sqlalchemy                                1.3.15  py27hdf8410d_1       conda-forge/linux-64       2MB
```

What a burden.... how about we kill DIRAC v7r3 with python2 in 3 weeks ? :-)

**Comment by chrisburr** [comment]
> What a burden.... how about we kill DIRAC v7r3 with python2 in 3 weeks ? :-)

It's been production ready for well over a year! 😉

**Comment by chaen** [comment]
oops, I had not realized that you opened that PR... I thought I already did to backport... anyway, I'm playing here with it, so if y ou don't mind, I'll close that one 
https://github.com/DIRACGrid/DIRAC/pull/6741

**Comment by fstagni** [comment]
> > What a burden.... how about we kill DIRAC v7r3 with python2 in 3 weeks ? :-)
> 
> It's been production ready for well over a year! wink

I am afraid we need to hang in there for a few more months

**Pull request closed without merging**
