### PR TITLE
[v6r18] Add option to clear PYTHONPATH on pilot start

### PR DESCRIPTION
**Pull request by sfayer**
Hi,

While testing GFAL2, we've found that the PYTHONPATH setting from the base worker-node software (at some sites, mainly ones that use it from CVMFS) causes DIRAC to load the wrong gfal2 library at runtime and segfault (when instantiating the GFAL2_SRM2 plugin for example). This patch adds an option to the pilot to clear the PYTOHNPATH at the start of the dirac-pilot.py which fixes this problem. (I wonder if this should actually be the default behaviour: It seems unlikely that the PYTHONPATH from the WN will ever have anything useful to DIRAC on it).

Regards,
Simon

### CODE REVIEW

**Comment by chaen** [comment]
Which version ? We have seen it too, but it was fixed by that: https://github.com/DIRACGrid/DIRAC/pull/3264

**Comment by fstagni** [comment]
In any case, I have a generic comment: as we have a "Pilot 3.0" repository, all changes in DIRAC/WMS/Pilot (which is so-called "Pilot 2.0") should also be ported to https://github.com/DIRACGrid/Pilot until Pilot 3 becomes the standard.

**Comment by sfayer** [comment]
We see the problem with v6r18p0 and newer versions of v6r17: I haven't tested it directly but I think #3264 actually introduced the problem we see (as PYTHONPATH is no longer cleared).

**Comment by fstagni** [comment]
Right now the pilot uses the PYTHONPATH set from the bashrc file, which is created via dirac-install. If this doesn't work then the problem is elsewhere. I may be missing something, but why do we need to clear the PYTHONPATH that we just created?

**Comment by sfayer** [comment]
We don't... This patch clears it right at the beginning before the DIRAC bashrc has even been created. The problem is that without the patch, you get the following environment for the job agent:
PYTHONPATH=<DIRAC_top_level>:<WN_python_path>
LD_LIBRARY_PATH=<DIRAC_externals>:<WN_libraries>

When the gfal2 module is loaded, it searches the PYTHONPATH first, so it finds the gfal2.so from <WN_python_path> and segfaults.

With this patch enabled you get the following env:
PYTHONPATH=<DIRAC_top_level>
LD_LIBRARY_PATH=<DIRAC_externals>:<WN_libraries>

Then when the gfal2 module is searched for it doesn't find it on PYTHONPATH, so it moves on to LD_LIBRARY_PATH and finds it in DIRAC_externals: Then everything works correctly.

**Comment by fstagni** [comment]
A-ha it's clear now, sorry I was not paying enough attention. I am even in favor of doing this by default, without the need for the flag. Would you see a problem with that?

**Comment by chaen** [comment]
I'd also be in favor of it

**Comment by sfayer** [comment]
I don't expect doing this by default would cause any problems, so I've enabled it and inverted the meaning of the flag. I'll put a pull request with a similar patch in the Pilot repo.

**Pull request merged**
