### PR TITLE
[v6r20] Bad merge

### PR DESCRIPTION
**Pull request by chaen**
BEGINRELEASENOTES
*TS
FIX: bad merge when porting
ENDRELEASENOTES

### CODE REVIEW

**Comment by atsareg** [comment]
You have chosen the wrong line, next time the beautification will touch it again

**Comment by chaen** [comment]
Oups, thanks. Changed

**Comment by andresailer** [comment]
How about merging this now, so the other PRs for integration stop failing because of this problem.

(Also next auto formatting will touch this line anyway because the whitespace after the opening parenthesis in the preceding line.)

**Comment by fstagni** [comment]
Correct, merging now.

**Comment by chaen** [comment]
Btw, any idea how one should do to have travis run when there is a push being done ? The propagation of changes from one branch to the other is not going through a PR, so it is not tested.

**Comment by chaen** [comment]
In fact it is ran, but nt displayed anywhere.
I corrected it here: https://github.com/DIRACGrid/DIRAC/pull/3556

**Pull request merged**
