### PR TITLE
[v6r14] Better error reporting (affecting jobs application status)

### PR DESCRIPTION
**Pull request by fstagni**

### CODE REVIEW

**Comment by phicharp** [comment]
Should be against v6r14 and not Integration ;-)

**Comment by atsareg** [comment]
Why all these gLogger errors ? These are utility classes mostly, the errors should be reported by the callers.

**Comment by phicharp** [comment]
... and using DError()

**Comment by fstagni** [comment]
sorry sorry I meant to open against v6r14 indeed. That's why no DError

**Comment by atsareg** [comment]
I strongly disagree with this PR. gLogger should not be used in the tools but in the agents using the tools with a proper identity. Remember also that gLogger.error() messages are also sent to the System Logging. They should always be split into a static and variable part.

**Comment by fstagni** [comment]
Andrei, I opened another PR with the same content targeted to v6r14 (this one was wrong opened towards integration). 

Regarding your comment: 
- all the gLogger.error messages I introduced are split into the static and the variable part
- these utilities were doing things like
```python
return S_ERROR( "Cannot write to file %s :%s" % ( fileName, str( e ) ) )
```
which leads to the fact that the return message can be something like
"Cannot write to file False :[Errno 28] No space left on device: '/tmp/dirac/tmp4v_C4e'"
which becomes impossible to handle client side (how do you split between "error code" - the "static" part - and the the details - the "variable" part?)

So it is better to return:
```python
return S_ERROR( "Cannot write to file" )
```
but this means that the details on what went wrong are lost.

- So, to know what happens, I've put the details in the logging.

**Comment by atsareg** [comment]
Can the use of DErrno help here ?

**Comment by fstagni** [comment]
Yes. This PR is for v6r14, so no DError here. But the idea is exactly to use DError for such cases from v6r15 on.

**Comment by atsareg** [comment]
Then it should be better deferred to v6r15, I think.

**Comment by fstagni** [comment]
The problem is, for example, that as of today the JobDB is storing a lot of crappy "ApplicationStatus" like the string above. This makes searching into it painful.

**Comment by atsareg** [comment]
Why an arbitrary error message goes directly to the Application Status ? This is not a logging mechanism. I am not sure I understand the case you want to solve. Can you please detail it a bit ?

**Comment by fstagni** [comment]
I didn't reconstruct the full trace, anyway I think that for the specific case I was saying few messages before, it is due to the "executeWithUserProxy" decorator, as used within StorageManagerClient.getFilesToStage() by the JobSchedulingExecutor.

**Pull request closed without merging**
