### PR TITLE
[v7r2] Add FTS3 archive monitoring feature and plugin based FTS activity 

### PR DESCRIPTION
**Pull request by chaen**
@atsareg please use DIRACOS v1r27 once this PR is merged

BEGINRELEASENOTES

*DMS
CHANGE: FTS DB change (see https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-v7r2#new-status-for-fts3-files-and-jobs)
NEW: enable FTS archive monitoring
NEW: allow to use FTS activity based on FTS3Plugin

*RMS
CHANGE: ReplicateAndRegister prefers disk replicas

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
I am building DIRACOS v1r27 containing the latest FTS version

**Comment by chaen** [comment]
DIRACOS v1r27 is ready, so is this PR

**Comment by andresailer** [comment]
This  need a DB update, because the various states are SQL enums, right?

**Comment by chaen** [comment]
> This need a DB update, because the various states are SQL enums, right?

RIGHT ! I' forgot it in the desc, I add it now and in the wiki, thanks

**Review by andresailer — APPROVED** [review]

**Pull request merged**
