### PR TITLE
[v6r20] Add JEncode for json serialization

### PR DESCRIPTION
**Pull request by chaen**
This PR contains all the code necessary to perform JSON serialization enhanced with datetime and custom types.
I added a doc about the serialization in general.
Tests are updated as well.

This code is still not used anywhere. It will be enabled progressively. 
Future PRs to come.

@andresailer @petricm : you guys are the doc experts. I desperately tried to add a link to the code documentation (using `:py:mod`) but miserably failed. Any hint ? Thanks

BEGINRELEASENOTES
*Core
NEW: JEncode for json based serialization
ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
where did you try to add a link to what exactly?

**Comment by chaen** [comment]
There is the CodeDocumentation section which is generated with automodule. I wanted to put a link in my rst file to the class documentation of JSerializable

**Comment by andresailer** [comment]
I think this should work
```
:py:class:`~DIRAC.Core.Utilities.JEncode.JSerializable`
```
:py:mod: is for modules (e.g., JEncode), there is also :any:

**Comment by chaen** [comment]
I tried all this, but it does not work :-/
I run makeDocs.sh, and then `make html`, but then the following code:
```
BEFORE class
.. :py:class:`~DIRAC.Core.Utilities.JEncode.JSerializable`

BEFORE mod
.. :py:mod:`~DIRAC.Core.Utilities.JEncode`

BEFORE any
.. :any:`~DIRAC.Core.Utilities.JEncode

```

outputs simply

```
BEFORE class .. JSerializable

BEFORE mod .. JEncode

BEFORE any .. :any:`~DIRAC.Core.Utilities.JEncode
```

**Comment by andresailer** [comment]
makeDocs.sh is the old script, MakeDoc.py is the new one. 
In the docs folder just run
```
READTHEDOCS=True make html
```
which will also call MakeDoc.py

**Comment by chaen** [comment]
:'( :'(

```
[chaen@pceplbc04 dirac]$ cat DIRAC/docs/README 
How to build DIRAC documentation
=================================

1. Create DIRAC client environment by an appropriate
   source bashrc

2. Go to the Tools directory of the DIRAC source code repository
   cd DIRAC/docs/Tools

3. Run the documentation building script
   ./makeDocs.sh
```

OK, I will try your recipe, thanks. I'll also update the doc.  
From what I can see, we should always want this READTHEDOC variable to True no ? Shouldn't we make it default ?

**Comment by chaen** [comment]
Thanks ! I've upated the README.

**Comment by chaen** [comment]
No courageous people to review ? :)

**Comment by rajanandakumar** [comment]
It will all work out of the box, I am sure  :)

**Pull request merged**
