### PR TITLE
[v7r2] Include microsecond precision in asctime in MessageQueueBackend

### PR DESCRIPTION
**Pull request by chrisburr**
When poking around in the elastic search logging I found myself being confused by messages appearing out of order due to the timestamps being identical at the millisecond level. I think it would be nicer to send the full microsecond precision timestamp.

BEGINRELEASENOTES

*Resources
CHANGE: asctime now includes microsecond precision when using the MessageQueueBackend for logging

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
this somehow relates to https://github.com/DIRACGrid/DIRAC/issues/5320
Frankly, I do not see the need for microsecond precision, not even milliseconds. All the latency and jitter we have are (at least) at the second level. So going below that does not make any sense

**Comment by chrisburr** [comment]
> All the latency and jitter we have are (at least) at the second level. So going below that does not make any sense

I disagree, for the logging the microsecond timestamp is very useful for ensuring the ordering of the lines can be reconstructed.

**Comment by fstagni** [comment]
There are conflicting requirements here, on one side ChrisB wants microseconds precision, and ChrisH wants seconds precision only.

Since "in medio stat virtus", I'd stay with milliseconds, which is the default.

**Comment by chrisburr** [comment]
This change only affects the message queue based logging backend and has no effect on the other uses of elasticsearch so I don't see how Chris's point is relavent, unless I misunderstand how the elastic monitoring works?

**Comment by chaen** [comment]
After discussion: conclusion is that this is fine with the understanding that the only effect is that it will guarantee consistency for a given service on a given host. 
Btw, does it need a change on ES index definition ?

**Review by chaen — APPROVED** [review]

**Comment by chrisburr** [comment]
>  Btw, does it need a change on ES index definition ?

No, it's a string and the logstash config is set up such tat it only indexes `@timestamp` at the second level. At some point we should redo the indices as they're very sub-optimal at the moment.

**Pull request merged**
