### PR TITLE
[v7r2/integration] aiming for a clean environment

### PR DESCRIPTION
**Pull request by marianne013**
We are trying to make the environment less intrusive for users. 
We are aware that this is a major change in approach, but we think it will be worth it in the long term. 
We created this as a draft, so we can discuss it at BiLD meeting.
-- Simon & Daniela

BEGINRELEASENOTES
*Core
CHANGE: Split environment in bashrc to make it more user friendly.
ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Hi, can you please rebase?

**Comment by marianne013** [comment]
Hi Federico, I thought it was decided we couldn't do it this way ? Cheers, Daniela

**Comment by fstagni** [comment]
I honestly don't remember... can you rebase anyway?

**Comment by fstagni** [comment]
Ah, yes I am maybe starting to remember. Do you still want to discuss this or is it a case closed on your side? If this is the case, that we close this PR.

**Comment by marianne013** [comment]
Hi Federico, 
it looks like some of this has already been merged in a different request, so I am going to close it for now.
Daniela

**Pull request closed without merging**
