### PR TITLE
[v6r15] new dfc client rebase

### PR DESCRIPTION
**Pull request by chaen**
Implements all the methods of the FileCatalog on the client side, with doc and default args

### CODE REVIEW

**Comment by phicharp** [comment]
I have a general concern: some of these methods are not specified in the FileCatalog abstraction... This is not really nice as in principle one should not have to know what is the actual implementation. Code should not depend on extensions, right?
However the PR looks OK, but this is really a problem with file catalogs...

**Comment by atsareg** [comment]
Do we really need rpc and url arguments in each method and not just in the constructor ? What is the use case ? Some catalogs will not be able to implement the same arguments.

**Comment by chaen** [comment]
Philippe, we already have this problem with the metadata method... it' true that we should have a nicer solution. I will think of it.

Andrei, that's the only way to specify a longer timeout for a single call.

**Comment by atsareg** [comment]
Timeout is fine. Do you need rpc and url arguments to specify the timeout ?

**Comment by chaen** [comment]
sorry, I answered too fast. No, it's probably good enough in the constructor. I will correct

**Comment by chaen** [comment]
modified according to your remark Andrei

**Pull request merged**
