### PR TITLE
[8.0] More FTS3DB perf improvments  

### PR DESCRIPTION
**Pull request by chaen**
BEGINRELEASENOTES

*DMS
CHANGE: FTS3DB uses `in` instead of `not in` for some query
CHANGE: FTS3DB removal of operations uses python datetime instead of mysql builtin

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
@marianne013 @andresailer something fishy with the `comdirac` documentation ?

```
  diracdoctools.Utilities:    ERROR: Error when runnning command python /home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/6864/src/DIRAC/Interfaces/scripts/dcd.py -h: 'Traceback (most recent call last):\n  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/6864/src/DIRAC/Interfaces/scripts/dcd.py", line 10, in <module>\n    from DIRAC.Interfaces.Utilities.DCommands import DSession\n  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/6864/src/DIRAC/Interfaces/Utilities/DCommands.py", line 580, in <module>\n    def sessionFromProxy(config=DConfig(), sessionDir=None):\n  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/6864/src/DIRAC/Interfaces/Utilities/DCommands.py", line 152, in __init__\n    self.bootstrapFile()\n  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/6864/src/DIRAC/Interfaces/Utilities/DCommands.py", line 157, in bootstrapFile\n    os.mkdir(self.configDir)\nFileExistsError: [Errno 17] File exists: \'/home/docs/.dirac\'\n'
  ```

**Comment by marianne013** [comment]
Just spoke to Simon, comment was "this is terrible code" and "I have no idea how to fix it", before starting to mumble about "None"s. But why does this show up now and not when it was first merged ?

**Comment by marianne013** [comment]
@sfayer I guess the documentation gets build (partially) by running the commends with the -h option ?

**Comment by marianne013** [comment]
We now think this is a race condition (too many shorthand commands issued at once) and that's why we never saw it. Do you have permissions to just rerun it to see if it works ?

**Comment by chaen** [comment]
> one does not simply re-run readthedocs...

Unfortunately can't be rerun, I will add another commit to trigger it. 
On the medium term, how can it be fixed ?

**Comment by andresailer** [comment]
I triggered a doc rebuild

**Comment by andresailer** [comment]
> one does not simply re-run readthedocs...

Fake news :trumpet:

**Comment by andresailer** [comment]
E.g.: https://readthedocs.org/projects/dirac/builds/19641493/
image

Though once clicked, the "rebuild..." disappears

**Comment by marianne013** [comment]
@andresailer Can I get the magic "trigger rebuild" ability as well :-) ?

**Comment by chaen** [comment]
me too me too :-)

**Review by fstagni — APPROVED** [review]

**Pull request merged**
