### PR TITLE
[v6r20] Add isSameSE method to StorageElement 

### PR DESCRIPTION
**Pull request by chaen**
Part of https://github.com/DIRACGrid/DIRAC/issues/3908
@phicharp can you have a look please ? 

BEGINRELEASENOTES

*Resources
NEW: Add isSameSE method to StorageElement which works for all protocols

*TransformationSystem
CHANGE: use SE.isSameSE

ENDRELEASENOTES

### CODE REVIEW

**Comment by phicharp** [comment]
Looks fine with me... 
I only find it strange to have it as a method of StorageElement as it is a binary test. I would have put it maybe in DMSHelpers...

**Comment by chaen** [comment]
Well I implemented there because I related it to the `==` operator. But I may change it.

**Comment by phicharp** [comment]
Good point, yes indeed this is pretty much `==`

**Comment by phicharp** [comment]
We can also put a binary function in `DMSHelpers` that calls that one ;-)

**Pull request merged**
