### PR TITLE
[v7r0] misleanous... misclenaous... miscallenous... various fixes

### PR DESCRIPTION
**Pull request by chaen**
A collection of various fixes

BEGINRELEASENOTES
*Docs
CHANGE: allow release notes to be empty in dirac-docs-get-release-notes

*Tests
FIX: DataManager tests check VO dynamically

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
@chrisburr is this the error your PR was supposed to fix ?

**Comment by chrisburr** [comment]
Nope, I've seen this a few times today:
```
2020-04-21 12:23:13 UTC dirac-install [NOTICE]  Installing DIRAC OS master...
2020-04-21 12:23:13 UTC dirac-install [DEBUG] Using DIRACOS tarball URL from configuration key Installations/DIRAC/DIRACOS
2020-04-21 12:23:13 UTC dirac-install [NOTICE]  Retrieving https://diracos.web.cern.ch/diracos/releases/diracos-master.tar.gz
2020-04-21 12:23:13 UTC dirac-install [DEBUG] Retrieving remote file "https://diracos.web.cern.ch/diracos/releases/diracos-master.tar.gz"
2020-04-21 12:23:27 UTC dirac-install [NOTICE]  Retrieving https://diracos.web.cern.ch/diracos/releases/diracos-master.md5
2020-04-21 12:23:27 UTC dirac-install [DEBUG] Retrieving remote file "https://diracos.web.cern.ch/diracos/releases/diracos-master.md5"
2020-04-21 12:23:28 UTC dirac-install [ERROR] Oops... md5 for package master failed!
```
(looking into the other one)

**Comment by chaen** [comment]
ah I did not even see the DIRACOS issue ! I was just looking at the Elastic problem

**Comment by chrisburr** [comment]
Not sure about this one...maybe a race in the test? It already has a 1 second sleep for some reason, maybe it needs to poll a few times?
```
 ServerInstallDIR/DIRAC/tests/Integration/WorkloadManagementSystem/Test_ElasticJobDB.py::test_setAndGetJobFromDB FAILED [100%]

=================================== FAILURES ===================================
___________________________ test_setAndGetJobFromDB ____________________________

    def test_setAndGetJobFromDB():
      res = elasticJobDB.setJobParameter(100, 'DIRAC', 'dirac@cern')
      assert res['OK']
      time.sleep(1)
    
      res = elasticJobDB.getJobParameters(100)
      assert res['OK']
>     assert res['Value'][100]['DIRAC'] == 'dirac@cern'
E     KeyError: 'DIRAC'

ServerInstallDIR/DIRAC/tests/Integration/WorkloadManagementSystem/Test_ElasticJobDB.py:24: KeyError
----------------------------- Captured stdout call -----------------------------
Inserting data in jobelasticdb:JobParameters
{'Name': 'DIRAC', 'Value': 'dirac@cern', 'JobID': 100}
Indexing jobelasticdb/JobParameters with {'Name': 'DIRAC', 'Value': 'dirac@cern', 'JobID': 100}, id=100DIRAC
JobDB.getParameters: Getting Parameters for job 100
=========================== 1 failed in 2.09 seconds ===========================
```

**Comment by chaen** [comment]
Yeah probably. It seem to have been added on purpose: f227053342
I'll increase the delay

**Comment by chrisburr** [comment]
`dirac-install` doesn't check the return code when downloading files and it seems like EOSWeb is unhappy at the moment and randomly returning 403 Forbidden now and again:
```
772188cf1ee02d70f9145dd4dcfeb5ff
772188cf1ee02d70f9145dd4dcfeb5ff
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /diracos/releases/diracos-master.md5
on this server.</p>
</body></html>
772188cf1ee02d70f9145dd4dcfeb5ff
772188cf1ee02d70f9145dd4dcfeb5ff
772188cf1ee02d70f9145dd4dcfeb5ff
772188cf1ee02d70f9145dd4dcfeb5ff
772188cf1ee02d70f9145dd4dcfeb5ff
772188cf1ee02d70f9145dd4dcfeb5ff
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /diracos/releases/diracos-master.md5
on this server.</p>
</body></html>
772188cf1ee02d70f9145dd4dcfeb5ff
772188cf1ee02d70f9145dd4dcfeb5ff
```

**Comment by chrisburr** [comment]
> Yeah probably. It seem to have been added on purpose: [f227053](https://github.com/DIRACGrid/DIRAC/commit/f227053342b61e5023cd0882537b0bdfabebbf49)
> I'll increase the delay

How about using this rather than always slowing down the tests:
```python
# Keep retrying in case the index is slow to update
for i in range(30):
    time.sleep(0.5)
    res = elasticJobDB.getJobParameters(100)
    assert res['OK']
    if res['Value'][100]['DIRAC'] == 'dirac@cern':
        break
else:
    raise ValueError(res)
```

**Comment by chrisburr** [comment]
I bet this is the same error with it returning a 403:
```
2020-04-21 13:01:34 UTC dirac-install [NOTICE]  Destination path for installation is /home/dirac/ServerInstallDIR
2020-04-21 13:01:34 UTC dirac-install [DEBUG] Defaults for Projects/DIRAC are in http://diracproject.web.cern.ch/diracproject/dirac.cfg
2020-04-21 13:01:34 UTC dirac-install [DEBUG] Processing dependencies for DIRAC:v7r0p21
2020-04-21 13:01:34 UTC dirac-install [DEBUG] Releases file is http://diracproject.web.cern.ch/diracproject/tars/release-DIRAC-v7r0p21.cfg
2020-04-21 13:01:34 UTC dirac-install [DEBUG] Retrieving remote file "http://diracproject.web.cern.ch/diracproject/tars/release-DIRAC-v7r0p21.cfg"
2020-04-21 13:01:35 UTC dirac-install [DEBUG] Retrieving remote file "http://diracproject.web.cern.ch/diracproject/tars/release-DIRAC-v7r0p21.md5"
2020-04-21 13:01:35 UTC dirac-install [NOTICE]  {u'DIRAC': {u'sourceUrl': u'/home/dirac/LocalRepo/ALTERNATIVE_MODULES/DIRAC', u'Version': u'local'}}
2020-04-21 13:01:35 UTC dirac-install [NOTICE]  Discovering modules to install
2020-04-21 13:01:35 UTC dirac-install [NOTICE]  Installing modules...
2020-04-21 13:01:35 UTC dirac-install [NOTICE]  Using local copy for source: /home/dirac/LocalRepo/ALTERNATIVE_MODULES/DIRAC
2020-04-21 13:01:36 UTC dirac-install [NOTICE]  Executing: mv /home/dirac/ServerInstallDIR/DIRACRepo /home/dirac/ServerInstallDIR/DIRAC
2020-04-21 13:01:36 UTC dirac-install [NOTICE]  Deploying scripts...
Scripts will be deployed at /home/dirac/ServerInstallDIR/scripts
Inspecting DIRAC module
2020-04-21 13:01:36 UTC dirac-install [NOTICE]  Installing DIRAC OS master...
Traceback (most recent call last):
  File "/home/dirac/ServerInstallDIR/dirac-install.py", line 2647, in <module>
    if not installDiracOS(releaseConfig):
  File "/home/dirac/ServerInstallDIR/dirac-install.py", line 2354, in installDiracOS
    diracos, diracOSVersion = releaseConfig.getDiracOSVersion(cliParams.diracOSVersion)
AttributeError: 'NoneType' object has no attribute 'getDiracOSVersion'
+ echo 'ERROR: dirac-install.py failed'
+ exit 1
ERROR: dirac-install.py failed
```

**Comment by chaen** [comment]
I've asked the EOS guys.

For the retry we could yes. I've already pushed another commit, let see if it helps

**Comment by fstagni** [comment]
Still WIP? Looks all OK to me.

**Comment by chaen** [comment]
yes I removed the WIP flag

**Pull request merged**
