### PR TITLE
[v7r1] arc.Endpoint doesn't accept unicode in ARCComputingElement

### PR DESCRIPTION
**Pull request by chrisburr**
BEGINRELEASENOTES

*Resources
FIX: Initialisation of arc.Endpoint in ARCComputingElement

ENDRELEASENOTES

Fixes the error seen in the hackathon but I think there is no reason not to backport to v7r0:

```
2020-10-29 10:10:12 UTC WorkloadManagement/SiteDirector ERROR: Agent exception while calling method <bound method SiteDirector.execute of <SiteDirector.SiteDirector object at 0x7f243c394e50>>
Traceback (most recent call last):
  File "/opt/dirac/pro/DIRAC/Core/Base/AgentModule.py", line 344, in am_secureCall
    result = functor(*args)
  File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 459, in execute
    result = self.submitPilots()
  File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 579, in submitPilots
    res = self._submitPilotsToQueue(pilotsToSubmit, ce, queueName)
  File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 856, in _submitPilotsToQueue
    submitResult = ce.submitJob(executable, '', pilotSubmissionChunk)
  File "/opt/dirac/pro/DIRAC/Resources/Computing/ARCComputingElement.py", line 225, in submitJob
    "org.nordugrid.gridftpjob")
  File "/opt/dirac/pro/diracos/usr/lib64/python2.7/site-packages/arc/compute.py", line 376, in __init__
    this = _compute.new_Endpoint(*args)
NotImplementedError: Wrong number of arguments for overloaded function 'new_Endpoint'.
  Possible C/C++ prototypes are:
    Arc::Endpoint(std::string const &,std::set< std::string,std::less< std::string >,std::allocator< std::string > > const &,std::string const &)
    Arc::Endpoint(std::string const &,std::set< std::string,std::less< std::string >,std::allocator< std::string > > const &)
    Arc::Endpoint(std::string const &)
    Arc::Endpoint()
    Arc::Endpoint(std::string const &,Arc::Endpoint::CapabilityEnum const,std::string const &)
    Arc::Endpoint(std::string const &,Arc::Endpoint::CapabilityEnum const)
    Arc::Endpoint(Arc::ExecutionTarget const &,std::string const &)
    Arc::Endpoint(Arc::ExecutionTarget const &)
    Arc::Endpoint(Arc::ComputingEndpointAttributes const &,std::string const &)
    Arc::Endpoint(Arc::ComputingEndpointAttributes const &)
    Arc::Endpoint(Arc::ConfigEndpoint const &)
```

### CODE REVIEW

**Comment by fstagni** [comment]
That's fine but I would check if there's a newer library on `arc` side.

**Comment by chrisburr** [comment]
It looks like there is a patch release but it doesn't contain any relevant changes. ARC6 probably fixes the issue (and is used by DIRACOS2) but I'm not sure anyone is motivated to add it to DIRACOS1.

**Comment by chaen** [comment]
I started having a look at arc6 because of xroot 5 but I agree with @chrisburr that this fix is the path of least resistance

**Comment by fstagni** [comment]
BTW: here the target branch is `integration`, but in the title you wrote `[v7r0]`. I think it can go to `integration`

**Comment by chrisburr** [comment]
It's based on `rel-v7r0` so it can be safely changed to `rel-v7r0` or `rel-v7r1`. I was targetting the oldest branch as I'm not entirely sure where it comes from (my best guess is JEncode if that's enabled) and it should be safe regardless. That said, you can adjust the target/title as you see fit.

**Review by fstagni — APPROVED** [review]

**Review by atsareg — APPROVED** [review]

**Pull request merged**
