### PR TITLE
[v7r0] M2Crypto: force bio free and shutdown when closing

### PR DESCRIPTION
**Pull request by chaen**
Requires M2Crypto >= 0.36, which is in DIRACOS v1r13

BEGINRELEASENOTES
*Core
FIX: M2Crypto: force bio free and shutdown when closing
ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Seems like there are some conflicts among packages.

**Comment by chrisburr** [comment]
The issue is the conda-forge doesn't support Python 2.7 or OpenSSL 1.0.0 anymore so getting a 2 day old version of M2Crypto doesn't work. It's fixable but we might be happier using pip for M2Crypto until we get Python 3.

**Comment by atsareg** [comment]
I will merge it as the test failures are irrelevant here

**Comment by chrisburr** [comment]
The test failures are very relevant, `pip install M2Crypto` fails to compile M2Crypto. I'll make a PR.

**Pull request merged**
