### PR TITLE
[v6r14] TransformationPlugin: Need to pass parameters to utils

### PR DESCRIPTION
**Pull request by andresailer**
As far as I can see the parameters for PluginUtilities are never set.
Without setting the params things like GroupSize are otherwise only taken from the default or the CS and not from individual transformations.

### CODE REVIEW

**Comment by phicharp** [comment]
You are right, this was forgotten by whoever ported all this from LHCbDIRAC to DIRAC... We have exactly that method in TransformationPlugin of LHCbDIRAC...

**Comment by phicharp** [comment]
There is also the following line that you may want to add:
    self.transID = params['TransformationID']

**Comment by phicharp** [comment]
Review OK

**Comment by andresailer** [comment]
the 
```python
self.transID = params['TransformationID']
```
is done in the PluginUtilities.setParameters function https://github.com/DIRACGrid/DIRAC/blob/rel-v6r14/TransformationSystem/Client/Utilities.py#L93
I don't find transID in TransformationPlugin itself. So that is not necessary, right?

**Comment by phicharp** [comment]
Right... It';s just that in LHCbDIRAC we need it ;-) but you are right it is not used in the base class...

**Pull request merged**
