### PR TITLE
[v7r3] Python 3 server installation improvements

### PR DESCRIPTION
**Pull request by chrisburr**
The main change here is to support versioned installations similarly to Python 2 based DIRAC installations. The main difference is:
* The `versions/` folder contains paths which include the architecture, e.g. `versions/v7.3.0a13-1624274835/Linux-x86_64`
* Non-versioned server installations are not supported (at least for the system administrator, future k8s based installations could choose not to)
* `UseVersionsDir` in the local configuration is now ignored for Python 3, instead it is implied by the current directory structure. It's a little ugly but I think it's nicer than relying on the CS having been loaded properly for `DIRAC.rootPath` to be set.
* ~~The `pro` "symlink" is a file when pointing to a Python 3 installation and contains a string like `v7.3.0a13-1624274835`. This allows a single "pro link" to be independent of CPU architecture as the directory is something like: `versions/$(cat pro)-$(uname -m)`~~ This point has been removed as suggested in https://github.com/DIRACGrid/DIRAC/pull/5215#issuecomment-869486563

I don't think any of this is worthy of release notes.

### CODE REVIEW

**Comment by fstagni** [comment]
Just :
```
+ pycodestyle --diff
./src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py:14:121: E501 line too long (128 > 120 characters)
./src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py:15:121: E501 line too long (129 > 120 characters)
./src/DIRAC/__init__.py:141:5: E121 continuation line under-indented for hanging indent
```

**Review by fstagni — DISMISSED** [review]

**Comment by TaykYoku** [comment]
Given the need for a path to the site-package working directory for nginx, from the discussion [#485](https://github.com/DIRACGrid/WebAppDIRAC/issues/485)..
If I understand correctly, `DIRACOS2` is installed with each new release and this is the only case when the link path will change. Why not create a symlink on `site-package` in /opt/dirac each time you install `DIRACOS2`? am i missing something?

**Comment by atsareg** [comment]
If the version directory is of the form versions/$(cat pro)/$(uname -m) then the single "pro link" can be still a link which is easier to manage I think.

**Comment by chrisburr** [comment]
`/opt/dirac/pro/$(uname -s)-$(uname -m)`

**Review by fstagni — APPROVED** [review]

**Pull request merged**
