### PR TITLE
[v6r13] Modify SiteDirector.py to correctly configure jobExecDir and httpProxy

### PR DESCRIPTION
**Pull request by yujikato**
We have tested this modification works for a Belle II SSH site.

### CODE REVIEW

**Comment by fstagni** [comment]
Hi, thanks for this. Where would you like this PR to be merged? v6r13 maybe?

**Comment by atsareg** [comment]
I will merge it in v6r13, it is a bugfix patch

**Comment by yujikato** [comment]
Yes, please merge it in v6r13.

**Comment by fstagni** [comment]
@yujikato for next time, if you want a PR to be merged in a release branch: 
- be sure that, when creating the PR, the release branch is the target.
- for commodity, write in the title the branch where you are asking the PR to be merged.

Thanks.

**Comment by atsareg** [comment]
Integrated into v6r13p6

**Pull request closed without merging**
