### PR TITLE
feat: Add jobGroup to job parameters

### PR DESCRIPTION
**Pull request by arrabito**
BEGINRELEASENOTES

* Workload
CHANGE: add jobGroup to job parameters

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
Or https://github.com/DIRACGrid/DIRAC/pull/7592 broke our labeler-action config?

**Comment by fstagni** [comment]
> Or #7592 broke our labeler-action config?

Indeed. I hope I fixed it now, please rebase.

**Comment by fstagni** [comment]
> > Or #7592 broke our labeler-action config?
> 
> Indeed. I hope I fixed it now, please rebase.

Please rebase.

**Comment by arrabito** [comment]
Should I do something? 
Can you please specify?

**Comment by fstagni** [comment]
Just rebase this PR with

```
git fetch upstream
git checkout addJobParam
git rebase upstream/rel-v8r0
git push upstream --force addJobParam
```

**Review by fstagni — APPROVED** [review]

**Pull request merged**
