### PR TITLE
[v6r15] Move of (integration) tests from the TestDIRAC repository

### PR DESCRIPTION
**Pull request by fstagni**
As announced in the google developer forum.

### CODE REVIEW

**Comment by chaen** [comment]
I now have tests to commit for v6r14. How am I supposed to proceed ?

**Comment by atsareg** [comment]
These are integration tests that used to be in TestDIRAC package. I guess you mean tests in the systems code. Those ones stay in the same place, so you can just commit them as usual

**Comment by chaen** [comment]
I know, but I have tests to commit in TestDIRAC

**Comment by atsareg** [comment]
I think you have to commit them both to TestDIRAC and to v6r15 branch of DIRAC

**Comment by fstagni** [comment]
Exactly: commit in both. Sorry about that, but I didn't think it would have been necessary to play with git-merge for the tests.

**Comment by chaen** [comment]
okay fine, so could this PR be merged rapidly then so we don't lose tests ?

**Comment by chaen** [comment]
that waw quick :D thanks

**Pull request merged**
