### PR TITLE
[8.0] change (Production): change column types in ProductionDB

### PR DESCRIPTION
**Pull request by arrabito**
BEGINRELEASENOTES
Thank you for writing the text to appear in the release notes. It will show up
exactly as it appears between the two bold lines

Please follow the template:
* Production System
CHANGE: change column types in ProductionDB from VARCHAR(255) to LONGTEXT
ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Such change would need to be advertised in https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-8.0

**Comment by arrabito** [comment]
Yes I will do it as soon as the PR is merged.

**Comment by fstagni** [comment]
Seems like you'll need to adapt: 

```
2023-03-07 15:37:03 UTC dirac-install-db [139752727328576] ERROR: Failed to initialize Database MySQL Error ( 1131 : Execution failed.: ( 1101: BLOB, TEXT, GEOMETRY or JSON column 'InputQuery' can't have a default value ))
7686
```

**Comment by arrabito** [comment]
Just done. 
Could you please point me where did you get the error message from the logs of the CI? I was not able to find it.
Thank you.

**Comment by fstagni** [comment]
It was in the Integration tests, prob in https://github.com/DIRACGrid/DIRAC/actions/runs/4355790795

**Comment by arrabito** [comment]
ok thank you. I saw it but I hadn't found the exact line. Thanks again.

**Review by fstagni — APPROVED** [review]

**Pull request merged**
