### PR TITLE
[v7r3] Backport OpenSSL 3 support

### PR DESCRIPTION
**Pull request by chrisburr**
Leaving as draft until this has been tested in certificiation with v8.0.x

BEGINRELEASENOTES

*Core
NEW: Support OpenSSL 3.0.x

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
Tested OK with python 3. Would be worth checking with python 2 if somebody still has an instance running python 2 ? @andresailer @marianne013  ?

**Comment by andresailer** [comment]
I will not have 7.3 run with python 2

**Comment by marianne013** [comment]
We don't have python 2 here either.

**Comment by chaen** [comment]
OK, then last potential people would be @hmiyake @iueda and @zhangxiaomei 
Otherwise, good to go

**Comment by zhangxiaomei** [comment]
We are running with python3 only

**Comment by hmiyake** [comment]
Could you give us a couple of days? My initial test on client showed positive result but we would test the code on our certification server.

**Comment by chrisburr** [comment]
> Could you give us a couple of days? My initial test on client showed positive result but we would test the code on our certification server.

That's fine, I doubt we'll be releasing anything until the new year.

**Comment by hmiyake** [comment]
This patch is working well on our v7r3 python2 environment. Please go ahead.

**Review by fstagni — APPROVED** [review]

**Pull request merged**
