### PR TITLE
[8.0] Tornado log fixes

### PR DESCRIPTION
**Pull request by chaen**
Fixes https://github.com/DIRACGrid/DIRAC/issues/6363

BEGINRELEASENOTES
*Core
FIX: Tornado components are initialized using the Tornado system section
FIX: each Tornado handler reads its own log level

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
@martynia what did your tests conclude ?

**Comment by martynia** [comment]
I tried to cherry-pick your changes. This did not work, since my Dirac version is v7r3, and your changes are not compatible with it, so I don't have a setup I could verify your fix.

**Comment by chaen** [comment]
Then how am I supposed to know if it fixes your issue ? :-) 
It's pretty straightforward to backport (juste use `TornadoService` instead of `BaseRequestHandler`), but I won't do it in the PR, because I don't want that to go in a production release

**Comment by martynia** [comment]
I have v8.0.5, so I cherry picked 2 commits:

On 30 Nov 2022, at 10:54, Daniela Bauer <daniela.bauer.grid@googlemail.com> wrote:

2022-11-30 10:52:25 UTC WebApp/RootHandler ERROR: Error in initialization KeyError('csPaths') 
ERROR:tornado.application:Uncaught exception 
Traceback (most recent call last): 
 File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/http1connection.py", line 238, in _read_message 
   delegate.finish() 
 File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/httpserver.py", line 319, in finish 
   self.delegate.finish() 
 File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/routing.py", line 256, in finish 
   self.delegate.finish() 
 File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/web.py", line 2195, in finish 
   self.execute() 
 File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/web.py", line 2214, in execute 
   self.handler = self.handler_class(self.application, self.request, 
 File "/opt/dirac/diracos/lib/python3.9/site-packages/tornado/web.py", line 194, in __init__ 
   self.initialize(**kwargs) 
 File "/opt/dirac/DIRAC/src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py", line 522, in initialize 
   res = self.__initialize(self.request) 
 File "/opt/dirac/DIRAC/src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py", line 475, in __initialize 
   logLevel = cls.srv_getCSOption("LogLevel", "INFO") 
 File "/opt/dirac/DIRAC/src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py", line 846, in srv_getCSOption 
   for csPath in cls._componentInfoDict["csPaths"]: 
KeyError: 'csPaths'

**Comment by chaen** [comment]
It would definitely help if you gave more context to your log snippet :-) 

I assume it works with the rest, but not with the web app ? It is because this is empty

https://github.com/DIRACGrid/DIRAC/blob/aacea350a6751d3fa167c9c76283ed0ee5da4c60/src/DIRAC/Core/Tornado/Server/TornadoREST.py#L258-L264

Now, why is this empty is a good question...

**Comment by martynia** [comment]
I can confirm, that the logging level selection works per Tornado handler:

`2022-12-06 11:27:18 UTC Tornado/Tornado/TornadoPilotLoggingHandler INFO: Handler initialised ...
2022-12-06 11:27:18 UTC Tornado/Tornado/TornadoPilotLoggingHandler DEBUG: with a dict:  {'serviceName': 'WorkloadManagement/TornadoPilotLogging', 'serviceSectionPath': '/Systems/WorkloadManagement/Devel/Services/TornadoPilotLogging', 'csPaths': ['/Systems/WorkloadManagement/Devel/Services/TornadoPilotLogging'], 'URL': 'https://diractest.grid.hep.ph.ic.ac.uk:8444/WorkloadManagement/TornadoPilotLogging'}`

And as we said in the meeting, it breaks the Web UI. The bit in `TornadoREST.py` looks unfinished. Definitely the docs are ahead of the code ;-)

**Comment by chaen** [comment]
@martynia please try again.
I wanted to add something meaningful in `TornadoREST` but I am not entirely sure what/how. So I have a workaround for the moment.

**Comment by martynia** [comment]
OK, I'll try to cherry-pick those 3 committees again and see what happens.

**Comment by martynia** [comment]
OK, your last commit keeps the Dirac UI alive.

**Review by fstagni — APPROVED** [review]

**Pull request merged**
