### PR TITLE
[v7r0] allow DIRAC extension to extend Properties

### PR DESCRIPTION
**Pull request by chaen**
Addresses https://github.com/DIRACGrid/DIRAC/issues/4077

BEGINRELEASENOTES
*Core
NEW: allow to extend Properties in DIRAC extensions

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Without looking the details, why not using the ObjectLoader?

**Comment by chaen** [comment]
It's the usual bootstrap issue. 

But it is true that we start having this at various places. We could consider having a raw `ObjectLoader` which does not import anything from DIRAC.

**Comment by fstagni** [comment]
I let @atsareg approve, IMHO this is fine.

**Comment by atsareg** [comment]
I am wondering if it is at all needed - the Property module ? It is just defining some other names for the group properties adding no extra logic. What is the use case ? If somebody needs to define a new property to be used in the rules of access to certain services, then this can be just done in the CS alone without registering this new properties in the Properties module.

**Comment by chaen** [comment]
https://github.com/DIRACGrid/DIRAC/issues/4077 has been here for 3 months, it's a pity that no one bothered commenting before I put the work in it :(

Now more concretely `then this can be just done in the CS alone`. Can you explain how ? I never saw this possibility, and I think @marianne013 either, since she asked for that feature

**Comment by atsareg** [comment]
I was asking this question for a long time. I will check if what I said above is true and then it will be enough to just document that.

**Comment by atsareg** [comment]
I checked once again, just to be sure, that any string in the configuration used as a group property on one hand and valid property in the Authorization section of a service on the other hand works as expected without the need to be registered in the Properties. This module is just defines constants with properties, nothing more. This is a good practice in principle but not in the case where you have to add new properties more dynamically, e.g. in extensions. The use of actual property strings in the code works the same way. So, I would suggest that extensions just use simple hard-coded strings for specific properties. And we keep Properties module for "core" properties as a good style of programming.

**Comment by chaen** [comment]
Why not giving the possibility to have good style of programming in the extension ? it does not cost much in my opinion, and it's much better (also from the documentation point of view)

**Comment by atsareg** [comment]
Well, I do not object to that. I just want to say that if somebody needs to add a new property for some service Authorization section it does not depend at all on the existence of the extension specific Properties module. We use sometimes property names in the code though. There, it is better to use constants.

**Comment by andresailer** [comment]
Given what Andrei describes, is it really necessary to do the import into the DIRAC Properties Module?
Is it not enough to just have a module in the extension and import a constant from the extension Properties module when it is used? 

I think I also had some confusion about these things in the past because there are the nice CONSTANTS (NORMAL_USER) usable in the code, but you have to use the string values `NormalUser` in the CS.

**Comment by atsareg** [comment]
I agree with André. If an extension defines a new property, it will be used only in this extension. So, it would be natural to define the corresponding constant in the extension Properties module. But there is no point to import it into the core Properties as no core mechanism relies on its presence.

**Comment by chaen** [comment]
Ok so if I understand properly what you are saying:
* You can just define an arbitrary name in the CS for a property, and that will work out of the box
* if that property name needs to be used in the extension, the extension can define their own `Properties.py` ? 

If yes, then it does make sense to me and I am happy with that.
Then please document it.

And people please, in the future, react to issues if you have the answer already :D

**Comment by atsareg** [comment]
I think we can close this one. And yes, let's react more promptly to the issues

**Pull request closed without merging**
