### PR TITLE
[v6r20] GetReleaseNotes: add --repo option

### PR DESCRIPTION
**Pull request by andresailer**
BEGINRELEASENOTES

*Docs
NEW: add --repo option, e.g. --repo DiracGrid/DiracOS, or just --repo DiracOS, fixes DIRACGrid/DIRACOS#30

ENDRELEASENOTES

```
$ ./GetReleaseNotes.py  -r DIRACGRID/diracos --branches=master --openPRs
[master]

NEW: (#29) requirements.txt copied from DIRAC
CHANGE: (#29) allow to have pipRequirements a URL or a file
```

### CODE REVIEW

**Comment by atsareg** [comment]
Very nice. I suggest also to add the repo name to the generated notes to see that this is not from the DIRAC project. e.g.:
    FIX: (DIRACOS #12345) release note text... 

./GetReleaseNotes.py  -r DIRACGRID/diracos  -> will it work ? Is it case insensitive ? Shouldn't be ./GetReleaseNotes.py  -r DIRACGrid/DIRACOS ?

**Comment by chaen** [comment]
Thanks ! 

@atsareg The idea is to use this script against the DIRACOS repo to put release notes in there directly, so I am not sure we want the repo name printed

**Comment by atsareg** [comment]
I see. But I would be happy to include those notes also to the related DIRAC overall release. We do not do it now (not so many reasonable cases but still, WebApp, Pilot, now DIRACOS), which is pity. For the moment these packages are released without notes at all although they are supposed to be release together with the DIRAC  project combo.

**Comment by chaen** [comment]
Hum, it's a bit delicate in the sense that the releases are decoupled. When would you put the release notes regarding VMDIRAC in DIRAC ? When the release of VMDIRAC is done, or when you start using it in DIRAC ? 
In the same way, we do not write the change log of the external libraries.
I would be in favour though of linking the external release notes when we do change version though. 
For example when releasing dirac vXYZ, in the changelog there could be a line saying

`use of DIRACOS UVW: link to changelog`

**Comment by atsareg** [comment]
VMDIRAC, WebAppDIRAC are always released together with DIRAC. Pilot or DIRACOS might be different although not necessarily. So, for the former it makes perfect sense, for the latter it does not harm.

**Comment by chaen** [comment]
No, it does not harm. But when will you put them in ?

**Comment by andresailer** [comment]
Re https://github.com/DIRACGrid/DIRAC/pull/3762#issuecomment-407032000: The group and repository is case insensitive.

We could set up readthedocs pages for all projects, which could be not much more than the release notes, then the pages get automatically created and one can link to them without much problem.

**Comment by atsareg** [comment]
I can merge the release notes by hand in the first place if they exist in the PRs using this tool. In this case, the notes will be also available via an html URL that can be linked from the documentation pages.

I agree with André that setting up readthedocs for all the packages would be very good. The docs can be organized similarly to the DIRAC one. I was thinking how this can be merged into just one docs web page but this is virtually impossible. So, having separate linked readthedocs projects is the only reasonable solution.

**Comment by atsareg** [comment]
In any case, I am merging tis PR now. We can continue discussion further.

**Pull request merged**
