### PR TITLE
[Integration] Use GitHub Container registry due to pull limit on dockerhub

### PR DESCRIPTION
**Pull request by petricm**
BEGINRELEASENOTES
*tests
FIX: Use GitHub Container registry due to pull limit on dockerhub

ENDRELEASENOTES

### CODE REVIEW

**Comment by petricm** [comment]
I don't get it why the tests was cancelled

**Comment by chrisburr** [comment]
I think it happens occasionally when the CI worker node goes offline. I've retried for now to see if it's a one-off

**Comment by petricm** [comment]
The fail here has nothing to do with the content of this PR

**Review by fstagni — APPROVED** [review]

**Comment by fstagni** [comment]
This can also be merged...

**Pull request merged**
