### PR TITLE
[v6r22] Add preamble attribute in SSHBatchComputingElement

### PR DESCRIPTION
**Pull request by aldbr**
BEGINRELEASENOTES
*Resources
FIX: preamble attribute was missing in SSHBatchComputingElement causing an error in _submitJobHost() 

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
@atsareg this looked like a bug, or simply we didn't understand what `preamble` is for.

**Comment by atsareg** [comment]
Thanks for the fix. It should rather be:

self.preamble = self.ceParameters.get('Preamble', '')

And you do not need then the comment in the line above

**Comment by atsareg** [comment]
And the fix can go to v6r22

**Comment by aldbr** [comment]
Alright, it should be okay now

**Pull request merged**
