### PR TITLE
[v6r15] Make sure DataStoreclient.commit does not throw exception

### PR DESCRIPTION
**Pull request by chaen**
To fix https://github.com/DIRACGrid/DIRAC/issues/2416

### CODE REVIEW

**Comment by chaen** [comment]
It says it has merging conflict, but I really don't see why though....

**Comment by atsareg** [comment]
I think this is because I am merging PRs now and your branch is in conflict with one of those just merged

**Comment by atsareg** [comment]
I will add this one by hand when preparing the release

**Comment by chaen** [comment]
ah ok thanks, I reopen then

**Comment by atsareg** [comment]
Added to v6r15, closing here

**Pull request closed without merging**
