### PR TITLE
Add url for new method

### PR DESCRIPTION
**Pull request by closier**
Add the url for certificates service

### CODE REVIEW

**Comment by chaen** [comment]
Review OK

**Comment by atsareg** [comment]
I guess you want it for rel-v6r13

**Comment by closier** [comment]
I want for rel-v6r12 and v6r13 and it seems I did it wrong.. sorry

**Comment by atsareg** [comment]
Make it for the earliest desirable
      release
      
        Andrei
      
      On 02/04/15 15:15, Joel Closier wrote:
    
    
      I want for rel-v6r12 and v6r13 and it seems I did it wrong..
        sorry
      —
        Reply to this email directly or view
          it on GitHub.

**Pull request closed without merging**
