### PR TITLE
[WIP] Using JSON for (un)marshalling

### PR DESCRIPTION
**Pull request by FlorentNKada**
CHANGE: In multiple places - whenever DEncode.decode() is called, removed the "_stubLength" argument, because DEncode.decode() now returns one single data structure and not a tuple  anymore. Also, removed the "[0]" when we tried to get the first member of a tuple returned by DEncode.decode().

*Core
CHANGE: DEncode.py kept the same name, to preserve its calls in DIRAC, but the file is now completely different. All the (un)marshalling now uses JSON protocol.

### CODE REVIEW

**Comment by phicharp** [comment]
You should give a title starting with the targeted version of Dirac, and [WIP] as this is highly work in progress.

Also please edit the release notes which are just a placeholder (i.e. set the system and explain the changes... In the title you should just give the topic, like

[WIP] [v6r20] Use JSON for (un)marshaling 

and give more details in the comments "RELEASENOTES"

Note that some checks have failed!!!  Please look at them, but before you should rebase your branch with Integration of DIRAC: it says it is out of date

**Comment by chaen** [comment]
There is definitely something wrong with this PR. YOu must have rebased on a integration branch from the beginning of your internship. Please fetch first, and then rebase.

**Comment by chaen** [comment]
Also, it was agreed to have a separate module to do the json (un)marshalling, so you should not overwrite the DEncode module this way.

Finally, did you write some docs and unit tests ? I can't find them, there are too many modified files.

**Comment by fstagni** [comment]
I close this PR for now with the idea of replacing it with something up-to-date (and without conflicts) in the future.

**Pull request closed without merging**
