### PR TITLE
[8.0] Add command to complete productions

### PR DESCRIPTION
**Pull request by alicefaure**
BEGINRELEASENOTES

*Production
NEW: add dirac-prod-complete command

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Hi Alice,
thank you for your first PR. The content looks fine, I will review later. But, in order to target 8.0 release series, you should move (rebase) the target branch to `rel-v8r0` instead of `integration`.

**Comment by chrisburr** [comment]
Rebasing wasn't quite what was needed as it means you've kept contents of `integration` in this branch. Something like this should work the way that was intended:

```bash
# Reset the current state to that of upstream/rel-v8r0
# WARNING: This command is destructive so make sure you don't have any unpushed changes
git reset --hard upstream/rel-v8r0
# "cherry pick" the commits that have now been lost
git cherry-pick bbca6a9 828af09
# We now need to force push as we've re-written the history
git push -u origin complete_prod -f
```

**Review by fstagni — APPROVED** [review]

**Comment by fstagni** [comment]
The issues with readthedocs compilation do not seem related to this PR @andresailer

**Comment by andresailer** [comment]
Indeed the warnings should be unrelated

```
WARNING: autodoc: failed to import module 'EC2Endpoint' from module 'DIRAC.Resources.Cloud'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 62, in import_module
    return importlib.import_module(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/6401/src/DIRAC/Resources/Cloud/EC2Endpoint.py", line 6, in <module>
    import boto3
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/client.py", line 17, in <module>
    from botocore import waiter, xform_name
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/utils.py", line 34, in <module>
    import botocore.httpsession
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

WARNING: autodoc: failed to import module 'S3Storage' from module 'DIRAC.Resources.Storage'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 62, in import_module
    return importlib.import_module(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/6401/src/DIRAC/Resources/Storage/S3Storage.py", line 25, in <module>
    import boto3
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/client.py", line 17, in <module>
    from botocore import waiter, xform_name
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/utils.py", line 34, in <module>
    import botocore.httpsession
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dirac/conda/6401/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

**Pull request merged**
