### PR TITLE
[v7r3] removals and deprecations

### PR DESCRIPTION
**Pull request by fstagni**
BEGINRELEASENOTES

*Core
CHANGE: removed dirac-agent, dirac-service, dirac-executor scripts

*WMS
CHANGE: removed StatesMonitoringAgent (use StatesAccountingAgent agent instead)

ENDRELEASENOTES

### CODE REVIEW

**Comment by petricm** [comment]
On a related topic, can we start to have the branch `rel-v7r2` even if it is the same as integration for the moment being.

**Comment by andresailer** [comment]
I think you meant to remove the StatesAccountingAgent (dumps to MySQL), and keep the StatesMonitoringAgent (dumps to elasticsearch)?

**Comment by fstagni** [comment]
No, I really meant to remove the StatesMonitoringAgent. This is a followup of https://github.com/DIRACGrid/DIRAC/pull/4905 where I have added to StatesMonitoringAgent the possibility to commit to ES.

**Comment by andresailer** [comment]
> No, I really meant to remove the StatesMonitoringAgent. This is a followup of #4905 where I have added to StatesMonitoringAgent the possibility to commit to ES.

I see, yes, see the comment for the docs in #4905 why I might have been confused about which agent should stay. , also the quoted phrase is still confusing :) and the ReleaseNotes need flag -> agent?

**Review by atsareg — APPROVED** [review]

**Pull request merged**
