### PR TITLE
[v6r15] enable google style docstrings

### PR DESCRIPTION
**Pull request by andresailer**
As asked in https://github.com/DIRACGrid/DIRAC/pull/2976#discussion_r66408006
Need to enable this extension: http://www.sphinx-doc.org/en/stable/ext/napoleon.html
Also changed some docstrings to make that work (I am guessing on the types, correct me if they are wrong).
Cf.:
Before:
http://diracsailer.readthedocs.io/en/rel-v6r15/CodeDocumentation/Core/Security/X509Chain.html#DIRAC.Core.Security.X509Chain.X509Chain.generateProxyToFile
After:
http://diracsailer.readthedocs.io/en/docgoogledoc/CodeDocumentation/Core/Security/X509Chain.html#DIRAC.Core.Security.X509Chain.X509Chain.generateProxyToFile

### CODE REVIEW

**Comment by chaen** [comment]
Great !! Thanks André !!

**Comment by atsareg** [comment]
Review OK

**Comment by andresailer** [comment]
I accidentally removed this branch before it was merged. Sorry for that

**Comment by fstagni** [comment]
Doc only, merging directly

**Pull request merged**
