### PR TITLE
[v7r0] Hackathon: Don't use SEs in Error state for testing

### PR DESCRIPTION
**Pull request by chrisburr**

### CODE REVIEW

**Comment by andresailer** [comment]
Can you also fix that in the other test scripts in the same folder?

**Comment by chaen** [comment]
Please do the PR against v7r0 branch

**Comment by chrisburr** [comment]
Changing the target branch confused the formatting test into failing but this PR only touches bash scripts so it's not relevant.

**Comment by atsareg** [comment]
Review OK ?

**Pull request merged**
