### PR TITLE
[v6r13] Missing import stat

### PR DESCRIPTION
**Pull request by calancha**
import stat was missing.

### CODE REVIEW

**Comment by chaen** [comment]
review ok

**Comment by andresailer** [comment]
This doesn't work. DirectoryListing was moved to a different module, except for some additions that were not incorporated there.
Sadly Andrei just fixed this merge conflict in v6r14.

**Comment by calancha** [comment]
Its required for instance to list:
With patch:
```
ls -ltrH /ilc/user/c/calanchac
drwxrwxr-x 0 calanchac ilc_user   0.0B 2013-01-19 14:54:04 data
drwxrwxr-x 0 calanchac ilc_user   0.0B 2013-02-13 08:58:21 stdhep
drwxrwxr-x 0 calanchac ilc_user   0.0B 2013-07-08 00:59:07 input
drwxrwxr-x 0 calanchac ilc_user   0.0B 2013-07-26 09:10:51 processors
drwxrwxr-x 0 calanchac ilc_user   0.0B 2014-07-24 07:52:35 examples
drwxrwxr-x 0 calanchac ilc_prod   0.0B 2014-10-29 11:24:57 tests
-rwxrwxr-x 1 calanchac ilc_prod   7.0B 2015-11-17 07:53:32 test10
-rwxrwxr-x 1 calanchac ilc_prod 129.0B 2015-11-17 08:08:51 test4
-rwxrwxr-x 1 calanchac ilc_prod   6.0B 2015-11-17 08:39:11 test5
-rwxrwxr-x 1 calanchac ilc_prod   5.0B 2015-11-17 08:39:11 test1
-rwxrwxr-x 1 calanchac ilc_prod 203.0B 2015-11-17 08:39:12 test3
-rwxrwxr-x 1 calanchac ilc_prod   6.0B 2015-11-17 08:39:13 test8
-rwxrwxr-x 1 calanchac ilc_prod 9.9KiB 2015-11-17 08:39:15 test2
```

W/o patch:

```
ls -ltrH /ilc/user/c/calanchac
FC:/> Error: global name 'stat' is not defined
```

**Comment by andresailer** [comment]
I am saying that your PR is not complete. DirectoryListing (the thing the merge conflict marker enclose) needs to be removed from the FileCatalogClientCLI.py file and the additions need to move to the DirectoryListing module, that is imported at the top of FIleCatalogClientCLI. All this was done in some merge into v6r14 so you would only create a new set of merge conflicts.

**Comment by calancha** [comment]
I see, thank you. In that case Andrei is the right person to fix this problem.

**Pull request closed without merging**
