### PR TITLE
[v6r12] GlobusComputingElement: count waiting pilots in the system

### PR DESCRIPTION
**Pull request by andresailer**
As there is no command for Globus, we just count the pilots in the dirac system

I don't know if anybody else is using this, and if this should also go into v6r11?

### CODE REVIEW

**Comment by atsareg** [comment]
Argh! Do you need it for v6r12 ? The PR is against v6r12, I did not noticed that

**Comment by andresailer** [comment]
Yes I need this for v6r12.

**Comment by andresailer** [comment]
(I don't need it for v6r11 if you meant that, I moved to v6r12)

**Comment by andresailer** [comment]
Ohh, this PR was against integration, that is what you meant?

**Comment by atsareg** [comment]
Yes, but I have cherry-picked the commit to v6r12

**Comment by andresailer** [comment]
Ok, great. Thanks

**Pull request merged**
