### PR TITLE
[v6r14] Disable indentation a multiple of four from pep8

### PR DESCRIPTION
**Pull request by petricm**
We should actually add some pep8 configuration file into the branch, but for now only this.

### CODE REVIEW

**Comment by chaen** [comment]
Can't we, instead of disabling it, give it a value of 2 ?

**Comment by petricm** [comment]
Sadly no. As far as I understand pep8, you only have an option to check for multiple of 4 or don't check (it doesn't believe that 2 is an option). pep8 is less configurable than pylint where you can specify indent string. But I would be happy if somebody proves me wrong.

**Comment by petricm** [comment]
To clarify:
E111 	indentation is not a multiple of four
E114 	indentation is not a multiple of four (comment)

http://pep8.readthedocs.io/en/latest/intro.html

**Comment by fstagni** [comment]
Review OK...

**Pull request merged**
