### PR TITLE
[v6r15] Pilot run dir

### PR DESCRIPTION
**Pull request by CinziaLu**
Using PilotRunDirectory as WorkingDirectory, if available at the CE level in the CS. 
Requested at the issue #2746

### CODE REVIEW

**Comment by fstagni** [comment]
Review OK.

**Comment by andresailer** [comment]
Changing the ```self.workingDirectory``` like this will make the SiteDirector Agent write to that folder, that is not the goal of #2746, is it?

**Comment by fstagni** [comment]
Ah, you are actually correct, thanks for pointing it out! Indeed it should change `pilotExecDir`

**Comment by CinziaLu** [comment]
Fixed, thanks @andresailer .
I got confused by this "it already exists a "WorkDirectory" parameter that does this job" :)

**Comment by fstagni** [comment]
Review OK

**Pull request merged**
