### PR TITLE
[v6r19] DOC: point README to master and add badges for integration

### PR DESCRIPTION
**Pull request by chaen**
BEGINRELEASENOTES
*Documentation
CHANGE: point README to master and add badges for integration
ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Merging straight away.

**Comment by fstagni** [comment]
Oh, I merged and looking now I realized that this was done towards the master branch. It should have been done to rel-v6r19, otherwise it won't be merged to integration, and since you are there please remove the last pointer to v6r17 (it is for landscape, which we don't run anymore)

**Comment by chaen** [comment]
Sorry, I am not sure what you want me to do now ? Cherry pick this, put it in v6r19, and remove the landscape badges, and make a new PR against v6r19 ?

**Comment by fstagni** [comment]
Make new PR. Sorry about that.

**Pull request merged**
