### PR TITLE
[v6r21] Document pit export

### PR DESCRIPTION
**Pull request by chaen**
@iueda @hmiyake  once this is merge, maybe you could add a few lines about your setup here too ? 

BEGINRELEASENOTES

*Docs
NEW: document methods for pit export

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
"pit", and "online" and "offline" are not necessarily concept common to everyone. Can you make it more generic?

**Comment by chaen** [comment]
pit -> experiment site ?
`Online` and `offline` I don't really see. Isn't it generic ? I've heard it in all the cases I came across.

**Comment by chaen** [comment]
I replaced 'pit' with other words, but I failed at finding alternatives for Online and Offline

**Comment by andresailer** [comment]
:+1: 

Also very interesting for test beams

**Pull request merged**
