### PR TITLE
[v7r1] DFC: remove SEPrefix, VOPath, VOPrefix, ResolvePFN and SEDefinition from the DFC

### PR DESCRIPTION
**Pull request by chaen**
The SE management has nothing to do in the DFC, as discussed already a long time.
So I remove it, and do what I said in the ticket https://github.com/DIRACGrid/DIRAC/issues/4227

BEGINRELEASENOTES

*DMS
CHANGE: remove all the SE mangling in the DFC (SEPrefix, resolvePFN, SEDefinition)

ENDRELEASENOTES

### CODE REVIEW

**Comment by atsareg** [comment]
This is fine. Just to be checked that we are nowhere relying on the availability of the PFN in the output of the FC.getReplicas() call

**Comment by chaen** [comment]
the PFN stored in the catalog will be left untouched so it's still there if needed

**Comment by marianne013** [comment]
I'm trying to understand the logic, but can't quite work it out yet.
How is the VOPath handled now ?

**Comment by chaen** [comment]
It is still handled in the `StorageElement` as it was https://github.com/DIRACGrid/DIRAC/blob/integration/Resources/Storage/StorageFactory.py#L367
That means if you instantiate a `StorageElement` where the `VOPath` is configured, the `VOPath` will be used in place of `Path`.
What changes in this PR is that none of this mangling is done anymore in the `FileCatalog`, because it should never have been done in a first place.

**Comment by marianne013** [comment]
It's probably OK, though I don't have any time to test it right now.

**Comment by atsareg** [comment]
The output of the FileCatalog CLI "replicas" command will not print out URLs of the file replicas, it will just print out the SE name and LFN instead of a URL. Is it acceptable ? In principle in most cases it is enough to know in which SE the file resides. And also just one possible URL was printed out. So, it looks OK, may be others have a different idea ?

**Comment by chaen** [comment]
I think it will print the URL that the catalog stores. At least that what it should be doing. 
Again, if mangling with path is needed, the client should use the `StorageElement` object, or even better, the `DataManager` class. 
This btw is inline with https://github.com/DIRACGrid/DIRAC/issues/1335

**Pull request merged**
