### PR TITLE
[v6r19]Fix serialization of FTSJob

### PR DESCRIPTION
**Pull request by chaen**
BEGINRELEASENOTES
Please follow the template:
*DataManagementSystem
FIX: fix the serialization of 0 values for FTSJob
ENDRELEASENOTES

### CODE REVIEW

**Comment by phicharp** [comment]
Do you really want it for Integration, not v6r17?

**Comment by phicharp** [comment]
Please add targeted version in the title

**Comment by chaen** [comment]
Oups, thanks for the title.
I targeted v6r19 because this problem only showed up with the latest mysql version, which we willo nly officially support from v6r19. But indeed, the bug is present before. So whoever merges can decide where it should go.

**Comment by fstagni** [comment]
I tried to change the base to rel-v6r17 and it messes up the PR, so let's stick to v6r19.

**Pull request merged**
