### PR TITLE
copying pilot.cfg if py2 and not reinstalling

### PR DESCRIPTION
**Pull request by fstagni**

### CODE REVIEW

**Comment by atsareg** [comment]
IS it to fix the validation PR ? The same error occurs for the Python3 integration test as well

**Comment by chrisburr** [comment]
I don't understand this PR and I'm fairly sure it's wrong

**Comment by chrisburr** [comment]
I think the test is buggy because it doesn't provide a `pilot.cfg` file rather than the copying of the `pilot.cfg` file being the issue. I don't think there is any valid situation why a Python 3 pilot (i.e. Pilot 3) would be running without it?

**Comment by fstagni** [comment]
Yes but does it need to be copied over?

**Comment by atsareg** [comment]
Can you please conclude on that ? Formally the tests are passing now

**Comment by chrisburr** [comment]
Maybe not, you probably know better than me.

I thought the `pilot.cfg` be used to override the setup or other bits of configuration that should also be applied to the inner CE's dirac installation?

**Comment by fstagni** [comment]
So, ma and @chrisburr talked a bit and concluded that this bit was never tested, so it's probably a fault of the test. I will provide in some minutes a fix.

**Pull request merged**
