### PR TITLE
[v7r0] only pass protocols parameter to getTransportURL in executeMethod

### PR DESCRIPTION
**Pull request by chaen**
This should address https://github.com/DIRACGrid/DIRAC/issues/4088

Before:
```
Traceback (most recent call last):
  File "/tmp/testSE.py", line 6, in <module>
    print StorageElement('CERN-USER').getFileMetadata('/lhcb/user/c/chaen/zozo.xml', protocols='root')
  File "/opt/dirac/DIRAC/Resources/Storage/StorageElement.py", line 1234, in __executeMethod
    res = fcn(urlsToUse, *args, **kwargs)
TypeError: getFileMetadata() got an unexpected keyword argument 'protocols'
```
And after, it just returns the metadata

BEGINRELEASENOTES
*Resources
FIX: SE __executeMethod: only pass protocols parameter to getTransportURL

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
Do you also want to apply this in the StageMonitorAgent?

**Comment by atsareg** [comment]
I merge it now but please answer André's question

**Comment by chaen** [comment]
I think this was the idea yes. At the same time. But since it is working now, and we anyway plan to get ride of it, is it worth it ?

**Comment by andresailer** [comment]
Do you mean getting rid of the StageMonitorAgent?

It is find by me to keep the configuration as it is for now. Then we can close #4088 ?

**Comment by chaen** [comment]
Yes, and replace it with FTS. 

I guess yes if you agree

**Pull request merged**
