### PR TITLE
[v6r12] Improved ls in dirac filecatalog.

### PR DESCRIPTION
**Pull request by calancha**
Supported short and long options.
Accept separated/joined short options: '-lt' or '-l' '-t'.

Allow list ordering by file size (-S, --sizeorder).
Support on listing in human readable format (-h, --human-readable).

### CODE REVIEW

**Comment by atsareg** [comment]
Have you tried the dls command of the COMDIRAC extension ? Please, try it out and let's see how this developments can profit from each other

**Comment by calancha** [comment]
Sorry for my ignorance but i dont know what is COMDIRAC. Could you give me one link to check such thing?

**Comment by sposs** [comment]
Hi Tino,
You can install COMDIRAC like any other dirac extension, by adding -e
COMDIRAC to the dirac-install call. Then you'll have the d* commands. The
COMDIRAC extension page on github https://github.com/DIRACGrid/COMDIRAC will
give you info about it.

Cheers,
S Poss

Le lun. 26 oct. 2015 à 11:08, Tino Calancha <notifications@github.com> a
écrit :

**Comment by calancha** [comment]
Thank you very much Stephan. I am very interested to try it.

**Comment by calancha** [comment]
See the PR:
https://github.com/DIRACGrid/DIRAC/pull/2678
https://github.com/DIRACGrid/COMDIRAC/pull/42

I have modified the human readable short option from '-h' to
'-H' to avoid conflicts with the Script help.
The pull request if for the integration branch. I have tested locally
with the branch v010, which is the one i have download: it seems
working to me, hope the integration branch work also fine.

**Comment by calancha** [comment]
Closing this PR because it is superseded by PR 2678.

**Pull request closed without merging**
