### PR TITLE
[DRAFT][v8.0] Refactor JobDB.SubmitJob

### PR DESCRIPTION
**Pull request by chaen**
BEGINRELEASENOTES
Thank you for writing the text to appear in the release notes. It will show up
exactly as it appears between the two bold lines

Please follow the template:
*Subsystem
NEW/CHANGE/FIX: explanation

For examples look into release.notes

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
This is a somewhat large refactoring, any specific reason for targeting rel-v8r0 and not integration?
Also, there will almost certainly conflicts when applying this to integration branch.

**Comment by chaen** [comment]
I'll mark it as draft for now

**Comment by atsareg** [comment]
To make reviewing easier - can you please describe the purpose of the PR. Is it just the code refactoring or it also fixes some problem or introduces new features ?

**Comment by chaen** [comment]
This PR does not need reviewing for now, it really is just playing around, and it stays open for the sake of running all the tests

**Pull request closed without merging**
