### PR TITLE
[v6r15] Make DIRAC unicode compatible

### PR DESCRIPTION
**Pull request by chaen**
With the usage of json started to appear more unicode strings. This PR attempts to make DIRAC unicode compatible by removing all the instances of StringType. 
All the extensions will have to do the same work. 
be careful to the super ultra mega nasty:
```
if type(value) == type( ' ') 
```
(Thanks Philippe for pointing it out !)

It is mostly trivial changes, but some were a bit more nasty, so please review carefully.
The rest of the replacement type -> isinstance can remain progressive.

### CODE REVIEW

**Comment by fstagni** [comment]
Review OK

**Comment by atsareg** [comment]
In the service handler definitions one can use now basestring, dict, list, etc instead of types.StringTypes, Dict, List. This is more inline with the type checking that we do now.

**Comment by atsareg** [comment]
The PR contains conflicts. Can those be resolved, please ?

**Comment by atsareg** [comment]
I have resolved conflicts in my local repository directly from the Chris's remote branch. This PR is therefore closed.

**Pull request closed without merging**
