### PR TITLE
[v6r15] Improved uniqueElements

### PR DESCRIPTION
**Pull request by vipersec**
I have improved uniqueElements, it is **much** faster now.

Here are some data from the performance benchmarking that I made using a list of 20 thousand numbers (unique and non-unique):
```
1) Old uniqueElements time:  0.752 seconds
2) New uniqueElements time:  0.002 seconds
```

### CODE REVIEW

**Comment by fstagni** [comment]
In DIRAC, we use 2 spaces instead of 4 for tabs :)

Can you also make AppendUnique  faster (same module)

**Comment by vipersec** [comment]
@fstagni 
I can try but I don't know how much faster I can make it, since `AppendUnique` needs only `0.0002 seconds` in order to add an element to the same list according to my tests.

**Comment by fstagni** [comment]
Alright, as you say it probably doesn't make much sense!

**Comment by atsareg** [comment]
Review OK

**Pull request merged**
