### PR TITLE
[v6r19] New logging system integration

### PR DESCRIPTION
**Pull request by aldbr**
I just removed the comment on the new logging system initialization line, so from now, we will use this new one.

### CODE REVIEW

**Comment by fstagni** [comment]
Logging unit tests are now failing, with
```
>     self.assertEqual("UTCFrameworkNOTICE:message\n", logstring1)
E     AssertionError: 'UTCFrameworkNOTICE:message\n' != 'UTCWMSNOTICE:message\n'
```

**Comment by aldbr** [comment]
Very strange, there is no error on my machine, I will try to find the problem.

**Comment by fstagni** [comment]
There are still failures;

**Comment by atsareg** [comment]
Is the test failure being looked at ?

**Comment by chaen** [comment]
@aldbr is on vacation until Tuesday morning, and will fix it as soon as he is back.

**Pull request closed without merging**
