### PR TITLE
[v7r1] VOMSSecurityManager replacing VOMSPolicy

### PR DESCRIPTION
**Pull request by atsareg**
The new mecanism for dynamic loading of the DFC plug-ins makes SecurityPolicy plugins obsoleted. The PolicyBasedSecurityManager/VOMSPolicy combo is replaced by the VOMSSecurityManager class with the same instantiation method as for other SecurityManagers.

BEGINRELEASENOTES

*DMS

NEW: FileCatalog - added VOMSSecurityManager class
CHANGE: FileCatalog - dropped PolicyBasedSecurityManager and VOMSPolicy classes

*tests
CHANGE: use VOMSSecurityManager for integration instead of PolicyBasedSecurityManager/VOMSPolicy

ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
From the migration point of view, how will that work ? Can we just install a v7r1 DFC service with the existing configuration and it will work, or how will that happen ?

**Comment by atsareg** [comment]
The only case where intervention will be needed is LHCb - changing in the configuration the SecurityManager from PolicyBasedSecurityManager to VOMSSecurityManager. VOMSSecurityManager is actually VOMSPolicy made as a manager

**Comment by chaen** [comment]
Then can you keep the backward compatibility hack to avoid that problem ?

**Comment by chaen** [comment]
ah well in fact it's ok if we change the config before installing, it should not harm then, instructions just have to be damn clear in the wiki

**Comment by atsareg** [comment]
I guess that only LHCb is concerned, I do not know anybody else using VOMSPolicy. So, indeed in the case of LHCb this option must be changed. But I think this is OK, and does not need any backward compatibility hack

**Comment by atsareg** [comment]
I have added instructions to the v7r1 release notes

**Pull request merged**
