### PR TITLE
[v6r16] Added 'Killed' to list of jobs status that can be deleted

### PR DESCRIPTION
**Pull request by fstagni**

### CODE REVIEW

**Comment by andresailer** [comment]
I thought it was a feature that one couldn't delete killed jobs any more :grinning:

**Comment by fstagni** [comment]
oh, really? I forgot about it. What's the rationale? Because if this is the case then they stay in the DB forever, at least for the transformations. CC @VladimirRomanovsky

**Comment by andresailer** [comment]
I just noticed from over release to the next killing jobs was no longer possible via the webapp. (or maybe it was just from old webportal to the webapp??). I though this was intentional. That is why I put the smiley
(for example so users don't kill there jobs and delete them)

**Comment by fstagni** [comment]
Users can't kill not delete jobs, unless it's their jobs. This PR is for enabling the possibility to mark as "Deleted" jobs that are in status "Killed". The JobCleaningAgent by default only works with User (and Test) jobs, but as I can see as of now production jobs that are in status "Killed" are never deleted - please look also in the CLIC setup for confirming that.

**Comment by phicharp** [comment]
Unless someone sees a compelling reason why Killed jobs should not be deleted (which I think was just forgotten!), 
Review OK!

**Pull request merged**
