### PR TITLE
[v6r15] Fall back to IPv4 only if AF_INET6 doesn't work.

### PR DESCRIPTION
**Pull request by sfayer**
Hi,

This is a fix for the IPv6 "Address family not supported by protocol" problems mentioned on the diracgrid-forum mailing list. I think the bug exists in all version which support IPv6.

Regards,
Simon

### CODE REVIEW

**Comment by fstagni** [comment]
Hi, 
in the mail thread on the dirac google forum it was said that the bug affects v6r13. v6r15 is not yet released. Are you sure you don't want to make a PR against rel-v6r13 branch?

Cheers,
Federico

**Comment by sfayer** [comment]
Hi,

I wasn't sure if v6r13 was still being supported... It hadn't had any commits in months, so I thought it'd be best to do it against the development version instead. The bug affects all versions v6r13 and above so it wasn't clear which branch I should have targeted; the patch is short enough that it should be easy to cherry-pick into other branches.

Regards,
Simon

**Comment by fstagni** [comment]
Bug fixes are still accepted for v6r13. Please (re-)make this PR against v6r13, it will make our life easier. Thanks a lot for this!

**Comment by atsareg** [comment]
I can back port this commit to earlier branches if you confirm that it is applicable since v6r13.

**Comment by fstagni** [comment]
Review OK (but needs cherry-pick for v6r14 and maybe v6r13)

**Pull request merged**
