### PR TITLE
[V6r18] add missing group by fields, required from MySQL 5.7

### PR DESCRIPTION
**Pull request by zmathe**

### CODE REVIEW

**Comment by fstagni** [comment]
There is this integration test: https://github.com/DIRACGrid/DIRAC/blob/integration/tests/Integration/AccountingSystem/Test_DataStoreClient.py did you run it?
This will be run anyway in Jenkins but to be sure...

**Comment by zmathe** [comment]
This is only for the DataStore. I modified the ReportGenerator. Accounting is not in a good shape taking account the integration tests.

**Comment by fstagni** [comment]
Right, I see, maybe a test for the report generator should be done then,

**Comment by zmathe** [comment]
I added a test for AccountingDB, but more must be added. It is not trivial to add unit tests.

**Comment by zmathe** [comment]
The new test are failing, but it will work after the merge.

**Comment by fstagni** [comment]
Why would they work after the merge?

**Comment by fstagni** [comment]
...and in fact they fail: https://travis-ci.org/DIRACGrid/DIRAC/builds/247121784?utm_source=email&utm_medium=notification

Zoltan, please fix properly.

**Comment by zmathe** [comment]
My modification was not used, this is the old query:
```sql
SELECT `ac_key_LHCb-Certification_DataOperation_Source`.`value`, `ac_bucket_LHCb-Certification_DataOperation`.`startTime`, `ac_bucket_LHCb-Certification_DataOperation`.`bucketLength`, SUM(`ac_bucket_LHCb-Certification_DataOperation`.`TransferOK`), SUM(`ac_bucket_LHCb-Certification_DataOperation`.`TransferTotal`)-SUM(`ac_bucket_LHCb-Certification_DataOperation`.`TransferOK`) FROM `ac_bucket_LHCb-Certification_DataOperation`, `ac_key_LHCb-Certification_DataOperation_Source` WHERE `ac_bucket_LHCb-Certification_DataOperation`.`startTime` >= 1495324800 AND `ac_bucket_LHCb-Certification_DataOperation`.`startTime` <= 1497963600 AND `ac_bucket_LHCb-Certification_DataOperation`.`Source` = `ac_key_LHCb-Certification_DataOperation_Source`.`id` GROUP BY startTime, `ac_key_LHCb-Certification_DataOperation_Source`.Value ORDER BY startTime
 ```
This means the code which was in this PR was not used. Let me create a new test PR.

**Comment by zmathe** [comment]
stupid me... Yes of course it is failing as I wrote the test using the previous version of the AccountingDB and I forget to update the tests :D sorry for that

**Pull request merged**
