### PR TITLE
[v7r0] Rucio File Catalog prototype

### PR DESCRIPTION
**Pull request by cserf**
BEGINRELEASENOTES

*Resources
NEW: RucioFileCatalog plugin based on Belle II implementation

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Please take care of the failing tests. The first thing to do is to add `rucio` to the conda env files.

**Comment by fstagni** [comment]
Hello, any news on this?

**Comment by chrisburr** [comment]
A few hints for adding the integration tests to help get you started:
1. Rebase on `rel-v7r2` so you get the newer integration tests scripts
2. Try using the `./integration_tests.py` script (see [the docs](https://dirac.readthedocs.io/en/latest/DeveloperGuide/CodeTesting/index.html#running-integration-tests-locally))
3. You can add rucio to the services that are created in docker during the "prepare-environment" step by editing `tests/CI/docker-compose.yml`

It might be best to make this optional by adding an option to the python script instead of editing `docker-compose.yml` but that can be addressed once you have something working with the above advice (LHCb does something similar to get an Oracle database).

**Comment by fstagni** [comment]
> A few hints for adding the integration tests to help get you started:
> 
> 1. Rebase on `rel-v7r2` so you get the newer integration tests scripts
> 2. Try using the `./integration_tests.py` script (see [the docs](https://dirac.readthedocs.io/en/latest/DeveloperGuide/CodeTesting/index.html#running-integration-tests-locally))
> 3. You can add rucio to the services that are created in docker during the "prepare-environment" step by editing `tests/CI/docker-compose.yml`
> 
> It might be best to make this optional by adding an option to the python script instead of editing `docker-compose.yml` but that can be addressed once you have something working with the above advice (LHCb does something similar to get an Oracle database).

A slightly different one (basically just adding a bullet at the beginning):
1. Make the current tests to pass, without adding new ones -- there are failing integration tests, but also e.g. pylint
2. Merge it "straight away", and from that moment on work on v7r2+ version, so you get the newer integration tests scripts
3. Try using the `./integration_tests.py` script (see [the docs](https://dirac.readthedocs.io/en/latest/DeveloperGuide/CodeTesting/index.html#running-integration-tests-locally))
4. You can add rucio to the services that are created in docker during the "prepare-environment" step by editing `tests/CI/docker-compose.yml`

**Comment by fstagni** [comment]
One last thing: please add `rucio-clients` also in https://github.com/DIRACGrid/DIRAC/blob/rel-v7r0/docs/requirements.txt

**Review by fstagni — APPROVED** [review]

**Pull request merged**
