### PR TITLE
[v6r14] Fix always banned check

### PR DESCRIPTION
**Pull request by chaen**
* check whether the always banned policy is applied to a given access type
* make printing the full request prettier
* make the amount of scheduled requests fetched by the FTSAgent a parameter in the CS

### CODE REVIEW

**Comment by phicharp** [comment]
Review OK

**Comment by chaen** [comment]
New commit, please review

**Comment by phicharp** [comment]
review OK again

**Comment by phicharp** [comment]
Again OK! Please add comment in the description

**Comment by chaen** [comment]
done

**Pull request merged**
