### PR TITLE
[v6r14] Fixes in Staging, DM, MJF

### PR DESCRIPTION
**Pull request by phicharp**
* Don't fail getting metadata for staging if at least one staged replica found
* Allow to not get URLs in DM
* Fix printout in optimizer that was saying "single site" and "multiple sites" in two consecutive lines ;-)
* Add recovery of FTS files (in FTSAgent) that can be left in weird statuses when the agent dies
* Protect MJF from 0 logical cores

### CODE REVIEW

**Comment by chaen** [comment]
Review OK for the DMS and the MJF part. 
I let @fstagni  comment for the job scheduling, I am not sure whether your discussion had converged or not :-)

**Comment by phicharp** [comment]
Thanks! For the changes in JobScheduling, I would propose to merge this PR (as it is just identical to what is done now) while we discuss on what the aim of this part was and eventually make a change in a next PR. Otherwise we shall not move... OK with you @fstagni?

**Comment by fstagni** [comment]
Yes OK for me. I am re-doing the mentioned PR for v6r15 anyway.

**Comment by phicharp** [comment]
The 'if failed' is inside the initial 'if failed' which makes sense?
%s removed, thanks!

**Comment by chaen** [comment]
Yes, it does make sense. Review OK

**Pull request merged**
