### PR TITLE
[v6r15] Hosts are presenting Host property

### PR DESCRIPTION
**Pull request by atsareg**
Added a Host group property presented by host certificates that can be used for authorization. Some service methods are meant only to be called by hosts, e.g. host status update for monitoring and logging.

### CODE REVIEW

**Comment by fstagni** [comment]
What's the 'Host' property for?

**Comment by atsareg** [comment]
See updated PR description

**Comment by fstagni** [comment]
I see. Is it used anywhere at the moment?

I would also say this deserves an item in https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-v6r15

**Comment by zmathe** [comment]
Yes. It is available in the SystemAdministrator page, which does not work in certification neither in production. I had to hot fix the SystemAdministrator in production (last time when I deployed the release) The fix in:
https://github.com/DIRACGrid/WebAppDIRAC/pull/250
And if you open the SystemAdministrator using the production web portal, you will see the Extensions.
I have updated the wiki page.

**Comment by andresailer** [comment]
What is the difference between "TrustedHost" and "Host", when should one be used instead of the other?
Also update this page: http://dirac.readthedocs.io/en/latest/AdministratorGuide/Configuration/ConfReference/Tips/Authorization/index.html ?

**Comment by atsareg** [comment]
TrustedHost is a completely different thing and is widely abused now. TrustedHost means that it can behave on behalf of a user, which credentials are passed together with the host credentials. This property is only meant to be used by web portals and REST interfaces. Now, it is often used to say that this is simply a host. This PR adds the Host property in order to avoid using TrustedHost property. All installations should remove TrustedHost property from all the hosts except for the web portals.

**Comment by andresailer** [comment]
Ok, that is good to know. That should definitely go to that doc page and to the next release announcement

**Comment by atsareg** [comment]
Agreed. This doc page is very poor, I will update it

**Comment by atsareg** [comment]
I have found a better solution to this  problem, see a new PR

**Pull request closed without merging**
