### PR TITLE
[v6r15] Specifying correct order when creating bashrc and tcshrc

### PR DESCRIPTION
**Pull request by fstagni**

### CODE REVIEW

**Comment by fstagni** [comment]
This has high priority, because for example install_site.sh always use the integration branch version of dirac-install.py.

**Comment by petricm** [comment]
I confirm install_site.sh is now broken and has to be pre-pended with LD_LIBRARY_PATH. Please merge

**Comment by petricm** [comment]
If you pre-prepend LD_LIBRARY_PATH before ./install_site.sh, you get an error after the restart of the machine:

python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

I would really need this. Please merge.

**Comment by fstagni** [comment]
As a quick fix I merged the same branch into integration with https://github.com/DIRACGrid/DIRAC/pull/2813

**Pull request merged**
