### PR TITLE
[v6r20] Alternative default vo group

### PR DESCRIPTION
**Pull request by fstagni**
For CS/Registry section: I added the possibility to define an "AlternativeDefaultGroup": this option can be used to specify a group name that acts as an alternative default VO group, and to which users would normally be added by hand (maybe as "punishment", like, for LHCb case, the "low priority group"). If a user is added there (and, in theory, removed from the "DefaultGroup"), then it won't be added back to the Default group.

BEGINRELEASENOTES

*CS
NEW: for CS/Registry section: added possibility to define an AlternativeDefaultGroup per VO

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
Here I have put the doc for the new CS option in the "old" place, until we finally decide what to do.

**Comment by atsareg** [comment]
The implementation of the idea is OK but this is a rather delicate point. Note that the VOMS information is considered to be the primary one. So, it might be more logical to "punish" users by assigning a special Role in VOMS ? In this case the user will be scrapped from all the other groups than the one corresponding to this Role.

**Comment by chaen** [comment]
Another VOMS in Role is probably not a good idea. 
The first reason is that it would mean that all the CEs and all the SEs should be instructed about what we want to do with that role. Just imagine the mess :-) They've finally settled on 3 basic roles ! 
The second reason is that very little people are allowed to act on VOMS role.
The final reason is the propagation time. In that case, it's about `downgrading` a user, but you might want to ban an offending user. With VOMS, it takes very long. Within DIRAC, we can have this under control in minutes.

**Comment by atsareg** [comment]
I understand your points but we are violating here the basic principle of the VOMS predominance. We should try to understand the consequences. 

If the user has other roles defined in VOMS - will it still keep the corresponding groups membership ? If I understand the idea, this is a kind of Quarantine group where the users are kept and which blocks having them in any other group, not only the Default one.

**Comment by chaen** [comment]
Don't get me wrong: I agree with you, it is probably a twisted way of doing here, it's too specific.

What is the principle of VOMS predominance ?

I think yes, the idea is to have one of this quarantine group. 

Btw, we will soon be asked to be able to block users at the DIRAC level, independently of VOMS...

**Comment by atsareg** [comment]
Ask Joel - VO user management IS done in VOMS, DIRAC is just reflecting it in its Registry. Me, I do not think that we should overly stick to that. With new authentication mechanisms we are about to abandon VOMS in some cases either replacing it or moving user rights management to DIRAC.

I am more worried about how to do it properly in DIRAC. AlternativeGroup looks to me a temporary solution to some particular case. "Alternative" as the option name does not look appropriate, I would call it QuarantineGroup to express explicitly the intention. Still the question remains what to do with the membership in order groups than the default one.

As for blocking users in DIRAC, we have to introduce user status. One obvious case is when users are getting Suspended in VOMS, they are Suspended(Blocked) in DIRAC as well. What it means operationally, we have to discuss.

**Comment by chaen** [comment]
We do not completely rely on VOMS, at least in LHCb. We have plenty of groups which are pure DIRAC. And some of them have a VOMS attributes, but the list in the registry is not populated from there. But it's true that on the Grid, it's VOMS :-)

I like your idea of calling in Quarantine, and to exclude it from any other group if it is there. 

I think what it means operationally is that we should reject their certificate whenever they try to communicate with a DIRAC service.

**Comment by fstagni** [comment]
I am OK with "quarantine". 

The point is really operational here: we have only few people that are VOMS admins, and we have many more GEOC. If we want to block or quarantine a user, GEOCs should be able to do it.

**Comment by fstagni** [comment]
Sorry, I had to close this one because of weird rebase result. I will open new one ASAP.

**Pull request closed without merging**
