### PR TITLE
[v6r15] Fix TransformationAgent, DataManager and IDR by protocol

### PR DESCRIPTION
**Pull request by phicharp**
* DataManager: was extremely slow when checking active replicas and filtering tape replicas. Probably due to changes in the cached information from RSS?
* TransformationAgent: no need to get replicas URLs back, and use iterators when possible

* IDR: the failed resolution for local SEs was not considered correctly if there were other SEs that were ignored (e.g. because on tape). This the catalogs were incomplete

### CODE REVIEW

**Comment by fstagni** [comment]
Hi @phicharp @vipersec , 
you mention slowness "Probably due to changes in the cached information from RSS?"

For my understanding, of which changes are we talking about?

**Comment by phicharp** [comment]
Frankly I don't know... Not in RSS AFAIU, mostly probably in the StorageElement itself... 
Chris ran the same test as mine on Sunday which was much faster, so it may also have been another problem...
Anyway it was absurd to instantiate a StorageElement for each and every replica, even if the cache was perfect... So the fix can't harm.
In the example of Saturday we had 10,000 files with 3 replicas each which was leading to 90000 instantiations of StorageElement(). With the fix it was reduced to 9*16=144.

**Comment by phicharp** [comment]
What is important now is to get the IDR fix in place quickly in order to have IDR rescheduling instead of jobs failures much later when we cannot get tURLs. 
This was really nasty as it could only occur when files have a local disk replica that was failing and remote tape replicas only... This case was not tested of course ;-)

**Comment by fstagni** [comment]
Review OK

**Comment by phicharp** [comment]
Thanks! As already discussed, I suggest that even though you can add a tag you also add a comment as there is no notification for a tag... and also you are the only one able to do it this way ;-)

**Comment by phicharp** [comment]
oups, it was done, but I didn't receive the notification yet ;-)
Network here is really :(
Apologies!

**Pull request merged**
