### PR TITLE
[WIP] new data logging

### PR DESCRIPTION
**Pull request by chaen**
Replaces https://github.com/DIRACGrid/DIRAC/pull/2575
This is the data logging system for DIRAC. It allows to track all operations on files. It is transparent for users, it does not change the behavior of DIRAC. It is flexible for future additional.

Here is an example of the logging of a put and register operation and of a remove file operation :
$ python dirac/DIRAC/DataManagementSystem/scripts/dirac-dls-sequence.py /lhcb/sub/file2.data

Sequence 1, Caller dirac-dms-add-file.py , UserName coberger , HostName localhost.localdomain , Group devGroup
DataManager.putAndRegister, 2015-08-19 11:50:13, Successful, TargetSE StorageTest1
DataManager.registerFile, 2015-08-19 11:50:14, Successful, TargetSE StorageTest1
FileCatalog.addFile, 2015-08-19 11:50:14, Successful, TargetSE StorageTest1
StorageElement.putFile, 2015-08-19 11:50:14, Successful, TargetSE StorageTest1

Sequence 2, Caller dirac-dms-remove-files.py , UserName coberger , HostName localhost.localdomain , Group devGroup
DataManager.removeFile, 2015-08-19 12:38:20, Successful
FileCatalog.removeFile, 2015-08-19 12:38:20, Successful
FileCatalog.removeReplica, 2015-08-19 12:38:20, Successful, TargetSE StorageTest1
StorageElement.removeFile, 2015-08-19 12:38:20, Successful, TargetSE StorageTest1

It is also possible to have all method calls about one LFN , here is the output:

$ python dirac/DIRAC/DataManagementSystem/scripts/dirac-dls-method-call.py /lhcb/sub/file2.data

Found 8 method calls
2015-08-19 11:50:13, DataManager.putAndRegister, TargetSE StorageTest1, Successful, SequenceID 1
2015-08-19 11:50:14, DataManager.registerFile, TargetSE StorageTest1, Successful, SequenceID 1
2015-08-19 11:50:14, StorageElement.putFile, TargetSE StorageTest1, Successful, SequenceID 1
2015-08-19 11:50:14, FileCatalog.addFile, TargetSE StorageTest1, Successful, SequenceID 1
2015-08-19 12:38:20, FileCatalog.removeFile, Successful, SequenceID 2
2015-08-19 12:38:20, DataManager.removeFile, Successful, SequenceID 2
2015-08-19 12:38:20, StorageElement.removeFile, TargetSE StorageTest1, Successful, SequenceID 2
2015-08-19 12:38:20, FileCatalog.removeReplica, TargetSE StorageTest1, Successful, SequenceID 2

It is possible to get method calls for one method name, it is also possible to precise a date before, a date after or an operation Status.

For sequences, it is possible to get all sequences for an LFN, a user name, a group name, an host name, etc.

### CODE REVIEW

**Comment by atsareg** [comment]
Something is wrong with this PR as it contains irrelevant commits. Please, check

**Comment by chaen** [comment]
As explained, it is because Corentin did a rebase, not a merge, but it should not matter

**Comment by atsareg** [comment]
This is a very impressive development indeed. However, this is a tool which is affecting the whole Data Management system and can put a heavy load on it. The scalability tests of this facility are extremely difficult. Therefore, before merging it, the following things should be added:

- There should be a general flag which activates ( if True ) the system, which is False by default. The flag is an Operations parameter, i.e. VO/setup dependent. Can be possibly implemented as class variable of the main decorator class
- There should be a possibility to define am LFN filter to apply logging only to, for example, production data, but not to user data.
- I think also that there should be a filter defined to limit data logging only for operations initiated by users of certain DIRAC groups. Otherwise a user can trigger zillions of faulty data operations that will all fail but will put a heavy and useless load on the system

At least the first item in the list must be implemented before the PR can be merged.

**Comment by chaen** [comment]
Yes, for the first point it is obvious, and I meant to add that. For the two others, we can certainly use the FC filtering mechanism I implemented.
Btw, scalability tests were done

**Comment by chaen** [comment]
I think you forgot to reopen this one

**Pull request closed without merging**
