### PR TITLE
[v6r21]Codecov setup

### PR DESCRIPTION
**Pull request by petricm**
Call codecov at the end pytest and disable comments on PR

### CODE REVIEW

**Comment by andresailer** [comment]
I think this should go to v6r21

**Comment by petricm** [comment]
Done, but @atsareg did not add #3999 to v6r21 as requested by @fstagni

**Comment by fstagni** [comment]
Please backport @3999 together with PR.

**Comment by petricm** [comment]
Done, since I changed the target branch the connection to travis is severed and the CI result can be observed [here](https://travis-ci.org/petricm/DIRAC/builds/518282820).

**Pull request merged**
