### PR TITLE
[v6r19] v6r19 RSS fixes

### PR DESCRIPTION
**Pull request by fstagni**
BEGINRELEASENOTES

*RSS
FIX: Just better check for key
FIX: handling all meta conditions in DB requests

ENDRELEASENOTES

### CODE REVIEW

**Comment by zmathe** [comment]
ops sorry. This is WIP :)

**Comment by fstagni** [comment]
I should be done with this PR, please review

**Comment by fstagni** [comment]
Review, please

**Comment by chaen** [comment]
review OK to me. But boy, this DB is reaaaaally convoluted :D

**Pull request merged**
