### PR TITLE
[WIP][v7r1] Allow to change SSL methods with M2Crypto

### PR DESCRIPTION
**Pull request by chaen**
BEGINRELEASENOTES
*Core
NEW: introduce `DIRAC_M2CRYPTO_SSL_METHODS` to configure accepted protocols

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
CC @hmiyake after today's discussion at BiLD

**Comment by chrisburr** [comment]
Does this need to target an older branch to meet @hmiyake's needs?

**Comment by hmiyake** [comment]
Applied the patch to v7r0p46 (it works with v7r0!)

[DIRAC_M2CRYPTO_SSL_METHODS=TLSv1:TLSv2:TLSv3]
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -tls1 2>/dev/null |grep Cipher
New, TLSv1/SSLv3, Cipher is AES256-SHA
    Cipher    : AES256-SHA
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -tls1_2 2>/dev/null |grep Cipher
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
    Cipher    : AES256-GCM-SHA384
[DIRAC_M2CRYPTO_SSL_METHODS=TLSv2:TLSv3]
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -tls1 2>/dev/null |grep Cipher
New, (NONE), Cipher is (NONE)
    Cipher    : 0000
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -tls1_2 2>/dev/null |grep Cipher
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
    Cipher    : AES256-GCM-SHA384

Looks fine!
Actually, however, our security inspector (based on nessus) complains about following ciphers usable by SSLv3.

$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -cipher AES128-SHA 2>/dev/null |grep Cipher
New, TLSv1/SSLv3, Cipher is AES128-SHA
    Cipher    : AES128-SHA
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -cipher AES256-SHA 2>/dev/null |grep Cipher
New, TLSv1/SSLv3, Cipher is AES256-SHA
    Cipher    : AES256-SHA
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -cipher CAMELLIA128-SHA 2>/dev/null |grep Cipher
New, TLSv1/SSLv3, Cipher is CAMELLIA128-SHA
    Cipher    : CAMELLIA128-SHA
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -cipher CAMELLIA256-SHA 2>/dev/null |grep Cipher
New, TLSv1/SSLv3, Cipher is CAMELLIA256-SHA
    Cipher    : CAMELLIA256-SHA

Since SSLv3 and TLS v1.0 are already invalidated by this patch, it is a false alarm, we think.
Although we already reported the issue, this alarm may not stop until the company fixes the issue.

Can we override DEFAULT_SSL_CIPHERS too, so that we can explicitly invalidate specific ciphers?

**Comment by chaen** [comment]
OK I'll add  the same trick for the Cipher

**Comment by chaen** [comment]
Done. Please try with 
`export DIRAC_M2CRYPTO_SSL_CIPHERS='AES256-GCM-SHA384:AES256-SHA256:AES128-GCM-SHA256:AES128-SHA256:HIGH:MEDIUM:RSA:!3DES:!RC4:!aNULL:!eNULL:!MD5:!SEED:!IDEA:!SHA'`

I think this should be ok for your security team ? If not, can you please ask them what do they recommend ?

**Comment by hmiyake** [comment]
[DIRAC_M2CRYPTO_SSL_METHODS=TLSv1:TLSv2:TLSv3]
[DIRAC_M2CRYPTO_SSL_CIPHERS='AES256-GCM-SHA384:AES256-SHA256:AES128-GCM-SHA256:AES128-SHA256:HIGH:MEDIUM:RSA:!3DES:!RC4:!aNULL:!eNULL:!MD5:!SEED:!IDEA:!SHA']
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -tls1 2>/dev/null |grep Cipher
New, (NONE), Cipher is (NONE)
    Cipher    : 0000
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -tls1_2 2>/dev/null |grep Cipher
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
    Cipher    : AES256-GCM-SHA384
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -cipher AES128-SHA 2>/dev/null |grep Cipher
New, (NONE), Cipher is (NONE)
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -cipher AES256-SHA 2>/dev/null |grep Cipher
New, (NONE), Cipher is (NONE)
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -cipher CAMELLIA128-SHA 2>/dev/null |grep Cipher
New, (NONE), Cipher is (NONE)
$ openssl s_client -connect b2dcdev1.cc.kek.jp:9162 -cipher CAMELLIA256-SHA 2>/dev/null |grep Cipher
New, (NONE), Cipher is (NONE)

Perfectly works! 

Also checked by pyGSI and M2Crypto clients and confirmed only the former is refused.

**Comment by chaen** [comment]
Perfect. Do you want me to do it against v7r0 or are you happy the way it is ?

**Comment by hmiyake** [comment]
I'm happy if the PR also goes to v7r0 :)

**Comment by chaen** [comment]
That should make you happy then https://github.com/DIRACGrid/DIRAC/pull/4967

**Pull request closed without merging**
