### PR TITLE
[Only for discussion] use python provided ThreadPool and other

### PR DESCRIPTION
**Pull request by fstagni**
This PR is just for discussion (for now). There are 2 things:

1) Replacing our custom ThreadPool with a "standard python" ThreadPool

I took the [completely undocumented](https://docs.python.org/2/library/multiprocessing.html#module-multiprocessing.dummy) native [python ThreadPool](http://stackoverflow.com/questions/3033952/python-thread-pool-similar-to-the-multiprocessing-pool) and used it instead of our custom ThreadPool implementation in one agent. It works our of the box.
Now, I didn't take a close look of weather there may be a critical capability for which one implementation is "better" than the other. So I am proposing this change only because:
- we'd need to maintain less code
- standard is (usually) better than custom

It should also be noted that a ProcessPool can be instantiated with 

```
from multiprocessing.pool import Pool
p = Pool()
```

and has exactly the same methods as ThreadPool

2) service processes

The change I made simply makes it possible to have several processes per service. I don't know if this has consequences.

### CODE REVIEW

**Comment by chaen** [comment]
You know that by default I am in favor of that type of change, but indeed, we need to carefuly evaluate the change. 

For service processes, without looking in details how it works, the only thing I can think on top of my head is that you might end up with independant processes competing for the same port

**Comment by chaen** [comment]
Just a feedback about the native thread pool. Here the exception handling is "manual", so the thread in which the execution takes place has to catch everything, otherwise the thread just dies.

**Comment by zmathe** [comment]
We are looking for ThreadPoolExecutor (concurrent.futures).  This is the one which works with blocking I/O. I have introduce the futures in #245 in order to fix #246.
I have tested tree different thread pools:
1. DIRAC ThreadPool
2. multiprocessing.pool.ThreadPool
3. concurrent.futures.ThreadPoolExecutor

What I noticed that with blocking I/O only the ThreadPoolExecutor works and this is the library what I like. I also made a performance comparison. I used the thread pools in our web server and I made an RPC call to the Bookkeeping server. I used 50 concurrent clients and the certification system. I run the test during 1 hour. 
Test:
1.) concurrent.futures.ThreadPoolExecutor using 1 Tornado process
2.) concurrent.futures.ThreadPoolExecutor using 2 Tornado processes
3.) multiprocessing.pool.ThreadPool using 1 Tornado process
4.) DIRAC ThreadPool using 1 Tornado process
As the DIRAC ThreadPool and multiprocessing.pool.ThreadPool does not work with blocking IO I was not able to use more than 1 Tornado process.
The results are:
responsetime

As you can see our ThreadPool is not the best one. The multiprocessing.pool.ThreadPool  and concurrent.futures.ThreadPoolExecutor have almost the same performance. But as you can see using 2 tornado processes I can go beyond 1 second, which is very good!

throughput

You can see the throughput of the experiments as you can see we can scale by increasing the number of Tornado processes.

I propose to introduce the futures library to WebAppDIRAC and after that to DIRAC. We have some places where we can introduce without any problem, but we have to test very careful the services.

**Comment by fstagni** [comment]
Thank you for this, very interesting indeed. 

Few minor questions/comments for now:
- can you share code of what you have done to try this one out?
- a "Tornado process" is not a real name, isn't it? Or I don't get what you mean.
- in the plots, you used the same color for "futures1" and "futures2"

**Comment by zmathe** [comment]
Right. I did not used the correct markers. The corrected plots:
responsetime

throughput

Tornado processes are threads. The name is wrong. When a Tornado server started it starts with one thread. But you can configure tornado to use more processes. Until now we are using only one Tornado thread. As Tornado is using blocking I/O using more than one thread the DIRAC ThreadPool and the multiporcessing threadpool do not work. Thats why only the concurrent.futures two times. But I can be 4, 6 Tornado servers using concurrent.futures.
I used the code which already committed: #245.
 @asyncGen 
  def web_getTest(self):
     bk = RPCClient( 'Bookkeeping/BookkeepingManager' )
     result = yield self.threadTask(bk.echo,'zoo')
     callback = {"result":result['Value']}
     self.finish(callback) 

and:
multiprocessing:
self.__threadPool.apply_async(cbMethod, args = targs, kwds = tkwargs )
DIRAC:
#self.__threadPool.generateJobAndQueueIt( cbMethod, args = targs, kwargs = tkwargs )

**Comment by zmathe** [comment]
We need a different test using this new threadPool and without web server (tornado) at front of the service. So we need to call the bk.echo from a DIRAC client... and the service has to use this new ThreadPool.

**Comment by fstagni** [comment]
So, you used tornado coroutines "client" side and `concurrent.futures.ThreadPoolExecutor` server side. Ok, this is more clear now.

**Comment by zmathe** [comment]
In principle both are in the same server side. tornado.coroutines and concurrent.futures are working together, because all calls are executed by a thread: the magic call:
result = yield self.threadTask(bk.echo,'zoo')
only works using tornado.coroutines which is an extension of python coroutines for asynchronous operations. Behind the threadTask method, we have to use a threadPool because we have a blocking I/O (we use RPC call). In principle we have two blocking i/o:
1.) one is solved by tornado.coroutines and yield generator
2. we have our internal blocking i/o which is the RPC call which is solved by concurrent.futures.

**Comment by zmathe** [comment]
I made the same tests using DIRAC services. 
Experiment1
threadpool
througput
Experiment2
threadpool2
througput2

**Comment by zmathe** [comment]
I enabled the processes. The throughput using threads:



The throughput using processes:

**Comment by fstagni** [comment]
Discussions went in other threads. This stays for reference but can be closed.

**Pull request closed without merging**
