### PR TITLE
[8.0] Minor fixes, and removing py2 compatibility

### PR DESCRIPTION
**Pull request by fstagni**

### CODE REVIEW

**Comment by chaen** [comment]
`cls.log` is defined in the children classes, so your fix shouldn't be needed

**Comment by chaen** [comment]
Also I thought we said that while we support a python2 compatible release (so any v7r2), we should not remove all the compatibility in v8 to avoid upstream propagation issue ?

**Comment by fstagni** [comment]
We have already removed compatibility in v8 for already hundreds of files, and we don't see propagation issues. Anyway, at some point we should just bite the bullet.

**Comment by fstagni** [comment]
> `cls.log` is defined in the children classes, so your fix shouldn't be needed
> 
> * Here for tornado: https://github.com/DIRACGrid/DIRAC/blob/integration/src/DIRAC/WorkloadManagementSystem/Service/TornadoJobStateUpdateHandler.py#L12
> * Here for DISET: https://github.com/DIRACGrid/DIRAC/blob/integration/src/DIRAC/Core/DISET/RequestHandler.py#L87

Right. Fixed.

**Review by TaykYoku — APPROVED** [review]

**Pull request merged**
