### PR TITLE
 add submitPool to siteDirector and resolving previous lazy hack of getting submitPool from submitPools of the VO

### PR DESCRIPTION
**Pull request by vmendez**
This is fixing submitPool with a single pool to be matched.
I have test it in dirac.egi.eu and it works.
I have also test v6r15 with single submit pool, not a list, and for some reason the production release is broken.
I have also test the v6r15-pre8 and it is neither working.
Therefore, to my eyes the last stable release is the v6r15-pre7, and it is the one I have used in this integration PR

### CODE REVIEW

**Comment by vmendez** [comment]
I have implemented in a way that works with the previous setup, just with SubmitPools in the VO, but if you add a SubmitPool to SiteDirectorVO then it checks that this one is in the VO list of SubmitPools, then submittin pilots. So dirac operators does not need to change current setup, just if they  have some VO with multiple SubmitPools, then indicating the one used at the corresponding SiteDirectorVO (one site director VO shall use a single SubmitPool).

**Comment by fstagni** [comment]
Hi, few things:
- you should not target integration, but a release branch
- this branch has conflicts
- this PR contains a printout
- this PR changes the releases.cfg, which should never be

**Comment by atsareg** [comment]
This PR is badly done. And it is not clear which problem it solves. I close it now and will discuss with Victor what is the need

**Comment by vmendez** [comment]
@fstagni I am not going to open a new release for this, because it is not a good practice. I am neither going to resolve the broken release v6r15-pre8, which is going to v615 and not working in production for multiple VO portals.
@atsareg  I will do a PR to the v6r15-pre7 which is the last release working in multiple VO instances. To this one I will fix the "hack" taking SubmitPools list as SubmitPool to match, because it onlly works when SumbitPools of the VO is just one submit pool, which is could be fine to LHCb but not to EGI, I am just implementing user requirements and resolving a lazy hack. I whish this is clear enought to your, particularly when you are in the mail thread of the discussion with the user requirements.

**Comment by fstagni** [comment]
@vmendez : a "release branch" is not a new release. A "release branch" is, for example "rel-v6r15", which you should use. Please read about in the developer guide: http://dirac.readthedocs.io/en/rel-v6r15/DeveloperGuide/DevelopmentModel/ContributingCode/index.html#working-on-a-patch

**Comment by vmendez** [comment]
@fstagni fine, this is what I want to do.

**Pull request closed without merging**
