### PR TITLE
[v7r0] Add the magic runes to make scripts work with DIRAC to the examples

### PR DESCRIPTION
**Pull request by marianne013**
BEGINRELEASENOTES
*Docs:UserGuide
CHANGE: Added magic runes to setup DIRAC to job handling the examples.
ENDRELEASENOTES

### CODE REVIEW

**Comment by petricm** [comment]
The text
> Thank you for writing the text to appear in the release notes. It will show up
> exactly as it appears between the two bold lines
> 
> Please follow the template:

should be removed from BEGINRELEASENOTES .... ENDRELEASENOTES

**Comment by marianne013** [comment]
You are right. I tried to update it, but my git is weak.

**Comment by fstagni** [comment]
Thanks. I would suggest you target v6r21 branch. The reason is that when you load `dirac.readthedocs.io` it will go by default to `https://dirac.readthedocs.io/en/latest/` where that `latest` is equal to the content of the `master` branch which in turn is equal to the content of the last production release, which right now is the branch `rel-v6r21`. 

Just:
```
git fetch release
git checkout -b magicRunes release/rel-v6r21
git cherry-pick ec99239e2a7243cc3affa9a48c7744fa202d1569
git push origin magicRunes
```

**Comment by marianne013** [comment]
I made a new, hopefully correct one against v6r21.

**Pull request closed without merging**
