### PR TITLE
[v6r20] DFC: adapt stored procedure to MySQL 5.7

### PR DESCRIPTION
**Pull request by chaen**
This solves an optimizer issue of MySQL 5.7

BEGINRELEASENOTES

*DataManagement
FIX: change the ps_delete_files and ps_delete_replicas_from_file_ids to not lock on MySQL 5.7

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
That's quite a big change. Would it work in MySQL 5.6?

**Comment by chaen** [comment]
I suppose yes. I can apply it to our production instance tomorrow, it is still 5.6

**Comment by atsareg** [comment]
@chaen :  can you please confirm that changes are MySQL 5.6 compatible ?

**Comment by chaen** [comment]
I'm going to try today

**Comment by fstagni** [comment]
Was this tried out?

**Comment by chaen** [comment]
No, not yet. I forgot :D

**Comment by chaen** [comment]
i just tried them out, they do work on MySQL 5.6 
Note that it is not a big scale test, just functionnal

**Pull request merged**
