### PR TITLE
[v7r1] Add GitHub actions

### PR DESCRIPTION
**Pull request by chrisburr**
Closes #4286, see there for discussion.

I've included the merge commit from #4179 as it wasn't added to `rel-v7r1`.

BEGINRELEASENOTES
*Core
NEW/CHANGE/FIX: explanation
FIX: Use subprocess32 if possible for significantly better performance
FIX: TypeLoader should not be a singleton as it has a cache
*FrameworkSystem
FIX: Avoid leaking std(in|out|err) file handles when running `runsvdir`
*Tests
NEW: CI for unit/lint/integration testing with GitHub actions
NEW: Start using shell linting of the test scripts
FIX: Exit quickly if the installation fails to make it easier to find issues
*Doc
NEW: Document how to run integration tests in docker
*Misc
NEW: Add environment.yml file for preparing an environment with conda
ENDRELEASENOTES

### CODE REVIEW

**Comment by chrisburr** [comment]
Can we get this merged so I can backport it to v7r0?

**Comment by chaen** [comment]
UP. @atsareg @fstagni please merge it now, this is really super useful

**Comment by chaen** [comment]
so ?

**Comment by atsareg** [comment]
I will make a usual set of patches tomorrow , 10 oct

**Comment by chrisburr** [comment]
Has been in back ported to v7r0 like mentioned in the BiLD a couple of weeks ago? I can make a PR for it if you’d prefer.

**Comment by atsareg** [comment]
This was not back ported to v7r0, this requires cherry-picking of multiple commits to the v7r1 branch (or there is a smarter way for that ?).  Please, make a PR for it.

**Pull request merged**
