### PR TITLE
[v7r2] added basic infrastructure for VMDIRAC certification tests

### PR DESCRIPTION
**Pull request by marianne013**
BEGINRELEASENOTES

*tests
NEW: added a helloworld test for the (yet to be implemented) cloud testing in certfication

ENDRELEASENOTES

### CODE REVIEW

**Comment by fstagni** [comment]
You could just add the new test job definition to the existing test script, no need IMHO to create a new "TestUserCloudJobs.py". Or is there a good reason?

**Comment by marianne013** [comment]
I thought about this, but then I figured that 
a) it tests a different bit of infrastructure (VMDIRAC) than the other tests 
b) not sure it'll work with dteam and it might have to use gridpp, so no everyone could run the test
and 
c) who knows what the 'real' test will be if I can come up with one 
so I figured it would be safer to keep it separate.
But I am not too bothered either way. Your call.

**Comment by fstagni** [comment]
Fine, keep it. Just fix:

```
./src/DIRAC/tests/Utilities/testJobDefinitions.py:142:1: E302 expected 2 blank lines, found 1
./tests/System/unitTestUserCloudJobs.py:55:1: E303 too many blank lines (3)
./tests/System/unitTestUserCloudJobs.py:59:1: E305 expected 2 blank lines after class or function definition, found 3
```

**Comment by marianne013** [comment]
Hi Federico, where can I find these errors ? I tried pylinting it by hand, but to no avail.

**Comment by fstagni** [comment]
https://github.com/DIRACGrid/DIRAC/pull/4938/checks?check_run_id=1816801911

You can reproduce with `git diff -U0 upstream/integration  | pycodestyle --diff`

**Review by fstagni — APPROVED** [review]

**Pull request merged**
