### PR TITLE
[v6r12] CLIUtilities: avoid code duplication fcCLI w/ dls; unlimited # args fcCLI funcs.

### PR DESCRIPTION
**Pull request by calancha**
The goal of this PR consist on the following items:

1) Avoid duplication of code between FileCatalogClientCLI.py and dls.py (COMDIRAC):
   Move class DirectoryListing into new file CLIUtilities.

2) Allow unlimited number of files/dirs. arguments in several CLI functions:
   ls, rm, rmreplica, rmdir, mkdir.

3) Follow PEP8 when not conflicting with dirac coding style.

### CODE REVIEW

**Comment by atsareg** [comment]
Hi Tino. You keep sending significant changes to a very old branch of DIRAC. Changes to an old branch are meant to be just bug fixes but not new developments. More than that, those changes are already made in subsequent release but differently. This is certainly creating a mess. I know that your project is constrained to v6r12 because of your production schedule. I suggest that we discuss offline the needs of the ILC project and find a proper way to proceed.

**Comment by andresailer** [comment]
Hi Andrei,

I agree with you for the first part of your comment. I wish Tino had discussed his plans with someone.

Regarding the second part of your comment:
Our project is constrained to v6r12 because the newer releases are broken for us.
If you like to know or needs, you just have to look at our questions and issues in github and the diracgrid-forum. 

Best regards,
Andre

**Comment by calancha** [comment]
Sorry for the misunderstanding but I cannot discuss about the ILC needs:
A. Sailer and M. Petric are the right people to contact for that.

Im open to collaborate with dirac community if they think i can help in some
specific task.

I agree that developing for the old v6r12 is not a good idea.

Regards,
Tino

**Comment by fstagni** [comment]
As discussed, this PR won't be accepted. You are welcome to implement the functionalities you'd like to introduce, if not present already, in v6r13 or even better v6r14 or v6r15.

**Pull request closed without merging**
