### PR TITLE
[v7r0] allow to download proxy for PRIVATE_LIMITED_DELEGATION role

### PR DESCRIPTION
**Pull request by zmathe**
BEGINRELEASENOTES

*FrameworkSystem
FIX: PRIVATE_LIMITED_DELEGATION role can download a proxy

ENDRELEASENOTES

### CODE REVIEW

**Comment by zmathe** [comment]
@atsareg @fstagni I was not able to download my proxy in the following case:
lhcb_user Properties=NormalUser,PrivateLimitedDelegation
If I try to download my proxy using lhcb_user group is failing. It is because the
Registry.getPropertiesForGroup(requestedUserGroup) return ["NormalUser","PrivateLimitedDelegation"] and Properties.PRIVATE_LIMITED_DELEGATION exists in the returned list. 
If I try to download lhcb_prmgr, it work as a dream.
So, it should be "not in" instead of "in"  This is a bug! I think lhcb_user should be able to proxy with the role=user and should not be able to download a proxy with role=production

**Comment by fstagni** [comment]
OK. The failing travis is due to a doc issue that I just fixed, if you rebase on the current v7r0 it will disappear.

**Comment by fstagni** [comment]
...rebase to v622

**Comment by zmathe** [comment]
rebased by #4352

**Pull request closed without merging**
