### PR TITLE
[v6r13] Fixes in BatchSystems to return Message in case of errors

### PR DESCRIPTION
**Pull request by atsareg**
BUGFIX: Torque, GE - methods must return Message field in case of non-zero return status

### CODE REVIEW

**Comment by chaen** [comment]
These values are never used anywhere ? 
I see for example in SSHComputingElement
 output = result['Jobs'][jobStamp]['Output']

**Comment by atsareg** [comment]
??? 
For example here in SSHComputingElement:
      result = resultCommand['Value']         
      if result['Status'] != 0:
        return S_ERROR( 'Failed to get job status: %s' % result['Message'] )

**Comment by chaen** [comment]
When I said value, I meant the key "Output"

**Comment by atsareg** [comment]
If the status is non-zero, the Output is not used

**Comment by fstagni** [comment]
Review OK on my side

**Pull request merged**
