### PR TITLE
[v6r19] Bug with empty JobIDList

### PR DESCRIPTION
**Pull request by zhangxiaomei**
During the upgrade to v6r18p1, when the number of pilots in the site was zero which means JobIDList is empty,  the function of "pilotAgentsDB.getPilotInfo" tried to get the total number of pilots of all the sites instead of the current site. Then the result is "AvailableSlots" get negative value for this site and pilots will never be sent for the site without pilots.

### CODE REVIEW

**Comment by fstagni** [comment]
Xiaomei, please don't update to v6r18p1, please read https://groups.google.com/forum/#!topic/diracgrid-forum/dFa-8hAxC6A The last stable release is v6r17p24. 

Thanks for the fix anyway. I have updated this PR to target the integration branch.

**Comment by fstagni** [comment]
Alternatively, if the fix is needed urgently, we can apply it to v6r17 branch.

**Comment by zhangxiaomei** [comment]
Yes, I took a risk.  This feature is newly introduced since v6r18.

**Comment by zhangxiaomei** [comment]
I have fixed it here and no other problems are found to our case so far.

**Pull request merged**
