### PR TITLE
Package DIRAC with setuptools

### PR DESCRIPTION
**Pull request by drbenmorgan**
As originally raised in #2763, it would be great to have a simpler installation procedure for DIRAC. This PR is a _very preliminary and incomplete_ go at packaging DIRAC using setuptools. 

The diff is quite large in the first commit, as I needed to create a `DIRAC` subdirectory and move the code under this so that setuptools would recognise a correct Python package. No other changes to the sources were made.

The second commit adds the setuptools `setup.py` script. The major features implemented are
- Basic metadata
- Basic install, so `python setup.py install` should work
- Wrapper for running tests, so `python setup.py test` will run the tests (even if some fail)
- Some, but not all requirements.

There's a lot more to do, but I wanted to at least put up this preliminary study to get feedback on whether this is going in the right direction. I'm not an expert on setuptools, so there's certainly room for improvement!

On the "to do list" are:
- Full requirements, some are documented in the README file taken from DIRACGRID/Externals, but need to be cross checked, and which sub packages use them.
- Allow for Client-only installs (connects with working out which requirements go with client/server)
- Additional items from the `dirac-install` script(s)
  - Python version check
  - Programs/Scripts, e.g. `dirac-proxy-init`. Setuptools has the nice [entry points](https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation) feature, but initial work here suggests scripts in Dirac are not directly compatible with this.
  - Certificates?
  - Anything else?

### CODE REVIEW

**Comment by fstagni** [comment]
Thanks for this. 

First of all, a question: is it a strict requirement to have a DIRAC sub-directory where all the DIRAC packages are?
Then my comment is that I would try and concentrate, for the moment, on the client side only. As of today, requirements for the client should include:
- readline
- bzip2
- ncurses
- openssl
- pyGSI
- simplejson
- fuse-python (you may actually ignore this for now)
- pyparsing

DIRAC works with python2.7. I believe it can also work on python2.6 but we've not tried for long.

**Comment by sposs** [comment]
Hi,
Yes, it's mandatory for the setup.py tools to work... This was one of the serious limitations I faced when looking into this a year or so ago...

Comment to @drbenmorgan :+1: 
 - Look into the pbr package for automatic tar-ball naming using the git tag version. (for the setup.py bdist)

**Comment by drbenmorgan** [comment]
> First of all, a question: is it a strict requirement to have a DIRAC sub-directory where all the DIRAC packages are?

As @sposs say, I believe it's mandatory - at least I cannot find a way of doing an install with an extra package level. Also, it makes running the tests difficult from within the project as the modules always `import DIRAC.`.

> Then my comment is that I would try and concentrate, for the moment, on the client side only. As of today, requirements for the client should include:
> 
> readline
> bzip2
> ncurses
> openssl
> pyGSI
> simplejson
> fuse-python (you may actually ignore this for now)
> pyparsing

Thanks - I need to cross check on the recommended way to put requirements on standard library modules into a `setup.py`. I think it's along the lines of

```python
try:
  import bz2
except ImportError:
  sys.exit("This python does not have the bz2 module")

# Or if there's a workaround from PyPI
dirac_install_requires = []
try:
  import json
except ImportError:
  dirac_install_requires.append("simplejson")

setup(
  install_requires = dirac_install_requires
  )
```

Regarding the Client/Server distinction, is there a list of which Packages/Modules are 

1. Common to both
2. Specifically for the Client
3. Specifically for the Server

and similarly for tests, scripts and commands? I can then check the relevant tests are passing and
look at providing something like  `--with-{client,server}` installer option(s).

> Comment to @drbenmorgan 
> 
> Look into the pbr package for automatic tar-ball naming using the git tag version. (for the setup.py bdist)

Thanks for the tip @sposs - I've tried to use `pbr`, but couldn't get it to generate correct versions - it always generated '0.0.0-dev<SEEMINGLYRANDOMNUMBER>'. The AUTHORS and ChangeLog was generated o.k., so I'll take a look when I have more time. I think the versioning issue might be due to the format of DIRAC tag names.

**Comment by fstagni** [comment]
Quick answer on the question on Client/Server distinction: up to now the server included all the client packages, and just added more. I would say it makes sense to keep this way of working.

**Comment by sposs** [comment]
As for pbr, yes, it needs StrictVersions. Also, the code must be exactly at the same version as the tag, as it uses the git status to know where it's at. So the setup.py sdist must be the very last command issued, just after the git tag.

**Comment by vincent-legoll** [comment]
Is this work stalled ?

I think this could help fix issue #3269

Please also try to keep an eye on pep8 compliance (maybe not 100%, if that would be too much), but an ALL CAPS MODULE NAME, ugh...
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

The rest of pep8 can be dealt with later, the package name will stay forever.

Anyways a big +1 for this work

**Comment by fstagni** [comment]
Hi,
yes this work is stalled. It started with very good will about an year ago, but after that it was always the "important but not urgent" stuff. In general, I would say that for what regards the packaging and deployment, in DIRAC we are quite behind the today's good practices. 

It should also be noted that in the meanwhile several other changes happened in the DIRAC dependencies, which looks more and more difficult to administer. We still have to fully understand which direction to take.

**Comment by fstagni** [comment]
I close this PR now with the idea of replacing it with something up-to-date in the future.

**Pull request closed without merging**
