### PR TITLE
[v7r3] Fix previous fix in RMS

### PR DESCRIPTION
**Pull request by phicharp**
BEGINRELEASENOTES

* RMS

FIX: if the request ID is an integer the test `is digit()` throws an exception

ENDRELEASENOTES

### CODE REVIEW

**Review by chrisburr — DISMISSED** [review]

**Comment by chaen** [comment]
I think it just would be nicer to catch  `AttributeError` in the list of exception below, but it does not really matter 

```python
In [2]: a = 3

In [3]: a.isdigit()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 a.isdigit()

AttributeError: 'int' object has no attribute 'isdigit'
```

**Comment by phicharp** [comment]
Thanks Chris 1&2!

**Comment by phicharp** [comment]
Oups! I reverted to the initial fix as adding `AttributeError` wouldn't work as expected if `reqID` is an integer: we want it to not go through the `except` clause...

**Comment by phicharp** [comment]
Sorry for the test failures on the commit messages... I always forget whether one needs a space before the ":" or not! ;-)

**Review by chrisburr — APPROVED** [review]

**Review by fstagni — APPROVED** [review]

**Pull request merged**
