### PR TITLE
[WIP][v6r21] Remove ReconnectListener in disconnect

### PR DESCRIPTION
**Pull request by wkrzemien**
As suggested by Chris this removes the infinite loop due to
disconnect/reconnect sequences.

BEGINRELEASENOTES

*Resources/MessageQueue
FIX: Remove infinite loop bug caused by the ReconnectListener.
ENDRELEASENOTES

### CODE REVIEW

**Comment by chaen** [comment]
Please do it against the v6r21 branch, and do not forget to push the tests you wrote for that

**Comment by wkrzemien** [comment]
@chaen Where should I push the tests which are integration ones? The standard unit tests are not useful here
I have tests that use travis with rabbitmq but it is for a specific platform cause I needed sudo

**Comment by chaen** [comment]
in the `tests` folder at the root

**Comment by fstagni** [comment]
Can you please re-open it, directly targeting v6r21? Travis gets confused and ran the tests against integration branch, which fail.

**Comment by wkrzemien** [comment]
yes, sorry.

**Pull request closed without merging**
